### ISSUE TITLE
Parsing a variable named &quot;assert&quot; in pre-1.4 source.

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#138]
New tests with the 2.0a4 release showed that parsing 
&amp;quot;assert&amp;quot; as a Name in pre-1.4 Java is erroneous:

trystero:jdk-1.2.2_012&amp;gt; /Users/kiniry/ESCTools/Escjava/escj 
-da -source 1.2 -sourcepath . -bootclasspath . -typecheck 
`find java -name &amp;quot;*.java&amp;quot;`
ESC/Java version ESCTools-CURRENT-CVS
java/awt/Component.java:2927: Fatal error: Expected a 
Name, got 'assert'
if (assert) {
^
1 error

javafe.parser.ParseType.parseName(Lex) must be updated 
to handle &amp;quot;assert&amp;quot; as an identifier when assert is not a 
keyword.

I'm testing my changes now.

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
