### ISSUE TITLE
ESC/Java2 message about calls is confusing

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#143]
When ESC/Java2 gives an error about a call (esp to a 
constructor) that isn't permitted by an assignable 
clause, it says that "this assignment" isn't permitted, 
when it's not obvious where the assignment is (since it's 
not an assignment at all, but a call).  Examples occur in 
org.jmlspecs.jmlunit.strategies.

Original comment by: leavens

**Comment by linuxlovell** [comment]
thanks www.movied.org
