### ISSUE TITLE
NullPointerException by ESC/Java-2.0a5

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#146]
While trying ESC/Java to stop complaining about a
Modifies clause, I ran into a NullPointerException.

The attached .tgz-file contains a setup for which the
NullPointerException shows up. It appeared after
changing the line 
public class CardTearException extends RuntimeException
into 
public class CardTearException extends CardRuntimeException
in the file
transactionAppletTransformed/CardTearException.java.

(Note that I'm not saying that this change makes sense;
it is just the way I encountered this exception.)

70 penguin [escjava_npe] &gt;  make esctrans
escjava2 \
-classpath . \
transactionAppletTransformed/*.java
ESC/Java version ESCJava-2.0a5
Prover started:0.064 s 4742536 bytes
[0.514 s 4787128 bytes]

transactionAppletTransformed.A ...
transactionAppletTransformed/CardTearException.java:20:
Error: No such constructor CardRuntimeException() in
type javacard.framework.CardRuntimeException
public class CardTearException extends
CardRuntimeException {

^
Fatal error: A type error has occurred at an unexpected
point; unable to continue processing

transactionAppletTransformed.CardTearException ...
[0.199 s 5682056 bytes]

transactionAppletTransformed.CardTearException:
PossibleCT() ...
transactionAppletTransformed/CardTearException.java:33:
Error: There is no assignable clause allowing this
assignment
throw (new CardTearException());
^
transactionAppletTransformed/CardTearException.java:20:
Associated declaration:
public class CardTearException extends
CardRuntimeException {

^
transactionAppletTransformed/CardTearException.java:36:
Error: There is no assignable clause allowing this
assignment
throw (new CardTearException());
^
transactionAppletTransformed/CardTearException.java:20:
Associated declaration:
public class CardTearException extends
CardRuntimeException {

^
[0.868 s 5723792 bytes]  passed

transactionAppletTransformed.CardTearException:
throwIt() ...
[0.063 s 5854224 bytes]  passed

transactionAppletTransformed.CardTearException:
CardTearException() ...
Exception in thread "main" java.lang.NullPointerException
at
escjava.translate.Translate.isStandaloneConstructor(Translate.java:217)
at
escjava.translate.Translate.trBody(Translate.java:84)
at escjava.Main.computeBody(Main.java:860)
at escjava.Main.processRoutineDecl(Main.java:565)
at escjava.Main.processTypeDeclElem(Main.java:501)
at escjava.Main.processTD(Main.java:464)
at escjava.Main.handleTD(Main.java:340)
at javafe.SrcTool.handleCU(SrcTool.java:249)
at escjava.Main.handleCU(Main.java:301)
at javafe.SrcTool.handleAllCUs(SrcTool.java:207)
at
javafe.SrcTool.frontEndToolProcessing(SrcTool.java:143)
at javafe.FrontEndTool.run(FrontEndTool.java:204)
at escjava.Main.compile(Main.java:165)
at escjava.Main.main(Main.java:140)
make: *** [esctrans] Error 1

Original comment by: hubbers

**Comment by linuxlovell** [comment]
thanks www.movied.org
