### ISSUE TITLE
Implicit constructor postconditions in ESC/Java2

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#147]
The full summary, were SF to let me add it, would be:
"Implicit constructor postconditions concerning
fields of reference type formal parameters."

I've added a set of new tests based upon the work of
Bergstra and Loots.  These are really hairy examples
that have been verified with the Loop tool.  Bart
started writing specs for them and trying to perform
verifications with ESC/Java2.  

About half of them focus on the subtleties of static
initialization, thus do not yet work with ESC/Java2 but
will provide good test cases for when we tackle that topic.

Neary all of the other half verify (to Bart's suprise,
since they are nasty).  A few issues came up though,
the first of which has to do with the modification of
fields of a formal parameter of a constructor.

See the file
ESCTools/Escjava/test/nijmegen/JCF/jcf55/c.java

The method m2() verifies properly, but m1 does not. 
m1() uses a constructor that is spec-wise identical to
the method methodX().

There are also issues verifying the precondition of the
constructor X(X x) with respect to verifying that this
!= x, which should be necessary to verify the
postcondition.

Since these bugs have to do with the subtleties of
modifies checking, I'm assigning this to David.

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
