### ISSUE TITLE
SecurityKey &amp; KeySet example.

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#148]
The directory ESCTools/Escjava/test/nijmegen/OCF
contains two new classes that are trimmed-down versions
of classes from Visa's OpenPlatform.  They illustrate
several issues with ESC/Java2.  It is unclear at this
point whether these are bugs or not.

The issues are:

(a) specification of modifies clause for fresh objects.

KeySet.java:29: Warning: Possible violation of modifies
clause (Modifies)
keyArray[--index] = new SecurityKey();
KeySet.java:30: Warning: Possible violation of modifies
clause (Modifies)
keyArray[index].setKey(bArray);
^
Associated declaration is "./SecurityKey.java", line
28, col 33:
@ modifiable keyLen, theKey[*];

(b) array assignment type issues.

KeySet.java:29: Warning: Type of right-hand side
possibly not a subtype of array element type (ArrayStore)
keyArray[--index] = new SecurityKey();

(c) postcondition-&gt;precondition implications.

KeySet.java:30: Warning: Precondition possibly not
established (Pre)
keyArray[index].setKey(bArray);

Perhaps other issues are here as well.

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
