### ISSUE TITLE
remaining scope problem with java/jml fields

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#149]
Esc/java has been upgraded to handle the scope of java and 
jml fields in accordance with JML rules.  In particular:

\- within a Java construct, only java fields are visible and the 
name lookup follows Java rules

\- within a JML construct, both java and jml fields are visible 
and the name lookup follows Java rules applied to both 
types of fields (JML fields include ghost and model fields)

\- This means that a JML field can hide a superclass Java 
field in a JML annotation, though it is not hidden in a Java 
construct.

\- A Java field can hide a superclass JML field; it is hidden for 
both java nd JML name lookup.

\- If the same id is declared in separate supertypes of a class 
or interface then it is an ambiguity error to reference that id 
in the inheriting class.  If one declaration is a JML field and 
one a Java field, then a reference is not an error in a Java 
construct but is an error in a JML construct.

REMAINING SCOPE PROBLEM:

If a class inherits two fields, one a JML declaration in a 
super class and one a Java declaration in an interface, the 
ambiguity error will not be flagged.  A use of the id in a JML 
annotation will simply reference to the JML declaration.

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
