### ISSUE TITLE
Jmldoc misses specifications in refinements

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#150]
Clyde and I were looking at the jmldoc output for the 
class org.jmlspecs.samples.list.list1.ListIterator and we 
found that the specification for the method next() in 
that class as displayed on the output is missing the 
specification case written in the ListIterator.java file.  It 
has the other inherited specifications, but this is 
missing.  We suspect some problem in handling 
refinements.

Original comment by: leavens

**Comment by linuxlovell** [comment]
thanks www.movied.org
