### ISSUE TITLE
A holdover from the old refinement rules

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#152]
In a mass jml run i stumbled across the following error
(after a serious
number of files did check out properly).

[java] parsing
..\..\..\comp\JML\specs\java\lang\NullPointerException.jml
[java] File
"src\org\jmlspecs\samples\stacks\BoundedStackInterface.jml",
line 24,
character 17 error: Invalid suffix sequence in a
refinement. File
"BoundedStackInterface.jml" cannot refine file
"BoundedStackInterface.java".
[java] File suffixes in refinement sequences are
grouped into
the following levels:
[java]   Level 8-- .jml-refined,
[java]   Level 7-- .spec-refined,
[java]   Level 6-- .java-refined,
[java]   Level 5-- .jml,
[java]   Level 4-- .spec,
[java]   Level 3-- .java,
[java]   Level 2-- .refines-jml,
[java]   Level 1-- .refines-spec,
[java]   Level 0-- .refines-java.
[java] A file with a suffix at a higher level
cannot refine one
at a lower level if it is the most refined declaration
(otherwise the
class will not load properly). [JML]
BUILD FAILED:
C:\eclipse3\workspace\jmltest\scripts\tasktest.xml:119:
Java returned: 1
Total time: 13 seconds

The comment David made re. what was going on:
It used to be that the suffixes of the files in the
refinement sequence had to
follow the ordering listed above strictly (with the
additional
suffixes .java-refined, .spec-refined, .jml-refined as
the last allowed
suffixes).  However, the rules were liberalized.  Now
the order is only used to
pick the MRCU out of multiple files with the same type
name -prefix.  After that
one just uses the files in the order designated by the
'refine' statements (they
don't even have to have the same prefix, though if you
don't follow that
convention everyone will get confused).

Original comment by: dacosta123

**Comment by linuxlovell** [comment]
thanks www.movied.org
