### ISSUE TITLE
weird errors when throw new RuntimeException

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#153]
The following small Test.java file:
-------------------------
class Test
{
Test()
{
throw new RuntimeException("Queue is empty");
}
}
-------------------------

gives these (very strange) errors:

$ export CLASSPATH=.
$ escj Test.java
ESC/Java version ESCJava-2.0a5
Prover started:0.019 s 4668008 bytes
[0.128 s 4708600 bytes]

Test ...
/opt/ESCJava-2.0a5/jmlspecs.jar:java/util/regex/Pattern.refines-spec:135:
Error: Method is not declared in the java/class file
boolean endMatch(Matcher matcher, int i,
CharSequence seq);
^
/opt/ESCJava-2.0a5/jmlspecs.jar:java/lang/Character.jml:92:
Error: Field is not declared in the java/class file
static char[][][] charMap;
^
Fatal error: A type error has occurred at an unexpected
point; unable to continue processing
3 errors

Original comment by: marku

**Comment by linuxlovell** [comment]
thanks www.movied.org
