### ISSUE TITLE
Correct paths mentioned in README to User's Guide &amp;amp;c

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#154]
&gt; and would like to be able to access the ESC/Java2
User's Manual
&gt; mentioned in README.first:
&gt;
&gt;   The new "ESC/Java2 User's Manual" is found in the file
&gt;   ESCTools/docs/ESCJAVA-UsersManual.html.  It is
currently in HTML
&gt;   format, but we have plans on moving to Texinfo like
the other main JML
&gt;   documents.
&gt;
&gt; I'm using the binary release ESCJava-2.0a5, and this
does not
&gt; contain any ESCTools (or docs) directory.

Reported by Mark Utting &lt;marku@cs.waikato.ac.nz&gt;.

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
