### ISSUE TITLE
Interface specification not enforced

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#155]
I have the following classes.

public interface IFoo {

```
//@ model instance 
```

org.jmlspecs.models.JMLType t; //fails
    // model instance Boolean t; //works

```
 //@ ensures false;
 void doFoo\(\);
```

}

public class Foo implements IFoo { 

```
public static void main\(String\[\] args\) \{
    IFoo f = new Foo\(\);
    f.doFoo\(\);
\}

public void doFoo\(\) \{        
    System.out.println\("Foo foo"\);
\}
```

}

Correct behavior, as I understand it, would entail that 
the f.dooFoo() call always triggers a runtime exception 
(with jmlrac), since the spec of doFoo is always violated.

However, this is not the case.  No exceptions are 
thrown.  If however, the activate line with JMLType t in 
IFoo interface is removed, which would seem to be 
irrelevant, execution will trigger the exception, which is 
the expected correct behavior.  Also, activating the 
other model line instead (commented out in above 
example), will also result in correct behavior.

The problem appears to be associated with using a 
model field of JMLType or similar type in interface, in 
which case the interface part of the specificaiton (as 
opposed to implementation spec) associated with a 
method call on that interface is not enforced.

I did try supplying the corresponding represents clause 
for the model field to see if that relieved the problem, 
but it did not.

Original comment by: noah75

**Comment by linuxlovell** [comment]
thanks www.movied.org
