### ISSUE TITLE
A type error in Object.jml

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#156]
I use ESCJava-2.0a5 as shipped from 
http://kind.cs.kun.nl/~kiniry/software/ESCJava-2.0a5-30-12-03-binary.tbz
with jmlspecs.jar replaced by the file from
http://kind.cs.kun.nl/~kiniry/software/jmlspecs-jar
on Linux RedHat 9.0, 
kernel: Linux version 2.4.20-8
(bhcompile@stripples.devel.redhat.com) (gcc version
3.2.2 20030222 (Red Hat Linux 3.2.2-5)) #1 Thu Mar 13
17:18:24 EST 2003
java: j2sdk-1_4_2_02-linux-i586.bin as shipped from
java.sun.com

When I run escjava2 as below on an attached Test.java I
obtain
the below mentioned Fatal error.

[alx@szczurolandia ESCJava-2.0a5]$ ./escjava2 Test.java
Guessing ESCTOOLS_RELEASE =
/home/alx/Praca/ESC/ESCJava-2.0a5/.
Warning: Guessing SIMPLIFY = Simplify-1.5.4.linux
ESC/Java version ESCJava-2.0a5
Prover started:0.035 s 4582672 bytes
[0.171 s 4623608 bytes]

Test ...
/home/alx/Praca/ESC/ESCJava-2.0a5/./jmlspecs.jar:java/lang/Object.jml:63:
Error: Invalid types (java.lang.Class and TYPE) in
equality comparison
//@ public represents _getClass &lt;\- \typeof(this);
^
Fatal error: A type error has occurred at an unexpected
point; unable to continue processing
2 errors

Original comment by: alx-sforge

**Comment by linuxlovell** [comment]
thanks www.movied.org
