### ISSUE TITLE
Example escjava2 tcsh script fails on paths w whitespace

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#158]
I've been slowly replacing all csh and tcsh scripts with bash scripts.  
I'll rewrite the example escjava2 script as well.  

Currently, the tcsh-based one will fail with:
tcsh: set: Syntax Error.
if it is run from a path that contains whitespace.

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
