### ISSUE TITLE
Self-checking Javafe

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#159]
This bug report will be used to track our progress in updating the 
specs on the Java front-end packages javafe.*.  

Currently, many of the specs have been updated to reflect recent 
JML syntax.  Many specs are still missing (now required) terminal 
semi-colons.  Some specs have been converted from lightweight to 
heavyweight variants, but the current coverage is ad hoc.  

Some new ghost and model variables have been introduced, and 
they have been one of the main sources for finding new ESC/Java2 
bugs.

For the 2.0a6 release, ESC/Java2 does not check itself.  My goal is 
to have ESC/Java2 self-checking the javafe and escjava packages 
during our beta releases.

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
