### ISSUE TITLE
Jmlunit docs for -testLevel switch need to be updated

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#160]
My invocation
jmlunit --classpath $(CLASSPATH) -d jmlunit
--package --source 1.4 --sourcepath specs:src
-testLevel 2 src/sos/koa
results in the error message
warning: Ignoring command-line argument that does
not exist - 2 [MJC]

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
