### ISSUE TITLE
behavior of + on Strings

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#161]
EscJava does not appear to know that the result of + on Strings is 
a fresh value.  At least it complains about a modification in

class Modifies0 {
/*@ non_null @*/ String one = "", two = ""; //@ in objectState;

public /*@ pure non_null @*/ String one() {
return one;
}

public /*@ pure non_null @*/ String two() {
return two;
}

public final int hashCode() {
return (one() + two()).hashCode();
} // nowarn Modifies;
}

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
