### ISSUE TITLE
jmldoc problem with in/maps clauses

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#162]
Problem: jmldoc no longer shows in and maps clauses in the 
generated documentation.  It turns out this is just the case for
packages and not individual files.  Try, in specs/java/lang,
running jmldoc on Throwable.jml and running jmldoc on java.lang.
The first is ok, the second is not.

Diagnosis:  Changes to the handling of task sequences combined
with some old design for handling packages caused any files from
a package to be handled only to a point shy of typechecking. 
Hence (a) the in and maps clauses were not handled, and (b) even
when (a) was fixed, there were no links to the target datagroups.
This was also related to the problem on duplicate listings of a
class name in the html list of classes down the left side of the
html frame.

\- Now fixed with today's commits.

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
