### ISSUE TITLE
Inherited specs for .class file omitted by jmldoc

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#166]
Given this situation:

package subt;
public class SS {

//@ public invariant i == 0;

//@ requires true;
public void mm() {}
}

package subt;
public class DD extends SS {

public void mm() {}
}

package subt;
public class EE extends DD {

public void mm() {}

}

in which class DD is present only as a .class file.

Running jmldoc -d tt subt will produce html for all 3 classes.
However, the documentation for class DD will not show the 
inherited specifications for the class or for the method mm.
EE does.

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
