### ISSUE TITLE
relative files in -link and -linkoffline in jmldoc

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#167]
jmldoc and javadoc have a bug when using relative directories in
-link and -linkoffline options.  The workaround is to use urls or
absolute path names.

In the command javadoc -d DEST -link LINK, output files are 
placed in the directory DEST, the package-list file is looked for in 
directory LINK, but the links to the html files in the package are 
created presuming the html files are in DEST/LINK (if LINK is a 
directory with a relative path name);
this prevents one from using both -d and -link together without 
kludges (if LINK is relative).

Similarly in javadoc -d DEST -linkoffline LINK PLDIR , the 
package-list file is expected to be at PLDIR/package-list, but 
the links to the html files are presumed to be at DEST/LINK.  

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
