### ISSUE TITLE
Bogus Internal error in jmldoc

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#168]
Running jmldoc on all of JML (e.g. make quiet-jmldocs) produces
the spurious message

Internal error: package sets don't match: [] with: null

This is a bug in the javadoc library.  The workaround is in the
Makefile (in JML2/Make.ProjDefs) - a grep -v filters out this 
message.

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
