### ISSUE TITLE
jmldoc --help

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#169]
jmldoc --help lists all of the command-line options but they are
in an unhelpful order to the user and the format is a bit odd (e.g.
the usage line is in the middle).  This can't be fixed really without
bypassing (and reimplementing) the mjc and javadoc help
structures - currently we utilize the Options handling for the 
mjc/jml options and the javadoc library for the javadoc and doclet
options.

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
