### ISSUE TITLE
Allowing JML specs in Java5 annotations

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#17]
In the long run, it might be interesting to allow JML
annotations to be expressed not only as specially
formatted comments (i.e. /*@ requires foo; */), but
also as Java5 Annotations (i.e. @JML("requires foo;").

This might make parsing annotated code / tool support /
integration into tools easier (and thus more likely to
happen :) ).

Probably not something that can be done right now
though, as i think JML annotations are allowed in some
places where Java5 annotations are allowed (yet).

Original comment by: raboofje

**Comment by davidcok** [comment]
Current JML does allow Java annotations along with JML keywords. Closing
