### ISSUE TITLE
NPE in escjava.translate.TrAnExpr.trSpecExprI

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#171]
The following code causes an NPE.  The code calls a
helper method then throws a non-default exception in a
constructor.

class C
{
C() throws Exception {
helperMethod();
throw new Exception("E");
}

private /*@ helper @*/ void helperMethod() {
return;
}
}

Removing the helper annotation, or throwing using the
default constructor for Exception both cause the NPE to
disappear.

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
