### ISSUE TITLE
Modifies clause checking with multiple spec blocks.

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#172]
The following class erroneously reports a possible
violation of modifies clause for method m(Object).  It
also erroneously reports an unfulfilled postcondition
for m().

---

class M {
boolean b;
Object obj;

/*@ pure @*/ boolean P(Object o) {
return b;
}

/*@ normal_behavior
requires P(o);
modifies \nothing;
ensures !\result;
also
normal_behavior
requires !P(o);
modifies o.owner;
ensures \result;
*/
boolean m(/*@ non_null @*/ Object o) {
if (P(o)) {
return false;
}
//@ set o.owner = this;
return true;
}
}

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
