### ISSUE TITLE
Specifications of java.util collections incorrect

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#173]
Roy Tan reported that JML's specifications of most of
the java.util collectoins are incorrect.  The problem
is that the models used for these specifications are
JML object collections (collections of object
identities) which are compared using == on elements. 
But in java.util the collections use .equals to compare
elements.

I am working on adding operations to
org.jmlspecs.models to allow for proper specification
of the java.util collections.

Original comment by: leavens

**Comment by linuxlovell** [comment]
thanks www.movied.org
