### ISSUE TITLE
Use of maps clause with array member attributes.

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#174]
The following class parses fine with jml 4.1, but does not with 
escjava2 2.0a6.  I believe the indended meaning of the 2nd maps 
expression is clear.

---

class Maps
{
Object [] oa = new Object[100]; //@ in objectState;
//@ maps oa[*] \into objectState;
//@ maps oa[*].* \into objectState;

Maps() {
}
}

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
