### ISSUE TITLE
Verifying assertions in the presense of inheritance.

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#175]
Consider the following code:

class E
{
void m(int i) {
}
}

class Child extends E
{
//@ also
//@ normal_behavior
//@   requires i &gt;= 0;
//@   ensures true;
void m(int i) {
//@ assert i &gt;= 0;
}
}

The assertion will not be checked by ESC/Java.  If one 
renames E.m() so that overriding is not happening, 
Escjava can check the assertion.  Comparing the 
desugared specs of the two situations shows that they 
are identical.

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
