### ISSUE TITLE
Bitwise operations need to be reviewed.

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#177]
It seems that bitwise operations are poorly supported
by the VC generator.  E.g., in the following method

static void nn() {
int i = 1, j = 1;
i = i | 0x100;
// assert i == 257;
// assert 0 &lt;= i && i &lt;= 1000;
// assert i == (1 | 0x100);
}

only the third assertion can actually be verified (!).

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
