### ISSUE TITLE
Specs of exceptions don't allow null arguments

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#220]
Reading the documentation for the exception types, 
such as java.lang.RuntimeException, it seems that all 
of the constructors permit their arguments to be 
null.  However, with the new default non_null, the 
current specifications are not permitting such 
arguments.  This seems incorrect and should be 
fixed.  

I think in this has to be fixed for all of the 
exception types that are documented the 
specifications we ship with JML.

Original comment by: leavens

**Comment by linuxjackto1** [comment]
thanks www.movied.org

**Comment by davidcok** [comment]
Repurposing this to apply to OpenJML.

**Comment by davidcok** [comment]
Fixed all existing exception specs to be nullable. Added some Rac checks to verify the behavior. Also Esc checks to make sure the specs are usable.
