### ISSUE TITLE
Add switch to print out number of VC variables and/or terms

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#24]
To give user feedback on the size of the VC, we should
add a switch that will print out this information. 
I've been dealing with this externally for now by doing
something like:

kind:verified&gt; escjava2 -v -ppvc -routine addElement
ArrayList.java | grep "|" | tr -d \[:blank:\] | sort |
uniq | wc
30      30     848

but this is quite coarse.

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
