### ISSUE TITLE
OpenJML fails to download/install on Eclipse Juno - artifact not found

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#250]
I've tried to install the OpenJML eclipse plugin via http://jmlspecs.sourceforge.net/openjml-updatesite/ in Eclipse Juno. I'm running Ubuntu x64 with Java 7, although this seems to be a web server related problem. 

An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://jmlspecs.sourceforge.net/openjml-updatesite/plugins/org.jmlspecs.OpenJMLUI_0.3.1.jar.
http://jmlspecs.sourceforge.net/openjml-updatesite/plugins/org.jmlspecs.OpenJMLUI_0.3.1.jar
Artifact not found: http://jmlspecs.sourceforge.net/openjml-updatesite/plugins/org.jmlspecs.Specs_0.3.1.jar.
http://jmlspecs.sourceforge.net/openjml-updatesite/plugins/org.jmlspecs.Specs_0.3.1.jar
Artifact not found: http://jmlspecs.sourceforge.net/openjml-updatesite/plugins/org.jmlspecs.annotation_0.3.1.jar.
http://jmlspecs.sourceforge.net/openjml-updatesite/plugins/org.jmlspecs.annotation_0.3.1.jar
Artifact not found: http://jmlspecs.sourceforge.net/openjml-updatesite/features/org.jmlspecs.openjml.OpenJMLFeature_0.3.1.jar.
http://jmlspecs.sourceforge.net/openjml-updatesite/features/org.jmlspecs.openjml.OpenJMLFeature_0.3.1.jar

Original comment by: mmi1991

**Comment by davidcok** [comment]
Won't fix - Juno no longer supported. Current OpenJML appears to install and work fine on Neon.
