### ISSUE TITLE
URGENT: JML rac "Internal Bug please report" preventing my teaching JML at RMIT University

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#255]
I am compiling a simple demo with JML annotations and I get an internal error :

---

java -jar openjml.jar -rac ListSeq.java Seq.java
ListSeq.java:47: Note: Runtime assertion checking is not implemented for this type or number of declarations in a quantified expression
}
^
ListSeq.java:47: Note: Runtime assertion checking is not implemented for this type or number of declarations in a quantified expression
}
^
Internal JML bug - please report.  BuildOpenJML-20131218-REV3178
## java.lang.ArrayIndexOutOfBoundsException: 277

(see full error text attached)

Also find the two source files attached.

Original comment by: keith-foster

**Comment by davidcok** [comment]
This example compiles OK in current OpenJML - see sf402 in racfiles. Closing the issue
