### ISSUE TITLE
Can't statically check files with HashMaps

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#257]
With the file (not very useful as I made it as small as possible to show the error)
class C {
    private java.util.Hashtable<String,String> m;
}

The command
C:\Users\p0074564\Desktop\JML>java -jar openjml.jar -esc -prover z3_4_3 -exec C:
\Users\p0074564\Desktop\z3-4.3.0-x64\z3-4.3.0-x64\bin\z3.exe -noPurityCheck C.java

Gives the output
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
error: An error while executing a proof script for <init>: (error "line 35 colum
n 49: unexpected character")
1 error

There is no such problem with ArrayList. Perhaps HashMap has not been implemented yet?

Original comment by: ianbayley

**Comment by davidcok** [comment]
Parses correctly. Remaining problem is with reasoning with real arithmetic - weel known as slow with Z3. Closing
