### ISSUE TITLE
In Eclipse package org.jmlspecs.lang does not exist

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#258]
I have this problem whether I try to type check, static check or generate run-time assertion checks.
The exact error message, usually as a pop-up put sometimes in my Problems tab is
package org.jmlspecs.lang does not exist

I have this, for example, with the B.java example on the openjml.org website. I do not have it with the A.java example though.

Original comment by: ianbayley

**Comment by davidcok** [comment]
In any case, the example works now at least without needing to enable JML, as it should
