### ISSUE TITLE
All Eclipse hover error messages turned into "Counterexample: no proof information available"

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#264]
After installing OpenJML in Eclipse Luna, all Java-related error messages reported by hovering over the squiggly line in the Java editor have the same message: "Counterexample: no proof information available".

The errors reported in the Problems view, as well as the hovers over the error marker in the left margin, are unaffected (meaning they are what they should be).

Original comment by: rensink

**Comment by davidcok** [comment]
This is no longer a problem. Closing.
However, showing counterexample info in the spec of a method is -- put that in a new issue.
