### ISSUE TITLE
Perhaps, Do not check for feasibility of assert false statements

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#272]
It may be redundant and confusing and wasteful to check feasibility of assert false statements. That is after all, why users insert them.

Original comment by: davidcok

**Comment by davidcok** [comment]
Leaving these checks in, because (a) expression rewriting with temporaries makes it difficult to tell whether the assert expression is a false literal and (b) users are encouraged to use 'reachable' for the question of reachability rather than assert false.
