### ISSUE TITLE
Example of using the ant tasks

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#273]
I couldnt find any examples of using the ant tasks.  It
took me a few hours to get everything running.  I still
don't understand all of it, but it works.  I'm
submitting a patch because there is no forum.  Delete
it if inappropriate.  Getting in the mailing list just
to send this is too f...ing complicated. (Forums are so
much simpler)

&lt;?xml version="1.0" encoding="UTF-8"?&gt;

&lt;!-- build.xml --&gt;
&lt;!--
This file contains build tasks used during development
to save time. Not to
be shipped to the client.
--&gt;
&lt;project name="ClipPlugin" default="Compile" basedir="."&gt;

```
&lt;property file="ant.properties" /&gt;
&lt;property environment="env"/&gt;


&lt;path id="module.classpath"&gt;
    &lt;fileset dir="$\{env.JAVA\_HOME\}"&gt;
        &lt;include name="lib/\*\*/\*.jar"/&gt;
        &lt;include name="ext/lib/\*\*/\*.jar"/&gt;
    &lt;/fileset&gt;
    &lt;fileset dir="$\{module.lib.dir\}"&gt;
        &lt;include name="\*.jar"/&gt;
    &lt;/fileset&gt;
    &lt;fileset dir="$\{lib.dir\}"&gt;
        &lt;include name="\*.jar"/&gt;
    &lt;/fileset&gt;
&lt;/path&gt;
&lt;property name="classpath.text"
```

refid="module.classpath" /&gt;

```
&lt;taskdef name="jmlcheck"
```

classpath="${module.lib.dir}/jml-release.jar"
classname="org.jmlspecs.ant.tasks.CheckTask" /&gt;
    &lt;taskdef name="jmlcompile"
classpath="${module.lib.dir}/jml-release.jar"
classname="org.jmlspecs.ant.tasks.CompileTask" /&gt;

```
&lt;target name="CompileDBC" if="compile.dbc"&gt;
    &lt;jmlcheck verbose="true" classpath="$\{classpath.text\}" &gt;
        &lt;fileset dir="$\{module.src.dir\}" includes="\*\*/\*.java" /&gt;
    &lt;/jmlcheck&gt;
    &lt;jmlcompile
            classpath="$\{classpath.text\}"
            destination="$\{intermediate.src.dir\}"
            source="false"
            verbose="true"
            recursive="true"
            sourcepath="$\{module.src.dir\}" &gt;
        &lt;fileset dir="$\{module.src.dir\}" includes="\*\*/\*.java" /&gt;
    &lt;/jmlcompile&gt;
&lt;/target&gt;


&lt;target name="CompileNormal" if="compile.normal"&gt;
    &lt;javac   destdir="$\{module.build.dir\}"
            source="1.4"
            target="1.4"
            memoryMaximumSize="512m"
            optimize="true"
            debug="false"&gt;
        &lt;classpath refid="module.classpath" /&gt;
        &lt;src&gt;
            &lt;pathelement location="$\{intermediate.src.dir\}" /&gt;
        &lt;/src&gt;
    &lt;/javac&gt;
&lt;/target&gt;


&lt;target name="ReleaseLocal" depends="CompileNormal"
```

description="Refresh the files on the local server and
reloads the application"&gt;
        &lt;copy todir="${servlet.release.dir}"&gt;
            &lt;fileset dir="${module.build.dir}"/&gt;
        &lt;/copy&gt;
        &lt;copy todir="${plugin.release.dir}"&gt;
            &lt;fileset dir="${module.src.dir}" includes="*.js" /&gt;
        &lt;/copy&gt;
    &lt;/target&gt;

```
&lt;target name="Compile"
```

depends="CompileNormal,CompileDBC"/&gt;

&lt;/project&gt;

Original comment by: hexsel

**Comment by davidcok** [comment]
Obsolete now.
