### ISSUE TITLE
Another doc for you

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#274]
This is a "beginners guide", or perhaps in my view, a
"most useful features guide".  I find it hard to read
the academic documents for JML, and I have a pretty
solid foundation for that.  So I decided to write a
simpler document with some of the features, in an easy
language, without most of the details, and only of the
features I use, which are quite few.

Review it, if you find useful modify, publish, fix,
increase, remove, whatever.  Just be nice and mention
me as having contributing for the file :-)

The format is more or less ugly, as it was just a
snapshot of my work wikiweb.  Feel free to reforma as well.

[]s Gustavo

Original comment by: hexsel

**Comment by davidcok** [comment]
Closing this as either complete or obsolete
