### ISSUE TITLE
refactored traverse methods in org.eclipse.jdt.internal.com

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#280]
For many of the classes in org.eclipse.jdt.internal.compiler.ast
(see the ChangeLog for a complete list), refactored body of the traverse methods into a traverseNoVisitCheck method that can be called, for example, from subclasses.  The purpose of this refactoring is to allow traverse methods to be overridden while not calling visit and endVisit twice, but not requiring that the body be copied and pasted from the overridden traverse method.  No new test cases since this is strictly refactoring of existing methods.

Note that with more refactoring, the traverse methods could potentially be removed from many of these classes, as overriding the traverseNoVisitCheck method would be sufficient.

I was not able to run all tests - see ChangeLog for a more complete description of the issue.

Original comment by: wahlst

**Comment by davidcok** [comment]
Won't fix. Not clear it is still relevant.
