### ISSUE TITLE
creating a java process to auto. have jml compile my source

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#311]
I have all the JML tools jmlc, jmlunit and jmlrac working 
correctly at the command prompt (i have set all relevant 
classpath vars etc).

The problem i am experiencing is creating a java process 
which automatically compiles my jml annotated source 
code using the jml compiler.

```
String task = "\\\JML\\\bin\\\jmlc Queue.java";
String task2 = "jmlc Queue.java";
String task3 = "javac Queue.java";


Runtime current = Runtime.getRuntime\(\);

// ---&gt; Problem
Process process = current.exec\(task\);
// ---&gt; Problem

process.waitFor\(\);

int result = process.exitValue\(\);
```

************************************
OUTPUT

Exception in thread "main" java.io.IOException: 
CreateProcess: \JML\bin\jmlc Queue.java error=2
**************************************

Neither using string task or task2 will work, yet task3 
works fine. (However this is not useful since no jml 
assertions are compiled.) "Jmlc Queue.java " works fine 
at the command prompt (parsing and creating the class 
file).
My QUestions is:
Is there anything i can do to allow me to automate the 
compiling of jml annotated source code. Also i would like 
to automate the use of jmlunit Queue.java, but 
currently i get the same error message when attempting 
to do it as a java process.

Many thanks
James Cornthwaite
james.corn1@ic24.net

Original comment by: cornthwj

**Comment by linuxlovell** [comment]
thanks www.movied.org
