### ISSUE TITLE
JMLC failing on \JML\specs\java\util\Collection.spec

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#312]
JMLC is failing on a simple compile in code that is JML
specific - not mine.  Any help would be appreciated
since I am stuck.  

C:&gt;jmlc
C:\Research\Code\Propel\laser\propel\gui\TriangleIcon.java
parsing
Research\Code\Propel\laser\propel\gui\TriangleIcon.java
parsing Research\Code\JML\specs\java\lang\Object.jml
parsing Research\Code\JML\specs\java\lang\String.jml
parsing Research\Code\JML\specs\java\util\Locale.jml
parsing
Research\Code\JML\specs\java\util\regex\Pattern.refines-spec
parsing
Research\Code\JML\specs\java\util\HashMap.refines-spec
parsing
Research\Code\JML\specs\java\util\AbstractMap.refines-spec
parsing
Research\Code\JML\specs\java\util\AbstractList.refines-spec
parsing
Research\Code\JML\specs\java\util\AbstractCollection.jml
parsing Research\Code\JML\specs\java\lang\Class.jml
typechecking
Research\Code\Propel\laser\propel\gui\TriangleIcon.java
parsing Research\Code\JML\specs\java\lang\Comparable.spec
parsing Research\Code\JML\specs\java\lang\CharSequence.spec
parsing Research\Code\JML\specs\java\util\Collection.spec
parsing Research\Code\JML\specs\java\util\Iterator.spec
parsing Research\Code\JML\specs\java\util\iterator.spec
File
"Research\Code\JML\specs\java\util\Collection.spec",
line 86, character 15
error: Cannot find type "Iterator"

Original comment by: amrels

**Comment by linuxlovell** [comment]
thanks www.movied.org
