### ISSUE TITLE
How to target specific methods with jml-junit?

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#313]
I've read the entirety of "Testing with JML and JUnit", 
but am having problems customizing the autogenerated 
test classes.  My classmates and I are using JML and 
JUnit for a project in the Carnegie Mellon University West 
Coast Campus MS in Software Engineering program, and 
hope you can help.  I'm sure that you are busy but I 
must put in a plug for help at your earliest convenience, 
since we have a project coming due soon.  Please read 
on below.  

In section 5.3, item #5, it is stated:

"Run the test data classs tests, using the JML runtime 
assertion checking libraries, as provided
by the jml-junit script or the jmlrac script; e.g., jml-junit 
Person_JML_TestData
or jmlrac Person_JML_TestData."

Firstly, since 'Foo_JML_TestData' is the superclass, I had 
to run the concrete class, 'Foo_JML__Test'.  

Secondly, I cannot see the complete procedure for 
feeding custom test data to a specific method.  An 
example is given in the article, but it does not cover the 
whole problem.

Third, I do not understand how the test 'Iterator' 
objects work.  This seems crucial, but is not well-
explained in the article.  

Fourth, when I run 'jmlrac' on my test the output seems 
to only indicate that a static check is being made.  Or is 
the class under test actually being instantiated and 
dynamically tested?  

In a related question, Item #5 in section 5.3 of the 
article (quoted above) seems to indicate that 'jmlrac' 
does the same basic thing as 'jml-junit' -- runtime 
assertion testing.  Is this true?

'jml-junit' reports 'nothing to be done' for a given 
autogenerated test with an 'ensures \result' assertion in 
it.  Why might this be?

We are very excited by the watershed development of 
true runtime assertion checking, and hope you can help 
us to use it (soon if possible :) !).  Thank you very much 
(in advance) for your help.

\- Chris Balz
Sourceforge user i.d.: chrisbalz

Original comment by: chrisbalz

**Comment by linuxlovell** [comment]
thanks www.movied.org
