### ISSUE TITLE
Not working with J2sdk1.4.2 ?

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#314]
Hi.

In the README.html file, it is said that the jml checker 
works with j2sdk1.4.1 and j2sdk1.4.2. With j2sdk1.4.1, it 
works fine but when I launch the jml checker with the 
j2sdk1.4.2, it gives me a "can't find type Iterator" error. 
I have tried with JML.4.1 and the last release candidate. 
I am on Windows XP.

Thanks.

Original comment by: th_missi

**Comment by linuxlovell** [comment]
thanks www.movied.org
