### ISSUE TITLE
Latest CVS of JML tools not building under Gentoo

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#332]
During compilation of the latest CVS build of both MJ
and JML2, I'm getting the following build error.

touch classes.stamp
touch antlr.stamp
make[3]: Leaving directory
`/home/dalrain/IS_Code/JML2/org/jmlspecs/checker'
make[3]: Entering directory
`/home/dalrain/IS_Code/JML2/org/jmlspecs/jmldoc'
make[4]: Entering directory
`/home/dalrain/IS_Code/JML2/org/jmlspecs/jmldoc/jmldoc_141'
make[4]: Nothing to be done for `build'.
make[4]: Leaving directory
`/home/dalrain/IS_Code/JML2/org/jmlspecs/jmldoc/jmldoc_141'
make[4]: Entering directory
`/home/dalrain/IS_Code/JML2/org/jmlspecs/jmldoc/jmldoc_142'
make[4]: Nothing to be done for `build'.
make[4]: Leaving directory
`/home/dalrain/IS_Code/JML2/org/jmlspecs/jmldoc/jmldoc_142'
java -Xms128M -Xmx768M org.multijava.util.msggen.Main
JmldocMessages.msg
java -Xms128M -Xmx768M org.multijava.util.optgen.Main
JavadocOptions.opt
java -Xms128M -Xmx768M org.multijava.util.optgen.Main
JmldocOptions.opt
javac Main.java JmldocGUI.java Utils.java
JmldocMessages.java JavadocOptions.java JmldocOptions.java
Utils.java:4: package com.sun.tools.doclets.standard
does not exist
import com.sun.tools.doclets.standard.*;
^
Utils.java:12: cannot resolve symbol
symbol  : class AbstractSubWriter
location: class org.jmlspecs.jmldoc.Utils
static public String
modifierString(AbstractSubWriter w, long m) {
^
Utils.java:15: cannot resolve symbol
symbol  : class FieldSubWriter
location: class org.jmlspecs.jmldoc.Utils
&& (w instanceof FieldSubWriter) ) {
^
3 errors
make[3]: *** [classes.stamp] Error 1
make[3]: Leaving directory
`/home/dalrain/IS_Code/JML2/org/jmlspecs/jmldoc'
make[2]: *** [build-subdirs] Error 1
make[2]: Leaving directory
`/home/dalrain/IS_Code/JML2/org/jmlspecs'
make[1]: *** [build-subdirs] Error 1
make[1]: Leaving directory `/home/dalrain/IS_Code/JML2/org'
make: *** [build-subdirs] Error 1

--------------------------

This is on a Gentoo Linux machine completely up to
date, using the latest version of the java sdk:

\*  dev-java/sun-jdk
Latest version available: 1.4.2.10-r2
Latest version installed: 1.4.2.10-r2
Size of files: 35,604 kB
Homepage:      http://java.sun.com/j2se/1.4.2/
Description:   Sun's J2SE Development Kit
License:       sun-bcla-java-vm

I did source the developer include file before trying
the build, does anyone have any ideas what might be
going on here?  I know the missing file seems to be
part of the javadoc stuff, but I'm not sure what the
problem (or the solution) is.

Original comment by: dalrain

**Comment by linuxjackto1** [comment]
thanks www.movied.org
