### ISSUE TITLE
GUI feedback on proof success

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#35]
It occurred to me in class today that it might be very useful to have ESC flag with a happy looking green info marker "these are the methods I proved correct on the last run". Otherwise, I often have trouble knowing immediately whether it ran and didn't find any problems or ran and failed, and I suspect the students would have similar issues.

-Dan

Original comment by: davidcok

**Comment by davidcok** [comment]
In the OpenJML plugin, this information is available in an OpenJML VIew - showing success or failure of each proof attempt on a method.
