### ISSUE TITLE
Prevent mutual recursion in represents clauses

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#362]
If there is a mutual recursion in represents clauses, the 
runtime assertion checker may go into an infinite loop, 
e.g.,

represents x &amp;lt;- y;
represents y &amp;lt;- x;

Original comment by: cheon

**Comment by davidcok** [comment]
Added a test case. OpenJML has (well before the current 21-0.3 version) implemented a check for circular model field dependencies.
