### ISSUE TITLE
use of italics in jmldoc for interfaces is inconsistent

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#384]
In  jmldoc produced output, an interface named in a line
"Specifications inherited from overridden method in interface XX"
is in italics whereas elsewhere it is not, such as in the line
"Description copied from interface XX"

[ Changing this will result in changes to a bunhc of test results.]

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
