### ISSUE TITLE
quiet and verbose flags

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#385]
Jmldoc has various quiet and verbose flags.  Some are inherited 
from jml and some from javadoc.  They have somewhat 
overlapping meanings and could stand some straightening out.

From javadoc:
-quiet
-verbose

From JML:
--Quiet, -Q
--debug, -c
--quiet, -q
--verbose, -v

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
