### ISSUE TITLE
Add complexity measure user feedback.

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#388]
One of the chief problems that our OOTI students had
was that they didn't have a good idea as to how complex
the verification condition was for the method that they
were attempting to verify.  The looked at verification
complexity as a function of method length and
specification complexity, when in fact it is more
subtle than this.

We should add a new switch to escjava (perhaps
something like -reportComplexity, or -C) that, when
used, will cause escjava2 to report the complexity of
the verification condition.

Good measures to report (IMO) would be the number of
predicates in the VC and the number of free variables
in the VC.

Original comment by: kiniry

**Comment by linuxlovell** [comment]
thanks www.movied.org
