### ISSUE TITLE
Typecheck level 0 Universe type declaration

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#428]
From the JML Ref Manual: 

Some syntax from the Universe type system (see section 18. Universe Type
System) is included in level 0. However, readonly is considered to be in
level X, as is the semantics of the Universe type system. The rep and peer
modifiers are included in level 0 because, in some form, they are
important
to the semantics of several level 0 features
[Mueller-Poetzsch-Heffter-Leavens03] [Mueller-Poetzsch-Heffter-Leavens06].

The \rep and rep ownership-modifiers (see section 18.2 Rep and Peer).
The \peer and peer ownership-modifiers (see section 18.2 Rep and Peer).

Original comment by: cclifton

**Comment by YuyanBao** [comment]
I am not sure the current status of supporting the Universe Type System, but the following example cannot be parsed.

public class LinkedList{
     /*@ rep @*/ Node first;
     
     public LinkedList(Object e){
       first = new /*@ rep @*/ Node();
       first.elem = e;
     }

    public static void main(String args[]){
         System.out.println(5);
     }
     
     
    class Node{
      /*@ peer @*/ Node pre, next;
      Object elem;
      
    }
 }


Error Message:
/tmp/tmpp0ev9f/LinkedList.java:5: error: Expected an identifier, found a JML keyword instead: rep first = new /*@ rep @*/ Node(); ^ /tmp/tmpp0ev9f/LinkedList.java:5: error: '(', '{', or '[' expected first = new /*@ rep @*/ Node(); ^ /tmp/tmpp0ev9f/LinkedList.java:5: error: cannot find symbol first = new /*@ rep @*/ Node(); ^ symbol: method Node() location: class LinkedList 3 errors
