### ISSUE TITLE
openjml error: An internal JML error occurred, possibly recoverable

### ISSUE THREAD

**Issue by sureshgl** [OpenJML/OpenJML#439]
Hi,
 Iam trying OpenJML with Z3, Successfully  git cloned the sources from the top of the tree , build and installed and configured to work. However all the esc based testcases are failing with the following error.

B.Java

public class B { /*@ invariant true; */ }

java -jar openjml.jar -noPurityCheck -esc  -progress -exec /Library/bin/z3 -prover z3_4_3 B.java

Proving methods in B Starting proof of B.B() with prover z3_4_3 error: An internal JML error occurred, possibly recoverable. Please report the bug with as much information as you can. Reason: Unexpected result when querying SMT solver for reason for an unknown result: success Completed proof of B.B() with prover z3_4_3 - with warnings Completed proving methods in B

However z3 is successfully able to execute its generated SAT script located user benchmarks/bench-00001.smt2( uploaded the as B.txt )

Could not figure out the issue, Please kindly help.

Will be able to email you.

Thanks 

[B.txt](https://github.com/OpenJML/OpenJML/files/109311/B.txt)
GL.

**Comment by cpecheur** [comment]
Same problem, Z3 v.4.4.2, MacOS v.10.10.5.  Is anyone looking into this issue?

A detailed log follows.

Ch. Pecheur

```
pecheur@kador:~/Desktop/test openjml% z3 -version
Z3 version 4.4.2
pecheur@kador:~/Desktop/test openjml% uname -a
Darwin kador.dhcp.info.ucl.ac.be 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
pecheur@kador:~/Desktop/test openjml% cat Test.java 
public class Test {
  public static void test() {}
}
pecheur@kador:~/Desktop/test openjml% java -jar ~/soft/openjml-v0.6.3-release-fixed/openjml.jar -exec /usr/local/bin/z3 -esc Test.java
error: An internal JML error occurred, possibly recoverable.  Please report the bug with as much information as you can.
  Reason: Unexpected result when querying SMT solver for reason for an unknown result: success
1 error
```

**Comment by cpecheur** [comment]
Further tries:
- using Z3 4.3.2, same results
- Java version : 
```
openjdk version "1.7.0-internal"
OpenJDK Runtime Environment (build 1.7.0-internal-dmz_2011_07_29_11_50-b00)
OpenJDK 64-Bit Server VM (build 21.0-b17, mixed mode)
```
- Benchmark file is attached.  It shows many extraneous `success` lines upon the last commands (starting with `(push 1)`), suggesting maybe a process communication issue?
- I also tried using Yices 2.2.1 but got an `error "Failed to start process /Users/pecheur/soft/yices-2.2.1/bin/yices : Stream closed"`.

@sureshgl, are you also on MacOS?  Is ESC in OpenJML known to work on Macs?

Thank you for any help,

Charles

[bench-00001.smt2.txt](https://github.com/OpenJML/OpenJML/files/181258/bench-00001.smt2.txt)

**Comment by jsinglet** [comment]
The latest version of the Z3 that works with the current OpenJML is 4.3.0. You can download a build for OS X here, or you can build it yourself: https://github.com/Spekl/static-files/releases/tag/z3-4.3.0-x86.zip

Let me know if that works any better for you.

Best,
JLS

**Comment by cpecheur** [comment]
This works, thank you @jsinglet !  This should be documented somewhere on the website.  Now it is on this thread, at least.

Charles

**Comment by sureshgl** [comment]
Hi Charles,

Thank you,
I tried setting up OpenJML on Mac, could not able to make it work with
either of the solvers i.e Z3 and Yices.
I don't remember  the exact lines of code, but  it was an issue because
OpenJML code could not  communicate  well with the running Z3 process.
Let me know what other information you would like to know.

Regards
GL.



On Sun, Mar 20, 2016 at 5:20 PM, cpecheur <notifications@github.com> wrote:

> Further tries:
>
>    - using Z3 4.3.2, same results
>    - Java version :
>
> openjdk version "1.7.0-internal"
> OpenJDK Runtime Environment (build 1.7.0-internal-dmz_2011_07_29_11_50-b00)
> OpenJDK 64-Bit Server VM (build 21.0-b17, mixed mode)
>
>
>    - Benchmark file is attached. It shows many extraneous success lines
>    upon the last commands (starting with (push 1)), suggesting maybe a
>    process communication issue?
>    - I also tried using Yices 2.2.1 but got an error "Failed to start
>    process /Users/pecheur/soft/yices-2.2.1/bin/yices : Stream closed".
>
> @sureshgl <https://github.com/sureshgl>, are you also on MacOS? Is ESC in
> OpenJML known to work on Macs?
>
> Thank you for any help,
>
> Charles
>
> bench-00001.smt2.txt
> <https://github.com/OpenJML/OpenJML/files/181258/bench-00001.smt2.txt>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenJML/OpenJML/issues/439#issuecomment-198910567>
>



-- 
Suresh GL

**Comment by sureshgl** [comment]
Thank you all,

With 4.3.0 Z3, I am able to  run the OpenJML on Mac.

Regards
GL.

On Tue, Mar 22, 2016 at 10:38 AM, Suresh GL <sureshgl009@gmail.com> wrote:

> Hi Charles,
>
> Thank you,
> I tried setting up OpenJML on Mac, could not able to make it work with
> either of the solvers i.e Z3 and Yices.
> I don't remember  the exact lines of code, but  it was an issue because
> OpenJML code could not  communicate  well with the running Z3 process.
> Let me know what other information you would like to know.
>
> Regards
> GL.
>
>
>
> On Sun, Mar 20, 2016 at 5:20 PM, cpecheur <notifications@github.com>
> wrote:
>
>> Further tries:
>>
>>    - using Z3 4.3.2, same results
>>    - Java version :
>>
>> openjdk version "1.7.0-internal"
>> OpenJDK Runtime Environment (build 1.7.0-internal-dmz_2011_07_29_11_50-b00)
>> OpenJDK 64-Bit Server VM (build 21.0-b17, mixed mode)
>>
>>
>>    - Benchmark file is attached. It shows many extraneous success lines
>>    upon the last commands (starting with (push 1)), suggesting maybe a
>>    process communication issue?
>>    - I also tried using Yices 2.2.1 but got an error "Failed to start
>>    process /Users/pecheur/soft/yices-2.2.1/bin/yices : Stream closed".
>>
>> @sureshgl <https://github.com/sureshgl>, are you also on MacOS? Is ESC
>> in OpenJML known to work on Macs?
>>
>> Thank you for any help,
>>
>> Charles
>>
>> bench-00001.smt2.txt
>> <https://github.com/OpenJML/OpenJML/files/181258/bench-00001.smt2.txt>
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OpenJML/OpenJML/issues/439#issuecomment-198910567>
>>
>
>
>
> --
> Suresh GL
>



-- 
Suresh GL
