### ISSUE TITLE
Documentation about OpenJML completeness.

### ISSUE THREAD

**Issue by layus** [OpenJML/OpenJML#441]
I have read in http://soft.vub.ac.be/~qstieven/sq/session8-solutions.html that 
> OpenJML is not complete: it may miss potential errors.

This is indeed confirmed by my toy example where the increment operation is checked for overflows only when I write i=i+1 explicitly.
Here is the intermediate code (`-show` option) generated by OpenJML in esc mode.

<pre>
<b>// i++ (for loop)</b>
int _JML__tmp13 = i;
int _JML__tmp14 = i + 1;
i = _JML__tmp14;
--
<b>// i++ (while loop)</b>
int _JML__tmp25 = i;
int _JML__tmp26 = i + 1;
i = _JML__tmp26;
--
<b>// i = i + 1 (while loop)</b>
// <b>ArithmeticOperationRange</b> assertion: !(0 < i && 0 < 1) || i <= 2147483647 - 1
final boolean ASSERT_162 = !(0 < i && 0 < 1) || i <= 2147483647 - 1;
/*@ assert ASSERT_162;*/
// <b>ArithmeticOperationRange</b> assertion: !(i < 0 && 1 < 0) || -2147483648 - 1 <= i
final boolean ASSERT_163 = !(i < 0 && 1 < 0) || -2147483648 - 1 <= i;
/*@ assert ASSERT_163;*/
int _JML__tmp37 = i + 1;
i = _JML__tmp37;
--
<b>// i += 1 (while loop)</b>
int _JML__tmp48 = i + 1;
i = _JML__tmp48;
</pre>

We can see that the increment operation are never checked for overflow, except in the `i = i + 1` case.
(Which z3 fails to prove unless we use java or safe math mode).

Can anyone tell me if and where this is documented ? I would expect every numeric expression to be checked for overflows.
Should I expect other incompleteness.

----------
Here is the full code, if someone needs it.

```java
public class MinimumUtil {

        /*@
	  @ requires a != null;
	  @ requires a.length > 0;
	  @ ensures (\forall int i; 0 <= i && i < a.length; a[i] >= \result); 
	  @ ensures (\exists int i; 0 <= i && i < a.length; a[i] == \result); 
	  @*/
	public static /*@ pure @*/ int min(int[] a) {
		int result = a[0];
		
		//@ loop_invariant 1 <= i && i <= a.length;
		//@ loop_invariant (\forall int j; 0 <= j && j < i; a[j] >= result); 
		//@ loop_invariant (\exists int j; 0 <= j && j < i; a[j] == result); 
		//@ decreases a.length - i;
		for(int i = 1; i < a.length; i++) {
			if (a[i] < result) {
				 result = a[i];
			}
		}
		
		return result;
	}

        /*@
	  @ requires a != null;
	  @ requires a.length > 0;
	  @ ensures (\forall int i; 0 <= i && i < a.length; a[i] >= \result); 
	  @ ensures (\exists int i; 0 <= i && i < a.length; a[i] == \result); 
	  @*/
	public static /*@ pure @*/ int min2(int[] a) {
		int result = a[0];
		
		int i = 1;
		//@ loop_invariant 1 <= i && i <= a.length;
		//@ loop_invariant (\forall int j; 0 <= j && j < i; a[j] >= result); 
		//@ loop_invariant (\exists int j; 0 <= j && j < i; a[j] == result); 
		//@ decreases a.length - i;
		while(i < a.length) {
			if (a[i] < result) {
				 result = a[i];
			}
			i++;
		}
		
		return result;
	}

        /*@
	  @ requires a != null;
	  @ requires a.length > 0;
	  @ ensures (\forall int i; 0 <= i && i < a.length; a[i] >= \result); 
	  @ ensures (\exists int i; 0 <= i && i < a.length; a[i] == \result); 
	  @*/
	public static /*@ pure @*/ int min3(int[] a) {
		int result = a[0];
		
		int i = 1;
		//@ loop_invariant 1 <= i && i <= a.length;
		//@ loop_invariant (\forall int j; 0 <= j && j < i; a[j] >= result); 
		//@ loop_invariant (\exists int j; 0 <= j && j < i; a[j] == result); 
		//@ decreases a.length - i;
		while(i < a.length) {
			if (a[i] < result) {
				 result = a[i];
			}
			i = i + 1;
		}
		
		return result;
	}

        /*@
	  @ requires a != null;
	  @ requires a.length > 0;
	  @ ensures (\forall int i; 0 <= i && i < a.length; a[i] >= \result); 
	  @ ensures (\exists int i; 0 <= i && i < a.length; a[i] == \result); 
	  @*/
	public static /*@ pure @*/ int min4(int[] a) {
		int result = a[0];
		
		int i = 1;
		//@ loop_invariant 1 <= i && i <= a.length;
		//@ loop_invariant (\forall int j; 0 <= j && j < i; a[j] >= result); 
		//@ loop_invariant (\exists int j; 0 <= j && j < i; a[j] == result); 
		//@ decreases a.length - i;
		while(i < a.length) {
			if (a[i] < result) {
				 result = a[i];
			}
			i += 1;
		}
		
		return result;
	}
}
```

**Comment by layus** [comment]
Hmm, I found https://github.com/OpenJML/OpenJML/blob/master/OpenJML/src/org/jmlspecs/openjml/esc/JmlAssertionAdder.java#L7555-7560:

```java
    /** Add any assertions to check for problems with unary operations. */
    public void addUnaryChecks(JCExpression that, int op, JCExpression expr) {

        // FIXME - add checks for numeric overflow
        
    }
```

**Comment by layus** [comment]
May I however assume that OpenJML tries to be complete, and that any missing checks are just waiting a good fellow to be fixed ?

**Comment by jsinglet** [comment]
@layus A good place to see what is implemented so far is our features page, here: http://www.openjml.org/features/

@davidcok could speak more directly in terms of what features are planned for the future (apart from what is on that list).

**Comment by layus** [comment]
Thanks @jsinglet. 
Do you (or @davidcok) know if working on OpenJML would make a good master thesis ?
Of course, that would require some research and/or major desing improvements.

I was thinking for example of using hygienic macros to do the translation of java, instead of the complex java code manipulating the AST (for example in [JMLAssertionAdder.java](.
A short research on the internet showed that The Java Syntactic Extender[jse] could be a good tool to do that.

[JMLAssertionAdder.java](https://github.com/OpenJML/OpenJML/blob/master/OpenJML/src/org/jmlspecs/openjml/esc/JmlAssertionAdder.java)
[jse] http://jse.sourceforge.net/

**Comment by leavens** [comment]
Hi Guillaume,

To me that sounds like a good project for an MS thesis.

On Thu, Feb 25, 2016 at 10:35 AM, Guillaume Maudoux <
notifications@github.com> wrote:

> Thanks @jsinglet <https://github.com/jsinglet>.
> Do you (or @davidcok <https://github.com/davidcok>) know if working on
> OpenJML would make a good master thesis ?
> Of course, that would require some research and/or major desing
> improvements.
>
> I was thinking for example of using hygienic macros to do the translation
> of java, instead of the complex java code manipulating the AST (for example
> in [JMLAssertionAdder.java](.
> A short research on the internet showed that The Java Syntactic
> Extender[jse] could be a good tool to do that.
>
> JMLAssertionAdder.java
> <https://github.com/OpenJML/OpenJML/blob/master/OpenJML/src/org/jmlspecs/openjml/esc/JmlAssertionAdder.java>
> [jse] http://jse.sourceforge.net/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenJML/OpenJML/issues/441#issuecomment-188844176>.
>



-- 
        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens <http://www.eecs.ucf.edu/~leavens>
phone: +1-407-823-4758
        leavens@cs.ucf.edu <leavens@eecs.ucf.edu>
