### ISSUE TITLE
OpenJML Eclipse plugin strange behavior

### ISSUE THREAD

**Issue by julioapm** [OpenJML/OpenJML#442]
Does anyone know why Eclipse plugin show -no-internalSpecs when VerboseUI is enabled as options collected by UI to send to OpenJML? I am kind of puzzled since when using OpenJML command line I use -noInternalSpecs. Which one is correct?

Julio Machado

**Comment by davidcok** [comment]
Julio, At some point in history all the negations of options were unified with -no prefixes, as in -no-option. In some cases legacy spellings such as -noInternalSpecs are still supported, but should be considered deprecated.

- David
