### ISSUE TITLE
Java 8?

### ISSUE THREAD

**Issue by JohnL4** [OpenJML/OpenJML#443]
Are there plans to support Java 8? If I understand correctly, I can't use this unless I'm compiling with OpenJDK 7. I'd like to do runtime checking.

**Comment by davidcok** [comment]
It is in progress, though admittedly stalled in the last month or two because of some project deadlines...
- David

**Comment by stasiran** [comment]
Is it possible to see a preview of the specification syntax for Java 8-specific features? We are working on a project written in Java 8. We are considering whether to rewrite the project in Java 7 to use JML or to pretend that Java 8 is there and write specs accordingly.

**Comment by lordaleph** [comment]
Hi everyone! We're currently researching ways to introduce formal verification aspects in an enterprise-level codebase. Our codebase is Java 8-based, so, we had to bump back to Java 7, which is not that great. We've started by automatically generating unit tests with JMLUnitNG, but want to go as far as verification where possible. We have roughly 5 months to achieve any results, or abandon the idea :(

If we manage to prove the usability of OpenJML in a real 50-100k lines codebase, it would be a great step forward in delivering better code. Please, @davidcok, let us know if you have a clearer timeline for releasing Java 8 support, or at least a more stable Java 7 version (last one is v0.6.3, to our knowledge).

Many thanks !

**Comment by leavens** [comment]
Hi,

As far as I see it, the main innovation in Java 8 is lambda expressions.
But these are just syntactic sugar for anonymous inner classes, so I don't
believe that any new specification syntax is needed for them. Are there any
other features in Java 8 that you see that need new specification
formalisms?

For specification and verification of code that uses higher-order methods,
i.e., methods that might take lambdas as arguments, I believe that JML's
model programs are the right mechanism. See our paper

Modular verification of higher-order methods with mandatory calls specified
by model programs
Steve M. Shaner, Gary T. Leavens, David A. Naumann
In International Conference on Object-Oriented Programming, Systems,
Languages and Applications (OOPSLA), Montreal, Canada, October 2007, pages
351-367.

You can get a copy (free) from the JML papers page:
http://www.eecs.ucf.edu/~leavens/JML/papers.shtml.

On Tue, Jun 28, 2016 at 5:36 PM, stasiran <notifications@github.com> wrote:

> Is it possible to see a preview of the specification syntax for Java
> 8-specific features? We are working on a project written in Java 8. We are
> considering whether to rewrite the project in Java 7 to use JML or to
> pretend that Java 8 is there and write specs accordingly.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenJML/OpenJML/issues/443#issuecomment-229191659>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALu2vXjz7mgXDZRphBejOpDAU_NzO0u8ks5qQZPrgaJpZM4Idsn2>
> .
>



-- 
        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens <http://www.eecs.ucf.edu/~leavens>
phone: +1-407-823-4758
        leavens@cs.ucf.edu <leavens@eecs.ucf.edu>

**Comment by davidcok** [comment]
The current releases of OpenJML support and are based on Java 8, though not all features are yet reasoned about in ESC.
