### ISSUE TITLE
Static checker does not take the contents of an int array to be 0 on initialization

### ISSUE THREAD

**Issue by slyubomirsky** [OpenJML/OpenJML#454]
The following code generated a counterexample that should not be possible in Java (running ESC using Z3):

```
public class zeroTest {
    //@ public normal_behavior
    //@   requires size > 0;
    //@   ensures \result != null;
    //@   ensures \result.length == size;
    //@   ensures \result[0] == 0;
    public static int[] allZeroes(int size) {
        int[] arr = new int[size];
        return arr;
    }
}
```

The counterexample generated was the following:
```
Postcondition assertion: _JML___result[0] == 0
			VALUE: _JML___result	 === REF!val!18
			VALUE: 0	 === 0
			VALUE: _JML___result[0]	 === 7
			VALUE: 0	 === 0
			VALUE: _JML___result[0] == 0	 === false
Invalid assertion (Postcondition)
```
An int array should be all zeroes upon initialization, so it should not be possible for the zeroth element of the result to be 7.

The following case, where the array is not referenced in \result, produces the same spurious counterexample:
```
    //@ public normal_behavior
    //@   requires size > 0;
    //@   ensures \result == 0;
    public static int returnZero(int size) {
        int[] arr = new int[size];
        return arr[0];
    }
```

The original function, however, successfully statically checks if I explicitly set element 0 to 0 like so:
```
    public static int[] allZeroes(int size) {
        int[] arr = new int[size];
        arr[0] = 0;
        return arr;
    }
```

I was simply using the ESC option in the Eclipse plugin, so was I perhaps missing some command-line argument or other option to specify the array initialization behavior?

**Comment by davidcok** [comment]
Fixed in 0.7.0; tests to check committed just after 0.7.0 release.
