### ISSUE TITLE
Strange behavior with String (but not other classes) with an ArrayList

### ISSUE THREAD

**Issue by slyubomirsky** [OpenJML/OpenJML#455]
The latest changes fixed the problems leading to the failure of sfBug407 and the NullPointerException in issue #450, but the following code still fails to statically check despite its general similarity to the sfBug407 test:

```
import java.util.ArrayList;

public class ArrList {
    private /*@ spec_public @*/ ArrayList<String> theList;

    //@ public normal_behavior
    //@   assignable theList, theList.objectState;
    //@   requires a != null;
    //@   ensures theList != null;
    //@   ensures theList.size() == 1;
    //@   ensures theList.contains(a);
    public ArrList(String a) {
        theList = new ArrayList<String>();
        theList.add(a);
    }
}
```

Intriguingly, if all the instances of the String type are replaced with Integer (or Object), then the test successfully statically checks (if we run from the command line with the -no-minQuant argument). Otherwise, running from the command line with the -no-minQuant argument leads to the following error:

```
/home/local/ANT/sslyu/pluginTest/ListTest/src/ArrList.java:12: warning: The prover cannot establish an assertion (InvariantLeaveCaller: /home/local/ANT/sslyu/pluginTest/ListTest/src/ArrList.java:22: ) in method ArrList:  (Parameter: a, Caller: ArrList.ArrList(java.lang.String), Callee: java.util.ArrayList.add(E))
    public ArrList(String a) {
                          ^
/home/local/ANT/sslyu/git/Specs/java5/java/lang/CharSequence.jml:30: warning: Associated declaration: /home/local/ANT/sslyu/pluginTest/ListTest/src/ArrList.java:12: 
    //@ public instance invariant charArray.owner == this;
                        ^
2 warnings
```

It's not clear to me why this error arises here, but not in sfBug407 (which works without errors if I run from the command line), which is in principle very similar. The error persists if I move the code shown here into a method that isn't the constructor.

**Comment by davidcok** [comment]
Confirmed fixed on 0.8.19
