### ISSUE TITLE
Pure and non_null annotations functioning differently when class is in same package vs a different one

### ISSUE THREAD

**Issue by slyubomirsky** [OpenJML/OpenJML#456]
Perhaps this is intended behavior, but it seems at the very least counterintuitive to me. My apologies for the long description -- the code is very short, but I had to have several separate files and folders in order to reproduce this error.

In the zip files below, I've included two nearly identical small test cases. However, the one in SamePackagePure.zip statically checks without problems, while the one in SeparatePackagesPure.zip fails to statically check with a strange error.

Here is an outline of what is going on (inspired by java.nio.Buffer and java.nio.ByteBuffer):
- In both cases, I have two abstract classes, Buf and ByteBuf. I specify them in Buf.jml and ByteBuf.jml. The former only defines some fields for specifying positions in the buffer (position, limit, capacity) and the latter has a get(int index) function, which retrieves a byte at that index if it is in bounds.
- I use a model byte[] field to model the contents of the ByteBuf.
- Both cases also have a class called ByteBufClient, which has a simple method that gets the byte at index 0 from a passed-in ByteBuf. The specification stipulates that the ByteBuf not be null, be of at least length 1, etc. However, in SamePackagePure.zip, ByteBufClient is in the same package as Buf and ByteBuf, while in SeparatePackagesPure.zip, ByteBufClient is in a package by itself and imports ByteBuf.

I run OpenJML with the following arguments:
```
-exclude bytebuf.ByteBuf.*  -code-math=java -esc  -exec (path to z3) -specspath ./src (followed by paths to each file)
```
(I use -exclude to ensure the false implementation of get() is ignored by the checker in favor of the specification)

When I run with the files in SamePackagePure.zip, open JML successfully verifies. When I run with SeparatePackagesPure.zip, however, I get the following error:

```
./src/bufclient/ByteBufClient.java:13: warning: The prover cannot establish an assertion (Assignable: ./src/bufclient/ByteBufClient.java:7: ) in method getOne:  \everything
		return b.get(0);
		            ^
./src/bufclient/ByteBufClient.java:7: warning: Associated declaration: ./src/bufclient/ByteBufClient.java:13: 
	/*@ public normal_behavior
	           ^
./src/bytebuf/ByteBuf.jml:11: warning: The prover cannot establish an assertion (UndefinedTooLargeIndex) in method getOne
      @   ensures \result == contents[index];
```

These errors do not seem to make sense to me, and what is more confusing is that if I add "assignable \nothing" to the specification for get() in ByteBuf, this allows SeparatePackagesPure.zip to successfully verify.

This seems very strange to me, since marking the method as pure should already imply that nothing is assignable -- why would this cause problems only when the classes are in different packages?

I suppose there could be an issue with privacy, since the JML Reference Manual says that the pure annotation is equivalent to a private specification that nothing is assignable, while we would be adding the "assigns" clause to the public specification, but should this not also apply within a package then?

[SeparatePackagesPure.zip](https://github.com/OpenJML/OpenJML/files/376570/SeparatePackagesPure.zip)
[SamePackagePure.zip](https://github.com/OpenJML/OpenJML/files/376569/SamePackagePure.zip)

**Comment by slyubomirsky** [comment]
Related: there's a similar disparity with non_null. If I add a line to the specification of getOne in ByteBufClient as follows:
```
@ requires b.contents[0] == (byte) 0x01;
```
then in SeparatePackagesPure, there is again a failure to verify (UndefinedNullDereference) but in SamePackagePure, the verification still succeeds.

In SeparatePackagesPure, the verification succeeds if I add an invariant to ByteBuf:
```
@ public invariant b.contents != null;
```
This is also rather confusing, since contents has non_null in its declaration and should therefore not itself be able to be null either -- why would this failure only happen when the files are in separate packages?

**Comment by davidcok** [comment]
Fixed. The core problem was that @Pure was not being recognized in .jml files when it was not present in a .java file. Not sure why a difference in behavior depending on the package was observed. The test case now succeeds.
