### ISSUE TITLE
Axiom contradicted with uninterpreted function

### ISSUE THREAD

**Issue by slyubomirsky** [OpenJML/OpenJML#460]
Perhaps this is a solver issue but in the following small case, OpenJML found a counterexample when the code appears correct:

```
public class ModelFunctions {   
    /*@ public normal_behavior
      @   assignable \nothing;
      @   ensures true;
      @ public static model pure int chomp(int i);
      @*/

    //@ axiom \forall int i, j; 489 <= i && i < 526 && 489 <= j && j < 526; i == j ==> chomp(i) == chomp(j);

    public static void main(String[] args) {
        //@ ghost int a = chomp(500);
        //@ ghost int b = chomp(500);
        //@ assert a == b;
    }
}
```

The counterexample JML returned when static checking (using Z3) contradicts the axiom. In particular, it included the following:

```
            VALUE: a     === 4
            VALUE: b     === 5
            VALUE: a == b    === false
```

Other rewrites of the above code (e.g., changing the axiom to `//@ axiom \forall int i; 489 <= i && i < 526; chomp(i) == chomp(i)`) result in similar counterexamples.

To phrase this issue in another way, the intent was to say that `chomp()` is deterministic without asserting anything in particular about its output value -- is there another way to express this in JML? Also, what could be wrong with the formulation above?

**Comment by davidcok** [comment]
Same as #474
