### ISSUE TITLE
"Catastrophic JML Internal Error" when using constructor in an \old block (it seems to me)

### ISSUE THREAD

**Issue by slyubomirsky** [OpenJML/OpenJML#463]
Attempting to statically check the below code yielded the following error, the cause of which isn't entirely clear to me: 
```
A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: Ignoring unknown kind of storeref in havoc: \old(\old(_JML___NEWOBJECT_341).a)	Initializer.java	/OldNewObject/src	line 6	JML Problem
```

The code that caused it is below. I had encountered a similar error in other code and this was a constructed attempt to reproduce it; in both that case and this, I used a construct similar to ``\old(new Initializer(a))``.

```
public class Initializer {
	public int a;
	
	/*@ public normal_behavior
	  @   assignable this.a;
	  @   ensures this.a == a;
	  @*/
	public Initializer(int a) {
		this.a = a;
	}
	
	/*@ public normal_behavior
	  @   assignable a;
	  @   ensures this.a == \old(this.a) + 1;
	  @   ensures \fresh(\result);
	  @   ensures \result.equals(\old(new Initializer(a)));
	  @*/
	public Initializer dupe() {
		Initializer other = new Initializer(a);
		a++;
		return other;
	}
	
	/*@ public normal_behavior
	  @   assignable \nothing;
	  @   ensures \result <==> obj instanceof Initializer && ((Initializer) obj).a == a;
	  @*/
	public /*@ pure @*/ boolean equals(Object obj) {
		return obj instanceof Initializer && ((Initializer) obj).a == a;
	}
}
```

**Comment by davidcok** [comment]
Steven,
I'll grant there should not be a catastrophic error.That said, the expression  \old(new Initializer(a)) 
does not make sense. What are you trying to compute?a) method calls within an \old are not really supported and are not intuitive in any caseb) new Initializer() in the postcondition is going to produce something different than the expression in the code so the ensures clause will not be valid.
- David

**Comment by slyubomirsky** [comment]
The construction was perhaps a silly way to express this particular case. The intent of it was to say that the object returned would be equivalent to calling new Initializer(a) in the pre-state. (It would be much simpler in this case to write new Initializer(\old(a)), but there was no easy way to do this in the original context I encountered this problem.) I thought this was consistent with the definition of \old, but perhaps I'm missing some subtlety (I was going off the JML reference manual's description).

**Comment by davidcok** [comment]
1. Methods (and constructors) should not be used in specifications unless they are 'pure'. No warning appears by default about this because a lot of library specs are not properly annotated yet. Also there was an omission in that methods were checked but constructors were not. That is now fixed.

2. Even if a non-pure constructor was used, OpenJml should not fail with an internal error. That is also now fixed.

3. Note that using methds or constructors in \old expressions is not well defined, though in this case I think it is unproblematic.

The following revised test program works OK (test gitbug463a).

public class Initializer {
    public int a;

    /*@ public normal_behavior
      @   ensures this.a == a;
      @ pure */
    public Initializer(int a) {
        this.a = a;
    }

    /*@ public normal_behavior
      @   assignable a;
      @   ensures this.a == \old(this.a) + 1;
      @   ensures \fresh(\result);
      @   ensures \result.equals(\old(new Initializer(a)));
      @*/
    public Initializer dupe() {
        Initializer other = new Initializer(a);
        a++;
        return other;
    }

    /*@ public normal_behavior
      @   assignable \nothing;
      @   ensures \result <==> obj instanceof Initializer && ((Initializer) obj).a == a;
      @*/
    public /*@ pure @*/ boolean equals(Object obj) {
        return obj instanceof Initializer && ((Initializer) obj).a == a;
    }
}

The following one emits the appropriate purity warning, when -purityCheck is on (test gitbug463).

public class Initializer {
    public int a;

    /*@ public normal_behavior
      @   assignable this.a;
      @   ensures this.a == a;
      @*/
    public Initializer(int a) {
        this.a = a;
    }

    /*@ public normal_behavior
      @   assignable a;
      @   ensures this.a == \old(this.a) + 1;
      @   ensures \fresh(\result);
      @   ensures \result.equals(\old(new Initializer(a)));
      @*/
    public Initializer dupe() {
        Initializer other = new Initializer(a);
        a++;
        return other;
    }

    /*@ public normal_behavior
      @   assignable \nothing;
      @   ensures \result <==> obj instanceof Initializer && ((Initializer) obj).a == a;
      @*/
    public /*@ pure @*/ boolean equals(Object obj) {
        return obj instanceof Initializer && ((Initializer) obj).a == a;
    }
}
