### ISSUE TITLE
Inheritance of method specifications fails when extended across two hops

### ISSUE THREAD

**Issue by slyubomirsky** [OpenJML/OpenJML#466]
It appears to me that, when given interfaces A, B, and C, if interface B extends A and C extends B, C does not carry over the method specifications in A even though, according to Java, C is still an instance of A.

This manifested in the following example. Given interfaces, Top, Middle, and Bottom, the test method failed with a counterexample that appears to contradict the specification for Top when static checking.

Top.java:
```
public interface Top {
	/*@ public normal_behavior
	  @   ensures \result == 3;
	  @*/
	public int identifier();
}
```

Middle.java:
```
public interface Middle extends Top {
	/*@ public normal_behavior
	  @   ensures \result == 4;
	  @*/
	public int other();
}
```

Bottom.java:
```
public interface Bottom extends Middle {}
```

Test.java:
```
public class Test {
	/*@ public normal_behavior
	  @   ensures \result == 7;
	  @*/
	public int run(Bottom b) {
		int i = b.other();
		//@ assert i == 4;
		int j = b.identifier();
		//@ assert j == 3;
		
		return i + j;
	}	
}
```

When running the static checker on Test.java, the method came up invalid, yet both counterexamples would be impossible if Bottom fulfilled the specification for Top. The first counterexample proposed an exception on the call to ``b.identifier()`` (but the ``normal_behavior`` clause should not allow one), while the second failed the line ``assert j == 3`` by having ``b.identifier()`` return 2 (contradicting the specification).

However, if I change the type of b from Bottom to Middle or if I change Bottom to also extend Top, then the method successfully verifies, leading me to think the relevant factor is the fact that Bottom as shown above does not directly inherit from Top. (Note also that the errors the solver found had only to do with the method inherited from Top, not the one from Middle.)

**Comment by davidcok** [comment]
Fixed, tested, committed, pushed: commit 4f2614f03ddd683214d0e3739e8fbe50c3f2e966
Bug in the recursive collection of interfaces
