### ISSUE TITLE
use of non-null array fields generate invalid SMT in some cases

### ISSUE THREAD

**Issue by iconmaster5326** [OpenJML/OpenJML#467]
Using this code:
```
public class IntToString {
  public static String intToString(int x) {
    return x + "";
  }
}
```
And with using the command-line arguments '-esc' and '-show', you get some output. On line 6551 is the following SMT output:
```
(assert (= BL_32712_afterIf_419 (=> (distinct java.lang.CharSequence_charArray_1068 NULL) (=> (distinct java.lang.String_CASE_INSENSITIVE_ORDER NULL) (and BL_32990_then_423 BL_32990_else_424)))))
```

In the Java, charArray is of type 'char[]', and is a member of String. in the SMT, 'java.lang.CharSequence_charArray_1068' is of sort '(Array REF REF)'. 'NULL' is of sort 'REF'. Therefore, the expression '(distinct java.lang.CharSequence_charArray_1068 NULL)' does not have the correct argument sorts.

Z3 4.3 accepts this invalidly-typed expression (due to a bug on their end), but Z3 4,4 (and presumably all other provers) do not accept this, returning a type error. It is not correct for OpenJML to be generating this SMT output.

**Comment by davidcok** [comment]
This appears to be fixed by intervening repairs on other bugs.
