### ISSUE TITLE
Problem in z3 4.4 not reported in z3 4.3

### ISSUE THREAD

**Issue by davidcok** [OpenJML/OpenJML#471]
David,
Today I learned some more about the innards of OpenJML : probably more than I need to, but this is "getting a feel" for the tools that support the applied science, of course.  
 
I found the that constructor method of a class generates slightly erroneous SMT, like this:
 
> cat Stub.java
class Stub { }
> openjml -prover=z3_4_4 -esc Stub.java
error: An error while executing a proof script for <init>: (error "line 531 column 1241: Sort mismatch between first argument and argument 2")
1 error
>  
 
It seems the problem is the handling of the ghost field Object.objectTimesFinalized, whose declaration is:
 
> openjml -show -prover=z3_4_4 -esc Stub.java -method Stub | grep declare-fun | grep objectTimesFinalized
(declare-fun java.lang.Object_objectTimesFinalized_9235 () (Array REF Int))
 
But among the uses are:
 
> openjml -show -prover=z3_4_4 -esc Stub.java -method Stub | grep -o '([^(]*([^(]*objectTimesFinalized[^)]*)[^)]*)'
(- 2147483648) (select java.lang.Object_objectTimesFinalized_9235 THIS))
(<= (select java.lang.Object_objectTimesFinalized_9235 THIS) 2147483647)
(distinct (select java.lang.Object_objectTimesFinalized_9235 _JML__tmp1) NULL)
 
including one spot where its value is compared to NULL (instead of 0).
 
My workaround is to use -method all the time, to avoid matching the constructor.
 
Best regards
AJM

**Comment by davidcok** [comment]
This problem shows up in Z3 4.4 but not in Z3 4.3, though I think the SMT is still flawed. It is fixed in commit  efeadffdf982cbc9392cd800e0d0f56bb540ad83

**Comment by iconmaster5326** [comment]
This sounds similar to #467 . Did fixing this fix that issues as well?

**Comment by davidcok** [comment]
Thanks for the alert. That issue is fixed, though by what I did not check. I am curious though, so if you want a break from WhyR, try running that example against a variety of commit points to find the commit that fixed it.
- David
