### ISSUE TITLE
Invariant of outer class not used to discharge an assertion in inner class

### ISSUE THREAD

**Issue by stasiran** [OpenJML/OpenJML#476]
In the following example, the assertion in method bar() is discharged but the one in foo() fails.

public class Repro1 {

    public static final int TEN = 10;
    //@static invariant TEN == 10;

    public static void bar(){
	//@assert TEN > 0;
    }
    
    public static class In {
	public static void foo(){
	    //@ assert TEN > 0;
	}
    }

}

**Comment by davidcok** [comment]
Fixed in commit 90636cdf24b203812459b45fb7fbb7fc68d9f1b1; will be in release 0.7.3
