### ISSUE TITLE
Array clone and Arrays.equals() specs not strong enough.

### ISSUE THREAD

**Issue by stasiran** [OpenJML/OpenJML#477]
OpenJML cannot discharge either assertion in this example.

import java.util.Arrays;

public class Repro3{

    public static void foo(){
	int[] a = {0, 1, 2};
	int[] b = a.clone();
	//@assert b != a;
	//@assert Arrays.equals(a,b);
    }
}

**Comment by davidcok** [comment]
Fixed in commit bce7e7b5e507a883246b0d4ccfc9e1667840097b. See discussion in #479
