### ISSUE TITLE
Eclipse Plugin - Unable to enable JML on a project

### ISSUE THREAD

**Issue by lcollin** [OpenJML/OpenJML#485]
What I'm using:
	Open JML 0.8.5
	Eclipse Luna 4.4.2

Error when I "Enable JML on the project":

	Errors occurred during the build.
	Errors running builder 'JML Builder' on project 'B'.
	NATIVE_HEADER_OUTPUT

Similar Error when I then try to run a static check:

	An internal error occurred during: "Static Checks - Manual".
	NATIVE_HEADER_OUTPUT

**Comment by davidcok** [comment]
To use JML 0.8.* you need Java 8 and you need to be running at least Eclipse Neon. 
Luna is a quite old version of Eclipse.
