### ISSUE TITLE
JML Grammar Issue

### ISSUE THREAD

**Issue by jsinglet** [OpenJML/OpenJML#528]
Unless I am mistaken, according to the JML grammar, the following program should not parse (but it does):

Runnable example: http://www.rise4fun.com/OpenJMLESC/VfX

```java
public class MaybeAdd {
   
    //@ ensures \result == a - b;
    //@ {|
    //@   requires a == b;
    //@  also
    //@   requires a < b;
    //@ |}
    public static int add(int a, int b){
        return a-b;
    }

    public static void main(String args[]){
        System.out.println(add(2,3));
    }
}
```

Specifically, a spec header cannot contain anything except requires clauses. Reference: http://www.eecs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_22.html#SEC230

**Comment by davidcok** [comment]
You are correct that strict JML does not allow this text. OpenJML allows clauses in any order and allows factoring out any kind of clause with the {| |} syntax.
I suppose a warning should be given with the -strictJML option.

- David

**Comment by davidcok** [comment]
New version of OpenJML does not have strict requirements on nested behaviors
