### ISSUE TITLE
Error in arithmetic expression

### ISSUE THREAD

**Issue by adilsonv77** [OpenJML/OpenJML#529]
Happens with this version. When compiles with Runtime checks, it gives me "A catastrophic JML internal error occurred".

public class T {

	private /*@ spec_public @*/ int a;
	private /*@ spec_public @*/ int b;
	private /*@ spec_public @*/ int c;
	
	//@ ensures \result == (a * c)/(0.06 * b);
	public double m() {
		return a/b;
	}
	
}

**Comment by davidcok** [comment]
Compiles without error if you use -spec-math=java

Fixed the error with the default value of -spec-math.  Fix will be in 0.8.20

- David

**Comment by adilsonv77** [comment]
Thank you for your quickly answer... Where does I put this option in Eclipse ?

**Comment by adilsonv77** [comment]
Thank you for your quickly answer. It solved my problem. I configured it in Eclipse with Window > Preferences > OpenJML and Other Options.
