### ISSUE TITLE
Note when inherited spec is pure

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#53]
When a specification of a method is pure, it shows up 
with &amp;quot;pure&amp;quot; in the jmldoc specification for that method in 
the class or interface where it is declared.  But when 
such a specification is inherited, the rest of the 
specification shows up in the documentation, but &amp;quot;pure&amp;quot; 
does not show up in the HTML output.

An example is the specification for the method get() in 
org.jmlspecs.jmlunit.strategies.IntIterator, which inherits 
a a pure get() method from IndefiniteIterator.

This seems useful, because &amp;quot;pure&amp;quot; is inherited.

Original comment by: leavens

**Comment by linuxlovell** [comment]
thanks www.movied.org
