### ISSUE TITLE
Invoking parent method gives an error message and throws StackOverflowError

### ISSUE THREAD

**Issue by adilsonv77** [OpenJML/OpenJML#534]
Let the following code
```
public class P {

	public int calc(int x) {
		return x*2;
	}
	
}
public class S extends P {

	public int calc(int x) {
		return super.calc(x*10);
	}
	
	public static void main(String[] args) {
		S s = new S(); // doesn't matter if s is P or S
		System.out.println(s.calc(3));
	}
}

```
I removed all the JML annotations in this example to demonstrate the problem is not in annotations. 

When I run the S class, the error is 

```
 JML result of numeric operation is out of range of the target type
return super.calc(x*10);
```
And also 

`Exception in thread "main" java.lang.StackOverflowError
`
The same happens when I add the annotations.

I used RAC option into Eclipse.

Sincerely,
Adilson

**Comment by davidcok** [comment]
Fixed for V0.8.20
