### ISSUE TITLE
An issue in installation

### ISSUE THREAD

**Issue by NuhaNasser** [OpenJML/OpenJML#537]
I am building a new tool for my master project. The title of my project is "Enhancing a DBC tool using inference rules of programming logic". The DBC tool that I would like to enhance is openjml. I am using eclipse (Version: Neon.1a Release (4.6.1)), and developing the tool for Java programming language. When I tried to install z3 solver, I faced an error "An error while executing a proof script for <init>: (error "Error writing to Z3 solver: java.io.IOException: Stream closed"). Do you have any suggestion or solution? 
Thanks

**Comment by davidcok** [comment]
Which version of Z3 are you using, and on which platform?

I suggest starting with Z3 4.3. Z3 4.4 certainly has the problem you describe and I have not completed an adapter for 4.5 yet.

- David

**Comment by NuhaNasser** [comment]
Thanks for your reply. The platform that I am using is macOS sierra version 10.12. How do I know the version of Z3? I download it from https://github.com/Z3Prover/z3 2 days ago. 
Thank you

**Comment by davidcok** [comment]
Try the version I’m attaching to the next email ( and let me know if the email or attachment  does not arrive)

**Comment by NuhaNasser** [comment]
I did not receive anything. If possible, please send the file to my email which is nuha_aldowsari@live.com

**Comment by NuhaNasser** [comment]
there is no attachment in this email. May you please attach the file?

Thank you


________________________________

**Comment by pron** [comment]
You can find all versions [here](https://github.com/Z3Prover/z3/releases).

**Comment by davidcok** [comment]
Fixed by providing a version of Z3 4.3 for Mac (which is not available at the link above)
