### ISSUE TITLE
Problems with String and ESC

### ISSUE THREAD

**Issue by JonasRahlf** [OpenJML/OpenJML#544]
When static checking the class below with 0.8.19, the ESC finds an invalid assertion in `main()`. After reviewing the trace several times, i couldn't find the error. The length of `'TestString'` is greater than 0 obviously. But the same error occurs when using other `String` methods e.g. `String.matches()`.

```
public class JMLTraining { //line 3

    /*@ //5
      @ requires s.length() > 0;
      @*/
    public static String copy(final /*@ non_null @*/ String s){
        return s;
    } //10

    public static void main(String[] args) {
        
          copy(new String("TestString"));
    } //15
}
```

**Trace:**
```
home/jonas/Git/bachelorarbeit/eclipse/src/crypto_examples/JMLTraining.java:8: Precondition assertion: _JML__tmp32

			VALUE: _JML__tmp32	 === false
			VALUE: ASSERT_354_145	 === false
			VALUE: _JML__tmp32	 === false
			VALUE: ASSERT_354_145 == _JML__tmp32	 === ???
/home/jonas/Git/bachelorarbeit/eclipse/src/crypto_examples/JMLTraining.java:14:  Invalid assertion (Precondition)
: /home/jonas/Git/bachelorarbeit/eclipse/src/crypto_examples/JMLTraining.java:8:  Associated location
```

The rest of the trace: [trace_JMLTraining_copy.txt](https://github.com/OpenJML/OpenJML/files/1262674/trace_JMLTraining_copy.txt)

Do you might have an idea where that error comes from? I think there is a problem in `CharSequence` somewhere, but i'm not sure.

**Comment by davidcok** [comment]
OpenJML (and solvers) don't support reasoning about Strings at present. New versions of SMT-LIB have a built-in theory for strings, so I'm hoping to use that when solvers support it.

**Comment by JonasRahlf** [comment]
Okay, than maybe it is possible in the future. I appreciate your quick response.
