### ISSUE TITLE
combining system and jmldoc html pages

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#55]
If jmldoc is run on a specification file for a java system class 
without the source for that class being available, then a jmldoc 
html page is produced containing any specifications in that spec 
file.  However, none of the javadoc content that is present in the 
system javadoc file is included.  It would be nice to be able to copy 
the javadoc content from the javadoc page if the java file is not 
present that contains it and combine it with the specifications 
contained in the spec file.

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
