### ISSUE TITLE
Allow \fresh in loop invariants and other method body annotations

### ISSUE THREAD

**Issue by davidcok** [OpenJML/OpenJML#552]

**Comment by leavens** [comment]
Hi David and all,

I also agree with this.

        Regards,

        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens  phone: +1-407-823-4758
        leavens@cs.ucf.edu

**Comment by davidcok** [comment]
Fixed in V0.8.22
