### ISSUE TITLE
Enhance \fresh to be with respect to a label (like \old)

### ISSUE THREAD

**Issue by davidcok** [OpenJML/OpenJML#553]

**Comment by leavens** [comment]
Hi David and all,

This seems like a sensible idea to me.

        Regards,

        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens  phone: +1-407-823-4758
        leavens@cs.ucf.edu

**Comment by davidcok** [comment]
Has been implemented. Closing the issue.
