### ISSUE TITLE
Let accordions stay closed in the Static Check Console when rerunning static checks .

### ISSUE THREAD

**Issue by HansvdLaan** [OpenJML/OpenJML#561]
I have a small feature request for the OpenJML eclipse plugin:

In the Static Check Console, I would like to have the accordions one closed stay closed after the static checks are rerun.

At the moment, whenever I rerun the static checks, all the accordions I closed reopen. This is quite annoying because I have to search again and again for the classes and functions I was working on after I make a small change in my program and/or annotations.  Especially in a project with a lot of JML annotated classes and functions this is quite a tedious task.

**Comment by davidcok** [comment]
Implemented in just released V0.8.23.  The View menu now has a toggle menu item that switches between automatically showing a function item when it is checked, vs. leaving the accordions alone. Background coloring is added to the non-leaf nodes to give a summary of the results of the hidden nodes. This will be changed to s submenu that gives multiple behavior options in the future.
