### ISSUE TITLE
Perform static check on a single method

### ISSUE THREAD

**Issue by samanthasyeda** [OpenJML/OpenJML#564]
Hello,

I am trying to perform static check on a single method using OpenJML. I am using:

OpenJML plugin for Eclipse
Mac OSX
z3 solver

![screen shot 2017-09-28 at 3 37 58 pm](https://user-images.githubusercontent.com/7947620/30989362-0f8b73d8-a463-11e7-91f3-bd2c36614dc7.png)

However, I am getting following error:
![screen shot 2017-09-28 at 3 32 51 pm](https://user-images.githubusercontent.com/7947620/30989409-397c833a-a463-11e7-87f0-f40f9f497cf7.png)

Why is this happening?

**Comment by davidcok** [comment]
This is a hard-to-reproduce situation that has been encountered in the past. The presumed causes are either (a) there are type checking errors that prevent the static checking from being performed or (b) the static check on a single function is performed before any type checking of files is performed.  A fix for the latter is implemented in the just released V0.8.23.
