### ISSUE TITLE
Meaning of "Validity is unknown - no model available" error

### ISSUE THREAD

**Issue by HansvdLaan** [OpenJML/OpenJML#565]
Very often I get the error "Validity is unknown - no model available" when running static checks. Unfortunately I cannot find any documentation on the cause of this problem or how to resolve it.

What does this message mean exactly?
Why can we get this while our specifications of the respective class/method seems to hold?
What are some techniques of avoiding this problem?

**Comment by davidcok** [comment]
This means that the underlying solver returned a result of ‘unknown’ but did not produce a counterexample.
OpenJML treats a result of ‘unknown’ as a proof failure. Often a counterexample is available;’ it is not guaranteed to be a correct counterexample, but I have found that it is always so (at least almost always).

However, for some logics, for example, real arithmetic I think, some solvers do not have the capability to produce counterexamples or they make an internal decision not to do so.

There is not much OpenJML can do in this situation except wait for improvements in solvers.

To avoid this problem, I would avoid newer SMT logics, such as floating point or real arithmetic; also situations that require quantification, where feasible, probably at least recursion.

- David

**Comment by davidcok** [comment]
Fixed in V0.8.24
