### ISSUE TITLE
Dealing with "Counterexample: src is REF!val!X"

### ISSUE THREAD

**Issue by HansvdLaan** [OpenJML/OpenJML#568]
Is there any documentation available how to interpret the counterexample from the trace?

**Comment by davidcok** [comment]
The tracing does need cleaning up and fixing — it has broken a bit with other changes.

In this case though REF!val!X is the solvers way of indicating a reference. The only relevant information is whether this value is different from null or other such values.

- David

**Comment by davidcok** [comment]
Fixed in V0.8.24

**Comment by HansvdLaan** [comment]
Out of curiosity, how is this fixed?
