### ISSUE TITLE
Error running solvers with AddLoop example

### ISSUE THREAD

**Issue by ducmle** [OpenJML/OpenJML#574]
Hi,

I am attempting to install and run OpenJML to test it out for my study. 
The code example that I am using  is the AddLoop class, which is successfully demo-ed on the rise4fun web site (https://www.rise4fun.com/OpenJMLESC/).

The JML type check is ok, but the ESC check fails for all three solvers mentioned on the OpenJML download web site: CVC4 (4.1.0-4.1.5), Z3 (4.3.2), and Yices (2.5.2). For CVC4, in particular, I could not find the version 1.2 that is mentioned in download page so I have to use the latest stable versions.
I am using Windows 7, Oracle JDK 1.8, and Eclipse neon (4.6.0).

In short, the ESC check does not produce the same response as that on the rise4fun web site (i.e. the method satisfies the spec). This makes me wonder **what back-end solver is actually used to run the rise4fun example on the web site**?

The **error messages for 3 solvers** are listed below:
1/ CVC4 (with a red error message reported in the Problems view):
- In Trace view:
Error occurred while checking method: AddLoop.AddLoop()
error: An error while executing a proof script for <init>: (error "Parse Error: <shell>:1.22: Expecting at least 2 arguments for operator 'DISTINCT', found 1")

2/ Yices (with a red error message reported in the Problems view):
- In Trace view:
Error occurred while checking method: AddLoop.AddLoop()
error: An error while executing a proof script for <init>: (error "Error writing to solver: (declare-fun intValue (REF ) Int) java.io.IOException: The pipe is being closed")

3/ Z3 (withOUT any red errors being reported in Problems): 
- In Trace view:
Method and its specifications are infeasible: AddLoop.AddLoop()
- In Console view: 
C:\Users\IEUser\workspace\INT8028\src\AddLoop.java:18:  Invalid assertion (LoopInvariant)

Please advise as to what could possibly be wrong here.

Thank you very much.
Duc

**Comment by davidcok** [comment]
Please supply the example code.
Rise4fun uses the Z3 4.3 solver, but has an older version of OpenJML.

**Comment by ducmle** [comment]
Hi David, 

Please find attached the AddLoop.java class which I copied from the rise4fun web site.

Thanks,
Duc

[AddLoop.java.txt](https://github.com/OpenJML/OpenJML/files/1364303/AddLoop.java.txt)

**Comment by ducmle** [comment]
Hi David, 

While you are looking into the problem, can you please let me know the precise version of OpenJML that rise4fun is using so that I can download it and try with the AddLoop example on my machine? 
I hope that version is still available for download from GitHub.

Thanks,
Duc

**Comment by davidcok** [comment]
The current Rise4Fun version is 0.8.6-20161230. (which is very old) OpenJML on Rise4Fun is being updated imminently.
The reported issue is not a problem for V0.8.24, just now being released.

**Comment by ducmle** [comment]
Hi David, 

Thank you very much for your prompt response.

I have downloaded the new version 0.8.24 that you posted but still have errors in running it with Z3 (v4.3.0).
I focus only on on Z3 since it is the one that they are using on rise4fun.
This time, I ran openjml with the command-line tool and on both Windows and Linux Ubuntu. 
Two errors were reported in each case, though the details differ slightly (see below).

Did you test your new release with the same version of Z3 (4.3.0)?
FYI: 
**for Linux**: I downloaded it from this link (https://github.com/Z3Prover/z3/releases/tag/z3-4.3.0) and manually compiled it
**for windows**: I downloaded the binary from this link (http://z3.codeplex.com/releases/view/97572)

Btw, has the Eclipse Plugin been updated to use openjml 0.8.24?

Thank you very much for your help.

=================
ERROR REPORTS:
=================
**1/ Windows:**
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: Prover aborted with exception: null
error: An error while executing a proof script for AddLoop: (error "Error writing to solver: (assert (= (erasure (_JMLT_0 T_java_lang_Comparable)) T_java_lang_Comparable)) java.io.IOException: The pipe is being closed")
Note: openjml\openjml.jar(specs18/java/util/Random.jml) uses internal proprietary API that may be removed in a future release.
Note: Recompile with -Xlint:sunapi for details.
2 errors

**2/ Linux:**
 error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: Prover aborted with exception: null
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: Prover aborted with exception: null
Note: openjml/openjml.jar(specs18/java/util/Random.jml) uses internal proprietary API that may be removed in a future release.
Note: Recompile with -Xlint:sunapi for details.
2 errors

**Comment by davidcok** [comment]
We test regularly on Mac - we used to test on Windows. We are setting up regular testing on Linux now, but don’t currently have a Windows machine available. The only differences I have ever noted have been with interprocess communication.

The version of Z3 I’m using reports itself as 4.3.1.

However, the error you report (at least the Linux) one is s translation one and not related to solver version, at least on the surface.

Please double check the OpenJML version (java -jar openjml.jar -version)

- David

**Comment by davidcok** [comment]
We now have testing setup on as Linux machine and are showing no problems with Z3 4.3.0 on the Rise4Fun examples. Please check that you have openjml.properties configured correctly, or specify the solver directly on the command-line.

**Comment by ducmle** [comment]
Dear David, 

1/ Here is the check on my openjml version. It shows 0.8.24.
> java -jar openjml/openjml.jar -version
openjml OpenJML-0.8.24-20171007

2/ Here is the check on the z3 version I am using:
> ~/programs/solvers/z3-4.3.0/bin/z3 -version
Z3 version 4.3.0

3/ Here is the command that I use to run the AddLoop.java example. I adapted it from the OpenJmL user guide:
java -jar openjml/openjml.jar -prover z3 -exec ~/programs/solvers/z3-4.3.0/bin/z3 -esc AddLoop.java
 
4/ I am not using the openjml.properties file at the moment and specify all options via the command line (the openjml folder still contains openjml-template.properties - which I think is the template)

5/ Here is the re-run of the command on Linux with the **-trace** and **-subexpressions** options. It shows a bit more information on the run (highlighted), which I hope help identify where it went wrong ?
> java -jar openjml/openjml.jar -prover z3 -exec ~/programs/solvers/z3-4.3.0/bin/z3 **-trace -subexpressions** -esc AddLoop.java

error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: Prover aborted with exception: null
error: An error while executing a proof script for AddLoop: (**error "Error writing to solver: (declare-fun intValue (REF ) Int) java.io.IOException: Broken pipe"**)
Note: openjml/openjml.jar(specs18/java/util/Random.jml) uses internal proprietary API that may be removed in a future release.
Note: Recompile with -Xlint:sunapi for details.
2 errors

Thank you very much for your help.

Duc

**Comment by ducmle** [comment]
Dear David, 

Just curious, do I need to separately execute Z3 to get into its console before running the openjml command?
(so that it serves like a daemon to receive commands from openjml?)

Duc.

**Comment by ducmle** [comment]
Dear David, 

If I attempt to interprete the new error message ("Error writing to solver: (declare-fun intValue (REF ) Int) java.io.IOException: Broken pipe"), I would think that OpenJML is sending to Z3 the statement: (declare-fun intValue (REF ) Int). And then for some mysterious reasons this results in an IOException.

Is the statement actually correct? Why is the word "REF" located within the argument list of the function intValue? Please correct me if I am wrong, I read the Z3 tutorial examples and learnt that the function declarations only have type informations (e.g. Int) for arguments and output. There is no mentioning of the word "REF".

Is there a way of obtaining the fully translated Z3 script that OpenJML generates from the AddLoop example (without actually sending it to the solver)? Because then we could manually run it on Z3 and see if it works. This could help eliminate the potential sources of the problem.

Thanks,
Duc.

**Comment by ducmle** [comment]
...just to confirm my suspicion, X3 reported an error complaining about "REF" when I ran the statement in it:

>  ~/programs/solvers/z3-4.3.0/bin/z3 -smt2 -in
(declare-fun intValue (REF) Int)
(error "line 1 column 24: unknown sort 'REF'")

Duc.

**Comment by davidcok** [comment]
A few things to try. 
1) You do not need to separately run z3. It is spawned as a subprocess by OpenJML.
2) The main mystery is why your environment produces a different result than mine.
3) A small thing to try: use -prover z3_4_3 instead of -prover z3
4) Add the flags -show -method=zzz where zzz is the name of the method causing trouble. Capture that output and send it to me.

Thanks,

David

**Comment by ducmle** [comment]
Dear David, 

Ok, please find below the two commands and their console log files. 
Although there are still errors, I think the option "-prover z3_4_3" that you suggested certainly makes a difference. The errors are more promising now (i hope). I could also see the translated script in the detailed log.

1/ running without -show:
> java -jar openjml/openjml.jar -prover z3_4_3 -exec ~/programs/solvers/z3-4.3.0/bin/z3 -esc AddLoop.java

[AddLoop_log.txt](https://github.com/OpenJML/OpenJML/files/1367462/AddLoop_log.txt)

2/ running with -show:
> java -jar openjml/openjml.jar -prover z3_4_3 -exec ~/programs/solvers/z3-4.3.0/bin/z3 -show -method AddLoop -esc AddLoop.java

[AddLoop_with_show_log.txt](https://github.com/OpenJML/OpenJML/files/1367463/AddLoop_with_show_log.txt)

Thanks, 
David

**Comment by davidcok** [comment]
Internally, OpenJML was using a translator for the wrong version of Z3. 

The errors you see now are perfectly expected. If you don’t want to worry about overflow errors, use the option -code-math=bigint to treat all math operations in the code as if they are unbounded, or at least never overflow.
Or you can add preconditions to constrain the range of the appropriate variables.

- David

**Comment by ducmle** [comment]
Dear David, 

I added to option "-code-math=bigint" to the command as you suggested and the warnings/errors disappear.
So, just to clarify what you said, the 3 warnings that we got before adding the option are to do with type translation issue between OpenJML and Z3. And this is not an error?

Another thing i wanted to ask is about the Eclipse Plugin. Does the current plugin (posted on this site: http://jmlspecs.sourceforge.net/openjml-updatesite) work with the new OpenJML 0.8.24 that you just updated?
If not, is there a tweak that I can do to incorporate 0.8.24 into my plugin setup?

Thank you very much for your help.
Duc.

**Comment by davidcok** [comment]
The prover option states the translator to be used to represent logical statements in SMT. Although SMT-LIB is a ‘standard’ different provers have different idiosyncrasies and hence need different translations. There is not a translator for ‘z3’ - it is ‘z3_4_3’ or ‘z3_4_4’ . ‘Z3” defaults to 4.4 , which you do not have O(and does not perform as well).  The problem is not translating things wrong for 4.4, but rather the communication mechanism is slightly different than z3, resulting in some missing commands.

So it is technically a usage error, but I changed the default internally to be 4.3 in this case so users do not get tripped up as you did. Sometime I’ll get 4.5 working and perhaps that will be better than previous versions.

- David

**Comment by ducmle** [comment]
Dear David, 

Thank you very much for your kind support.

Just a side node, I've figured out a way to manually upgrade the Eclipse plugin to use your latest OpenJML release. I can now do ESC on the examples directly in the Eclipse IDE.
I wrote down the steps in the attached file. May be this would be of use for other users.

[OpenJml-Plugin-manual-upgrade.txt](https://github.com/OpenJML/OpenJML/files/1367777/OpenJml-Plugin-manual-upgrade.txt)

Duc.

**Comment by ducmle** [comment]
... and here is the openjml.properties that should be used with Z3_4_3 and this release.

[openjml.properties.txt](https://github.com/OpenJML/OpenJML/files/1367779/openjml.properties.txt)

**Comment by ducmle** [comment]
Dear David, 

I just noticed a new Eclipse plugin update and installed it. It worked fine, except for 2 new warning messages (below). It would be nice if we can turn these off. Can we do that?

`/data/programs/eclipse-openjml.neon/configuration/org.eclipse.osgi/490/0/.cp/java5/java/lang/StringBuffer.jml:272: warning: A non-pure method is being called where it is not permitted: java.lang.StringBuffer.capacity()
    //@ ensures capacity() >= minimumCapacity;
                        ^
/data/programs/eclipse-openjml.neon/configuration/org.eclipse.osgi/490/0/.cp/java5/java/lang/reflect/Method.jml:53: warning: A non-pure method is being called where it is not permitted: java.lang.reflect.Method.getModifiers()
    //+@ requires !Modifier.isStatic(getModifiers()) ==> obj != null;
`

Thanks,
Duc

**Comment by davidcok** [comment]
That is an omission that snuck past the regression tests.
You should be able to turn it off with -no-purityCheck.
Let me know if it is a problem.

- David
