### ISSUE TITLE
Bug -- Internal error, code 4

### ISSUE THREAD

**Issue by SylvioCorrea** [OpenJML/OpenJML#586]
I have no idea what it is. Was working with eclipse when it happened. Following the report recommendation and posting it here.

[bug.txt](https://github.com/OpenJML/OpenJML/files/1425626/bug.txt)

**Comment by davidcok** [comment]
Resulted from some parsing error that resulted in a bad AST that was then not handled well during type checking. But there is insufficient data to reproduce. So unfortunately I'll have to close this one without resolution.
