### ISSUE TITLE
Internal JML bug on loop example

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#587]
I got a null pointer exception on the file Loop.java in the attached zip file. This resulted in an Internal JML bug, which the tools asks to report.
[loop-example.zip](https://github.com/OpenJML/OpenJML/files/1432782/loop-example.zip)

**Comment by leavens** [comment]
Sorry, this was an installation error. (Installation is complex for openjml!)

**Comment by davidcok** [comment]
Gary - what about the process tripped you up?  Installing z3 and editing openjml.properties?

- David
