### ISSUE TITLE
assignable on loops is recognised as a refinement statement.

### ISSUE THREAD

**Issue by Jankoekenpan** [OpenJML/OpenJML#592]
Having the following method:
```
       /*@ public normal_behavior
          @ requires a != null;
          @ ensures (\forall int x; x >= 0 && x < a.length; a[x] == 0);
          @*/
	public static void zero(int[] a) {
		
		/*@
		  @ loop_invariant i >= 0 && i <= a.length
                  @ 	   && (\forall int x; x >= 0 && x < i; a[x] == 0);
	  	  @ assignable a[*];
		  @*/
		for (int i = 0; i < a.length; i++) {
			a[i] = 0;
		}

	}
```
OpenJML complains about the loop_invariant that does not directly preceed the loop `error: Loop specifications must immediately precede a while or for statement
                  @ loop_invariant i >= 0 && i <= a.length;`, but when I change the inner contract to
```
/*@
@ assignable a[*];
@ loop_invariant i >= 0 && i <= a.length
@ 	&& (\forall int x; x >= 0 && x < i; a[x] == 0);
@*/
```
then OpenJML warns me about refinement statements being ignored ` warning: Refining specifications (pre- and post-conditions on method statements) are not yet implemented and are ignored
                  @ assignable a[*];`

This is inconsistent, as in the previous situation the statement was not ignored, the loop invariant didn't preceed the for statement immediately.

The only way I managed to get this working is to put the assignable statement in the contract of the whole method.
```
       /*@ public normal_behavior
	  @ requires a != null;
	  @ assignable a[*];
	  @ ensures (\forall int x; x >= 0 && x < a.length; a[x] == 0);
	  @*/
	public static void zero(int[] a) {
		
		/*@
		  @ loop_invariant i >= 0 && i <= a.length
                  @ 	   && (\forall int x; x >= 0 && x < i; a[x] == 0);
		  @*/
		for (int i = 0; i < a.length; i++) {
			a[i] = 0;
		}

	}
```

The command I used:
```"C:\Program Files\Java\jdk1.8.0_121\bin\java.exe" -jar C:\Users\Jan\Studie\JML\Tools\openjml-0.8.24-20171007\openjml.jar -esc -exec C:\Users\Jan\Studie\JML\Tools\Z3\z3\build\z3.exe ./AssignableOnLoop.java```

**Comment by davidcok** [comment]
What you want is the loop_modifies statement.  This is in progress. At present the loop_modifies annotation is inferred — the inference works properly for a case such as your example.

- David

**Comment by davidcok** [comment]
Closing this old issue as resolved.
