### ISSUE TITLE
ESC error concerning List.remove

### ISSUE THREAD

**Issue by ducmle** [OpenJML/OpenJML#595]
Dear David,

There is an ESC error on the List.remove method concerning the validation of an assertion about the effect of this method. This happens ONLY when List.remove is invoked indirectly within another method (see file ListAPIErr.java). When List.remove is invoked directly within the main method (see the attached ListAPI.java), the problem does not occur.

The assertion simply states that the List does not contain the removed element (e). However, the prover (Z3_4_3)  throws a warning saying that it cannot establish it. 
The strange thing is that a similar assertion about the method List.add is validated with no problems at all.

I've attached to this message two test Java files for your convenience. File test/ListAPI.java contains the equivalent code in one main method. This file passes the ESC check. File test/ListAPIErr.java, however, has the ESC error:

```
examples/src/test/ListAPIErr.java:27: warning: The prover cannot establish an assertion (Assert) in method remove
    /*@ assert !col.contains(e); */
        ^
```

Thank you very much for your support.
Duc.

[ListAPI.java.txt](https://github.com/OpenJML/OpenJML/files/1565493/ListAPI.java.txt)
[ListAPIErr.java.txt](https://github.com/OpenJML/OpenJML/files/1565494/ListAPIErr.java.txt)

**Comment by davidcok** [comment]
Duc, A List may contain more than one reference to an object, so removing it does not necessarily mean that the list no longer contains that reference. 

- David

**Comment by ducmle** [comment]
Hi David, 
Thanks for your response.
Yes, i understand your explanation. However, why is the assertion still validated when I directly invoke List.remove, as shown in ListAPI.java.txt?

Duc.

**Comment by davidcok** [comment]
Duc, 

In ListAPI, the prover can see that after the call of remove, the size of the List is 0, and hence it contains nothing.

In ListAPIErr.remove however, there is no precondition on remove saying what the content of the list is on entry to the call, so one cannot assert anything about the content of the list after the remove call - except possibly that there is one less ‘e’, but that is too strong a conclusion for the current specs to find.

- David

**Comment by ducmle** [comment]
Hi David, 
Yes, i see. Thank you.
