### ISSUE TITLE
Helper method violates class invariant

### ISSUE THREAD

**Issue by Jankoekenpan** [OpenJML/OpenJML#598]
Hello,

Using extended static checking, OpenJML warns me about the violate() method not satisfying the class invariant. But since it is a helper method, violating the class invariants and constraints should be allowed.

Example code:
```
public class Helper {
	
	private /*@spec_public@*/ int i;
	
	/*@
	  @ public invariant i >= 0;
	  @*/
	
	/*@
	  @ assignable i;
	  @*/
	private /*@helper@*/ void violate() {
		i = -1;
	}
	
	//warning that violate() violates the class instance invariant
	//that is to be expected since helper method are allowed to do that.
	//the warning is useless.
	/*@
	  @ assignable this.i;
	  @ requires i < Integer.MAX_VALUE;
	  @ ensures \result == i && i == \old(i) + 1;
	  @*/
	public int incrementAndGet() {
		int j = i + 1;
		violate();
		return i = j;
	}

}
```

Warning message:
```
warning: The prover cannot establish an assertion (InvariantExceptionExit: .\helper.java:16: ) in method incrementAndGet
                violate();
                       ^
.\helper.java:16: warning: Associated declaration: .\helper.java:49:
        /*@ public invariant i >= 0; @*/
                   ^
```

Helper method/constructor semantics: [http://www.eecs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_9.html#SEC98](http://www.eecs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_9.html#SEC98)

**Comment by davidcok** [comment]
The warning is an InvariantExceptionExit. That is, it is pointing out that if violate() exits with an exception, and thus incrementAndGet ends with an exception then the invariant is not satisfied (on \exit from incrementAndGet).

If you add ‘signals (Exception e) false’ to the specification of violate(), then the warning goes away.

- David

**Comment by Jankoekenpan** [comment]
Thanks, I missed that. Instead of adding the signals clause I changed the specification of violate() to the heavyweight format and used normal_behaviour.

**Comment by davidcok** [comment]
That would work too.
