### ISSUE TITLE
Errors after upgrading from 0.8.24 to 0.8.27

### ISSUE THREAD

**Issue by ledru** [OpenJML/OpenJML#599]
I have upgraded my eclipse from 0.8.24 to 0.8.27 and I am experiencing two JML problems (the second one is an internal JML Bug)

First problem : the compiler complains about the java environment variable openjml.eclipseSpecsProjectLocation being undefined. I have this problem on several project which workd fine with the previous version.

Second problem : a JML Internal Bug. This happens on a rather simple class which is expected to 
store a Prime number. 

Here is the code of the file Prime.java , followed by the JML console messages resulting from a call to RAC.
Thanks by advance for your help!

public class Prime{
    private /*@ spec_public @*/ int p;
    /*@ public invariant
      @ (* A COMPLETER *);
      @*/

    public Prime(){
	p = 3;
    }

    //@ requires (* A COMPLETER *);
    //@ ensures (* A COMPLETER *);
    public Prime(int x){
	p = x;
    }

    //@ requires (* A COMPLETER *);
    //@ ensures (* A COMPLETER *);
    public void set_p(int x){
	p = x;
    }

    //@ ensures (* A COMPLETER *);
    public /*@ pure @*/ int get_p(){
	return p;
    }

    /*@ ensures \result == true <==>
      @   (n > 1 ) && (\forall int d; 2<= d && d<= n-1; n % d != 0);
      @*/
    public static /*@ pure helper @*/ boolean is_prime(int n){
	return true; // A MODIFIER
     }
}

[0,00] Executing openjml on Prime.java
error: The java environment variable openjml.eclipseSpecsProjectLocation used for testing must be defined.  It should contain the parent directory of the java4, java5, and java6 directories of the Specs project; you should set it as a VM argument in run Run Configuration for tests, as in -Dopenjml.eclipseSpecsProjectLocation=...
warning: Could not locate the internal specifications files - you may need to add the jmlspecs.jar explicitly on the command-line using -specspath.
warning: Could not locate the internal runtime classes - you may need to add the jmlruntime.jar explicitly on the command-line using -classpath.
RAC-Compiling Prime
Internal JML bug - please report.  BuildOpenJML-20180114
java.lang.AssertionError: The current compile state [ATTR] of class java.lang.Object is previous to FLOW
	at com.sun.tools.javac.util.Assert.error(Assert.java:133)
	at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:991)
	at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:967)
	at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:511)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
	at org.jmlspecs.openjml.JmlTree$JmlClassDecl.accept(JmlTree.java:1059)
	at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:490)
	at com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:1035)
	at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1496)
	at org.jmlspecs.openjml.JmlCompiler.desugar(JmlCompiler.java:425)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:898)
	at org.jmlspecs.openjml.JmlCompiler.compile2(JmlCompiler.java:657)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:867)
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.main.Main.compile(Main.java:410)
	at org.jmlspecs.openjml.Main.compile(Main.java:567)
	at com.sun.tools.javac.main.Main.compile(Main.java:399)
	at com.sun.tools.javac.main.Main.compile(Main.java:390)
	at org.jmlspecs.openjml.Main.executeNS(Main.java:493)
	at org.jmlspecs.openjml.API.execute(API.java:215)
	at org.jmlspecs.openjml.eclipse.OpenJMLInterface.executeExternalCommand(OpenJMLInterface.java:291)
	at org.jmlspecs.openjml.eclipse.Utils$3.run(Utils.java:564)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
ENDING with exit code 4
INTERNAL ERROR: return code = 4   Command: -command=rac -strictJML=false -purityCheck=false -show=false -racShowSource=true -racCheckAssumptions=true -racPreconditionEntry=true -racJavaChecks=false -racCompileToJavaAssert=false -verboseness=2 -checkSpecsPath -nullableByDefault=false -no-internalSpecs -specspath C:/Users/ledru/workspaces/OxygenJML/TD3-OpenJML-2018/src;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/514/0/.cp/java8;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/514/0/.cp/java7;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/514/0/.cp/java6;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/514/0/.cp/java5;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/514/0/.cp/java4 -sourcepath C:/Users/ledru/workspaces/OxygenJML/TD3-OpenJML-2018/src -no-internalRuntime -classpath C:/Program Files/Java/jre1.8.0_131/lib/resources.jar;C:/Program Files/Java/jre1.8.0_131/lib/rt.jar;C:/Program Files/Java/jre1.8.0_131/lib/jsse.jar;C:/Program Files/Java/jre1.8.0_131/lib/jce.jar;C:/Program Files/Java/jre1.8.0_131/lib/charsets.jar;C:/Program Files/Java/jre1.8.0_131/lib/jfr.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/access-bridge-64.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/cldrdata.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/dnsns.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/jaccess.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/jfxrt.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/localedata.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/nashorn.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/sunec.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/sunjce_provider.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/sunmscapi.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/sunpkcs11.jar;C:/Program Files/Java/jre1.8.0_131/lib/ext/zipfs.jar;C:/EclipseOxygenJML/plugins/org.junit_4.12.0.v201504281640/junit.jar;C:/EclipseOxygenJML/plugins/org.hamcrest.core_1.3.0.v201303031735.jar;C:/Users/ledru/workspaces/OxygenJML/TD3-OpenJML-2018/src;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/513/0/.cp/jmlruntime.jar;C:/EclipseOxygenJML/configuration/org.eclipse.osgi/513/0/.cp/jmlruntime.jar -d C:/Users/ledru/workspaces/OxygenJML/TD3-OpenJML-2018/bin C:/Users/ledru/workspaces/OxygenJML/TD3-OpenJML-2018/src/Prime.java

**Comment by davidcok** [comment]
Sorry - this is not reproducing for me. 
Are you using command-line or Eclipse?
What platform?
What other aspects of the environment - command-line parameters, openjml.properties file etc.?

- david

**Comment by davidcok** [comment]
Can reproduce the second but not the first.

**Comment by ledru** [comment]
I have seen the first bug on the computers of several of my students. These students have installed 0.8.27 but had no previous installation. So it is not specific to my machine and its history.

I repost the additional information that I have sent you directly by email (but maybe you did not receive these). 

Some additional info :
- at least one of my students experienced the same bug on his eclipse. It was his first day with OpenJML, so he has no prior configuration which could interfere with version 0.8.27
- if I navigate my eclipse history and go back to version 0.8.24, the bug disappears
- if I reinstall version 0.8.27, the bug reappears.

I am using eclipse Oxygen under Windows
It is installed in C:\EclipseOxygenJML
Could you tell me where is located the openjml.properties file? I did not find it by scanning my C: disk.
You'll find hereunder some screen copies : version of eclipse, screen copy of the bug, screen copy of my JML preferences
(I guess these are the standard options)

Thanks by advance for your help,
Yves
![image](https://user-images.githubusercontent.com/13377828/35505117-62355db4-04e5-11e8-9b13-924675426f43.png)

Here is a screen copy with the bug:

![image](https://user-images.githubusercontent.com/13377828/35505166-875cbb96-04e5-11e8-821f-71b514cf61c7.png)


and a screen copy with the JML properties


![image](https://user-images.githubusercontent.com/13377828/35505175-92822a9c-04e5-11e8-96a5-26b37ba5c961.png)

**Comment by julioapm** [comment]
I can reproduce the second error "The current compile state [ATTR] of class java.lang.Object is previous to FLOW" in command-line (version BuildOpenJML-0.8.28-20180326). Even with simple get/set classes I also found the same error.

Julio Machado

**Comment by davidcok** [comment]
Fixed in V0.8.29, though there are some configuration issues with the IDE.
