### ISSUE TITLE
openjml gives notes about java.util.Optional.jml and java.util.Random.jml

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#602]
When I run openjml version 0.8.28 on the attached files, I get notes about specifications that I don't think I'm using (Optional and Random):

$ openjml IntSet*.java
Note: C:\cygwin64\usr\local\openjml\openjml.jar(specs/java/util/Optional.jml) uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\cygwin64\usr\local\openjml\openjml.jar(specs/java/util/Random.jml) uses internal proprietary API that may be re
moved in a future release.
Note: Recompile with -Xlint:sunapi for details.

When I recompile with the recommended flags I get:

$ openjml -Xlint:sunapi -Xlint:unchecked IntSet*.java
C:\cygwin64\usr\local\openjml\openjml.jar(specs/java/util/Optional.jml):79: warning: [unchecked] unchecked call to apply
(T) as a member of the raw type Pure
  //@   ensures value != null ==> \result.value == ((java.util.function.Function.Pure)f).apply(value);
                                                                                              ^
  where T,R are type-variables:
    T extends Object declared in interface Pure
    R extends Object declared in interface Pure
C:\cygwin64\usr\local\openjml\openjml.jar(specs/java/util/Random.jml):21: warning: Unsafe is internal proprietary API an
d may be removed in a future release
  private static final sun.misc.Unsafe unsafe;
                               ^
2 warnings

[IntSet.zip](https://github.com/OpenJML/OpenJML/files/1924763/IntSet.zip)

**Comment by davidcok** [comment]
They are referenced recursively - at least you are using some part of a class some other part of which references those classes (recursively somewhere).
I agree that they are annoying but don’t be concerned about them.  This issue will remind me to clean them up someday.

**Comment by davidcok** [comment]
Fixed in V0.8.29
