### ISSUE TITLE
Use of long (integer) in assignment means obvious assertion doesn't pass ESC

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#605]
After an assignment to a long field, the field's value is not proven (by ESC) to be equal to the value assigned. The attached shows that this works for int fields but the equivalent does not work for longs. The issue may be that there is no background predicate that says that Integer.MAX_VALUE < Long.MAX_VALUE.

In any case, if lb is of type long (as in the attached), then in the following:

    //@ requires il < Integer.MAX_VALUE;
    public void use_long(long il) {
        if (!(lb <= il)) { return; }
        //@ assert lb <= il;
        lb = il+1;
        //@ assert lb == il+1;
        //@ assert lb > il;
    }

the assertion "lb == il+1" does not verify with ESC.
[LongArith.zip](https://github.com/OpenJML/OpenJML/files/1959117/LongArith.zip)

**Comment by davidcok** [comment]
Fixed in V0.8.32
