### ISSUE TITLE
No feasible path to program exit due to use of long arithmetic

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#606]
Maybe this is also due to long arithmetic (as in the previous issue), but I get the warning message:

LongArith2.java:21: warning: There is no feasible path to program point at program exit in method LongArith2.size()
    public /*@ pure @*/ long size() {
                             ^
from the attached. The only statement in the body of the method is a return statement, so it seems odd that there should be no feasible path to the exit of that method... However, if there is no long arithmetic in the return statement, then there doesn't seem to be a problem (as in the upperBound() method).
[LongArith2.zip](https://github.com/OpenJML/OpenJML/files/1959164/LongArith2.zip)

**Comment by davidcok** [comment]
Fixed for V0.8.32
