### ISSUE TITLE
spec_public not considered to create a model field for purposes of in/maps_into

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#615]
The JML Reference Manual may be somewhat unclear about this, but I had always thought that spec_public was sugar for creating a model field and a represents clause. However, in the attache zip file, it seems that OpenJML does not consider a spec_public field to be a model field for purpose of using it in "in" and "\maps_into", as I get the error message:

ReCell.java:2: error: Datagroups in "in" and "maps" clauses must be model variables
  protected /*@ spec_public @*/ int bak;  //@ in val;

even though val is declared to be spec_public.
[InAndDataGroups.zip](https://github.com/OpenJML/OpenJML/files/2046207/InAndDataGroups.zip)

**Comment by davidcok** [comment]
Replicated in gitbug615. Fixed for V0.8.33
