### ISSUE TITLE
How to ensure a map put pair successfully

### ISSUE THREAD

**Issue by ZhangDingwen** [OpenJML/OpenJML#625]
The version of OpenJML is 0.8.39-20180701. 
And here is my Java code below.

```
package temp;

import java.util.HashMap;
import java.util.Map;

public class MapPut {

    public Map<String, String> myMap = new HashMap<>();
    
    //@ ensures myMap.get("key").equals("value");
    public void put() {
        myMap.put("key", "value");
    }
}
```

I use command line tools to run openjml.

```
java -jar ./openjml.jar -esc -prover z3_4_3 -exec ./Solvers-macos/z3-4.3.1 -noPurityCheck -dir ./src/main/java/temp
```

But I can not get any result from console because it runs for a long time and seems to run forever.

So, My problem is how to  ensure the map -- myMap put pair -- <"key","value"> successfully? Thank you!

**Comment by davidcok** [comment]
Hi - Comparisons of strings are not yet well-handled in OpenJML. I suggest you try your example with integers. However, we are also in the process of improving the specs for Map objects.

**Comment by ZhangDingwen** [comment]
Thank you! I try to use byte[] to take place of String.
