### ISSUE TITLE
How to initiate an array which elements are object ?

### ISSUE THREAD

**Issue by jinjideqiangwei** [OpenJML/OpenJML#627]
I got problem when using array which elements are object. I want to initialize its elements in the contructor like what the code did below:

```
package temp;

public class MyObjectArray {

    public class Address {
        public int address;
    }

    //@ public invariant addresses.length == 100;
    public Address[] addresses = new Address[100];


    //@ ensures (\forall int i; i >= 0 && i < 100; addresses[i] != null);
    public MyObjectArray() {
        //@ maintaining i >= 0 && i <= 100;
        //@ decreasing 100 - i;
        for (int i = 0; i < 100; ++i) {
            addresses[i] = new Address();
        }

        //@ maintaining i >= 0 && i <= 100;
        //@ decreasing 100 - i;
        for (int i = 0; i < 100; ++i) {
            addresses[i].address = 99;
        }
    }
}
```
But openjml told me there were two warning:

```
./src/main/java/temp/MyList.java:24: warning: The prover cannot establish an assertion (PossiblyNullDeReference) in method MyList
            addresses[i].address = 99;
                        ^
./src/main/java/temp/MyList.java:14: warning: The prover cannot establish an assertion (Postcondition: ./src/main/java/temp/MyList.java:13: note: ) in method MyList
    public MyList() {
           ^
./src/main/java/temp/MyList.java:13: warning: Associated declaration: ./src/main/java/temp/MyList.java:14: note: 
    //@ ensures (\forall int i; i >= 0 && i < 100; addresses[i] != null);
        ^
```

I couldn't understand why the prover cannot establish postcondition -- **//@ ensures (\forall int i; i >= 0 && i < 100; addresses[i] != null);** since I had initialized the array with new Address for each element. What I really wanted was to solve the PossiblyNullDeReference warning.

**Comment by davidcok** [comment]
Note that whenever you have a loop, you need an inductive loop invariant. In this case the first loop should have

        //@ loop_invariant (\forall int j; 0<=j && j<i; addresses[j] != null);

and the second

        //@ loop_invariant (\forall int j; 0<=j && j<i; addresses[j].address == 99);

These are sufficient for your immediate question.
There are some other things that would be useful here that are in the process of being implemented. Stay tuned

**Comment by jinjideqiangwei** [comment]
Thank you! That works!
