### ISSUE TITLE
How to properly use the specification above the While loop like this?

### ISSUE THREAD

**Issue by caohui-ouba** [OpenJML/OpenJML#629]
Hello, Teacher David.
I recently encountered a problem with the While Loop. There are a lot of introductions about the specification of loops in your documentation. For example, use the `maintaining` keyword to specify the loop invariant and the `decreasing` keyword to specify the end of the loop and so on. But what should I do with the following While Loop? And how the RuntimeException should be specified using the `signals` clause？
```java
class Node {
    int data;
    Node next;
}
public class Test {
    public Node getLast(Node head) {
        if (head == null)
            return null;

        Node node = head;
        //@ ???
        while (node.next != null) {
            node = node.next;
            if (node.equals(head)) {
                throw new RuntimeException();
            }
        }
        return node;
    }
}
```
Our team is working on a project based on OpenJML tools. Recently, we have encountered a lot of troubles. There are a lot of problems that we don't understand. I hope you can give some tips. Thank you very much.                        ——  曹 辉 (CaoHui)

**Comment by davidcok** [comment]
These examples work as expected in the current version and are added to the test suite, so closing this issue.
However, opening a new issue about writing specs over data structures like linked lists.
