### ISSUE TITLE
showPromotion

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#63]
The showPromotion option has this behavior:

When source code and specifications are written (by humans), 
type promotions (e.g. int to float or class to super class) are
generally not included in the text.  Jmldoc by default will not write 
out any promotions, even those written by the user.  
This flag turns on the
generation of such text (and can result in wordy specifications).
Currently jmldoc cannot distinguish between implicit
promotions generated by the type checker and explicit promotions 
written by
the user.  The user writes:

int i;
float f;
//@ requires i == f;
//@ requires (float)i == f;
//@ requires i == (int)f;

without the --showPromotion option (i.e. off) jmldoc produces

requires this.i == this.f;
requires this.i == this.f;
requires this.i == (int)this.f;

With --showPromotion, jmldoc produces

requires (float)this.i == this.f;
requires (float)this.i == this.f;
requires this.i == (int)this.f;

We'd like to be able to distinguish implicit from explicit promotions
so that off is

requires this.i == this.f;
requires (float)this.i == this.f;
requires this.i == (int)this.f;

and on is as above.

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
