### ISSUE TITLE
Sort mismatches cause "catastropic JML internal error"

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#633]
When I run OpenJML -esc on the complex numbers example (see attached), I get sort mismatch errors which cause a  "catastropic JML internal error".
[complex-example-with-error.zip](https://github.com/OpenJML/OpenJML/files/2267591/complex-example-with-error.zip)

**Comment by davidcok** [comment]
Catastrophic error fixed; also some reasoning about reals implemented.  Still need modeling of NaN and infinities.

**Comment by davidcok** [comment]
Remaining work entered in #715. Closing this one
