### ISSUE TITLE
Exceptional outcomes of pure methods dropped

### ISSUE THREAD

**Issue by RustanLeino** [OpenJML/OpenJML#635]
A method marked as `pure` can return normally or exceptionally (see section 7.1.1.3 Pure Methods and Constructors of the JML reference manual). However, OpenJML forgets any exceptional behavior of calls to such methods. I speculate that the implementation accidentally does this when it makes various optimizations in calls to pure methods.

Repro:

    public class A {
    
        public static class MyException extends Exception { }
    
        //@ private exceptional_behavior
        //@   signals_only MyException;
        //@ pure
        private void Throw() throws MyException {
            throw new MyException();
        }
    
        //@ public normal_behavior
        //@   ensures false;
        public void caller() {
            try {
                Throw();
            } catch (MyException e) {
            }
        }
    }

OpenJML warns that there is no feasible path leading to the exit of `caller`. In particular, it does not complain about the postcondition `false` in `caller`.

  Rustan

**Comment by davidcok** [comment]
It should drop exceptional behaviors when used in a specification (because that would be ill-defined behavior), but not in Java code.

- David

**Comment by davidcok** [comment]
At one time it was thought that pure functions should not permit exceptional behavior. Certainly pure functions used in JML expressions may not throw exceptions (that is undefined, like div by 0). However, there should have at least been some type-checking checks that would warn about this. Furthermore, purity and normal behavior are likely better as orthogonal properties. So I have reversed the partial decision/implementation above and repaired the behavior for this bug.
Note that the default spec for default constructors needs to be pure and normal_behavior, if all the parent constructors are also pure and normal_behavior.  [Test case gitbug635]
