### ISSUE TITLE
specs as part of field documentation

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#64]
From Marko van Dooren (11/3/2002):
I have a class with final static
fields (prototypes of SI quantities), and I want to write 
specifications for
them. I want to do it using class invariants, but jmldoc always puts 
them
together on top of the page. Is there at this moment a way to 
make them
appear next to the field itself (as with methods) ? I could introduce 
static
methods :

/*@
@ \result == LENGTH
@ \result.getName().equals("length");
@ ......
@*/
public static Quantity LENGTH() ...

However, now the names appear between the normal methods 
which I don't want
since there will be about 20 of them (\+ the 20 fields) and thus 
would turn
the documentation of the class into a mess. So I think it would be 
very
useful to treat the combination of javadoc block + JML block + 
public
(static) field in a similar manner as methods.

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
