### ISSUE TITLE
Request: less noisy -progress switch

### ISSUE THREAD

**Issue by RustanLeino** [OpenJML/OpenJML#641]
The current `-progress` switch in OpenJML produces a status line for every method it encounters, saying if it's verifying the method or excluding the method (based on the `-method` and `-exclude` switches). For larger classes and packages, this produces a lot of output that one needs to scroll through to see any actual errors reported. On the other hand, if `-progress` is not indicated, then one cannot tell from the empty output if the indicated method verified or if the indication of which method to verify contained a typo that caused no method to be verified at all.

I am therefore wishing for a variation of the `-progress` switch that does not print progress other than the summary at the end (which says how many methods were verified, etc).

  Rustan

**Comment by davidcok** [comment]
Feature added and merged to development. The -no-skipped option trans off printing of skipped proof attempts. It is not the default because we aim for the default to be 'sound'.
