### ISSUE TITLE
non_null spec_public field of foreign class possibly null

### ISSUE THREAD

**Issue by RustanLeino** [OpenJML/OpenJML#647]
Using non-null as the default, if a class `A` declares a `spec_public` field `s`, then a constructor in another class still believes there's a possibility that `s` is `null`.

Repro:

```
//@ non_null_by_default
public class A {
    //@ spec_public
    private String s;
    
    //@ private normal_behavior
    //@   requires true;
    //@ pure
    public A() {
        s = "hello";
    }
}
```

```
//@ non_null_by_default
public class B {
    //@ public normal_behavior
    //@   requires true;
    //@ pure
    public B(A a) {
        //@ assert a.s != null;  // OpenJML reports error
    }
    
    //@ public normal_behavior
    //@   requires true;
    //@ pure
    public void testMethod(A a) {
        //@ assert a.s != null;  // fine
    }
}
```

In the code above, the assertion in `B.B` is not verified, but the same assertion in `B.testMethod` verifies. Both should verify.

If the declaration of `A.s` is changed from `spec_public` `private` to just plain `public`, then both assertions pass, as expected.

  Rustan

**Comment by davidcok** [comment]
Incorrect logic on when to presume fields are non null. When the method under analysis is a constructor we cannot presume its fields are yet non-null, but other objects of the same type should be completely initialized. Problem fixed and merged to development with a remaining problem - that issue recorded In #657
