### ISSUE TITLE
Inner private spec dropped, and incorrect empty join of specifications

### ISSUE THREAD

**Issue by RustanLeino** [OpenJML/OpenJML#648]
The following program results in a mysterious error:

```
public class B {
    //@ public normal_behavior
    //@   ensures true;
    public static void caller() {
        Inner a = new Inner();
    }
    
    public static class Inner {
        //@ private normal_behavior
        //@   ensures true;
        //@ pure
        private Inner() {
        }
    }
}
```

The specifications say that all behaviors are normal, yet the error produced is:

> B.java:7: warning: The prover cannot establish an assertion (ExceptionalPostcondition: B.java:4: ) in method caller
>         Inner a = new Inner();
>                   ^
> B.java:4: warning: Associated declaration: B.java:7: 
>     //@ public normal_behavior
>                ^
> 

Apparently, the call to "new Inner()" first prunes the behaviors specified for this constructor. In doing so, it drops the one and only behavior, because that behavior is private and the caller is not from within class `Inner`.

First off, this pruning does not follow the rules of Java, where `private` in a nested class still makes the item accessible to the enclosing class.

Moreover, after pruning away this one and only behavior, OpenJML apparently applies a default specification that allows exceptional outcomes. This is also not right, I claim. The program is giving a specification, so no defaults should be applied. Instead, the join (that is, the "`also`") of an empty set of behaviors is not the behavior that can do anything, but it is the behavior that can never be invoked. In other words, the empty join of behaviors has `requires false`. [0] So, the appropriate error to issue for callers where the pruning of the callee behaviors gets down to 0 behaviors is a precondition violation (not an exceptional-postcondition violation).

The problem of the empty join can also be provoked without an inner class (and probably also without using a constructor, but I did not try).

```
public class A {
    //@ private normal_behavior
    //@   ensures true;
    //@ pure
    public A() {
    }
}
```

```
public class B {
    //@ public normal_behavior
    //@   ensures true;
    public static void caller() {
        A a = new A();
    }
}
```

In this example, method `caller()` also gives rise to the exceptional postcondition error above.

  Rustan

[0] Rajit Manohar and K. Rustan M. Leino. Conditional Composition. Formal Asp. Comput. 7(6): 683-703 (1995)

**Comment by davidcok** [comment]
Just one initial comment without yet having looked in to this: constructors are different than non-constructors in that they do not inherit any specifications, which non-constructors may do.

- David

**Comment by RustanLeino** [comment]
I know privately that a discussion about the visibility rules has started. Let me add a comment about the other part I reported in this Issue. In particular, I'm hoping that the account below provides a convincing argument why `requires false` should be the effective specification for a call to an annotated method where all of the user-supplied behaviors have been filtered out due to visibility rules.

Here goes.

I think it's worthwhile to distinguish an _un-annotated_ method from an _annotated_ method, which JML does. For an un-annotated method, JML supplies a _default spec_, namely

    requires true; assignable \everything; ensures true; signals true;

For an annotated method, JML computes the _effective spec_ as the `also` of the given behaviors.

`also` is a symmetric and associative binary operator on behaviors. In a nutshell (ignoring `assignable` clauses and `signals` clauses, for example), it works like this:

    (requires A; ensures X;)  also  (requires B; ensures Y;)
    =
    requires A || B;  ensures (\old(A) ==> X) && (\old(B) ==> Y);

The `also` operator has a unit element, call it `Unit`.  It is:

    requires false; ensures true;

(Actually, this behavior can be shown to equal `requires false; ensures X;` for any `X`.)

As I said above, the effective spec of an annotated method is the `also` of the given behaviors. For example, if a user supplies behaviors `F`, `G`, and `H`, then the effective specification is:

    F also G also H

Since `also` is a symmetric, associative binary operator with a unit element, we can define a ("big") operator `ALSO` that applies to finite _sets_ of behaviors, in the usual way:

    ALSO {}  ==  Unit
    ALSO ({F} \union W)  ==  F also (ALSO W)

We can now say that the effective spec of a method is the `ALSO` of the set of given behaviors. For example, if a user supplies behaviors `F`, `G`, and `H`, then the effective specification is:

    ALSO {F, G, H}

It thus follows that if JML would provide a way to give an annotated method zero behaviors, the effective spec would be:

    ALSO {}

that is, `Unit`. (However, in JML, the way to turn a method into an annotated method is to supply one or more behaviors. Therefore, confusingly, we are used to saying that the effective spec of a method with zero user-supplied behaviors is the default spec.)

To make the story more complete, each behavior has a given visibility level, like private or public. The visibility levels are taken into consideration when computing the effective spec. So let me update what I said above to: The effective spec of an annotated method is `ALSO` applied to the _visible subset_ of the user-supplied behaviors. For example, if a method has user-supplied behaviors `F`, `G`, and `H`, where `F` and `H` are public and `G` is private, then for a "public" caller, the effective specification is:

    ALSO {F, H}

To an implementation, all given behaviors are visible. This means that while a caller uses the effective specification `ALSO {F, H}`, the implementation is subject to `ALSO {F, G, H}`. This is all on solid ground, because `also` is the _join_ operator (supremum, least upper bound) in the lattice of behaviors (aka known as the lattice of conjunctive predicate transformers), where the ordering relation is the refinement relation. A behavior `F` is refined by a behavior `G`, denoted `F <= G`, if every client who is happy with behavior `F` would also be happy with behavior `G`. In other words, `F <= G` says that `G` is "better" than `F`, or that `G` is "stronger" than F. In this way, the implementation of a method must be better than/stronger than/a refinement of its specification. By virtue of being a lattice, we have:

    F  <=  F join G

and, by induction, for any sets of a behaviors `V` and `W` where `V` is a subset of `W`,

    ALSO V  <=  ALSO W

This tells us that it's fine to drop behavior for the caller. For example, if the caller is happy with `ALSO {F, H}`, the caller would also be happy with `ALSO {F, G, H}`, and since the method implementation is a refinement of `ALSO {F, G, H}`, the caller would also be happy with the actual implementation of the method.

In terms of the lattice, the unit element of join is the _bottom element_ (that is, the empty join--I should have pointed this already above when I said "by induction"). In other words, the `Unit` behavior is the bottom element of the lattice of behavior (that is, `ALSO {}`). Stated differently, `Unit` is the worst of all behaviors.

Back to visibility rules. Recall from above that the effective specification of an annotated is the `ALSO` of the visible behaviors. Thus, in conclusion, if there's an annotated method where none of the given behaviors is visible to a caller, then the effective specification is `ALSO {}`, which equals `Unit`.

  Rustan

**Comment by davidcok** [comment]
Implemented to issue an error if no spec cases are visible. Leaving open as a reminder to consider a different behavior.

**Comment by davidcok** [comment]
The implementation is along the lines suggested:
- a method that does no overriding and has no spec gets a default spec
- a method that overrides and has no spec gets the ALSO of inherited specs, along with, if you like, its own Unit spec
- if a method has specs but none are visible at some call site, an error is issued

In fact I have never had a need for specs with a visibility other than that of the method itself and wish that the default visibility of a spec were the same as the method, rather than Java's package visibility.
