### ISSUE TITLE
Is there any way around a cast range error?

### ISSUE THREAD

**Issue by slyubomirsky** [OpenJML/OpenJML#649]
It appears currently that OpenJML registers a ArithmeticCastRange error if an int that may be greater than `Short.MAX_VALUE` is cast to a short. Under most circumstances, this is a reasonable error to report. However, consider the following case:

```
    ByteBuffer buf = ByteBuffer.allocate(2).putShort((short) i);
```

In this situation, a user may only want to write the two less significant bytes of the integer and may be fine with truncation or the sign flipping in the cast. Is there any way to tell OpenJML to be fine with such a cast? None of the JML math modifiers (so far as I could tell) gets it to work.

**Comment by Thiez** [comment]
I'm not affiliated with the OpenJML project, but does the error still occur when you explicitly ensure that the number being cast is in the correct range? For example:

```java
ByteBufffer buf = ByteBuffer.allocate(2).putShort((short) (i & 0xffff));
```

I would be quite surprised if a modern JVM would fail to optimize away the extra bitwise and operation.

**Comment by leavens** [comment]
Hi,

Another possibility would be to add an assume statement just before the
statement, but then the RAC might check that assumption at runtime if you
are using the RAC:

    //@ assume Short.MIN_VALUE <= i && i <= Short.MAX_VALUE;

    ByteBuffer buf = ByteBuffer.allocate.putShort((short) i);


        Regards,

        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens  phone: +1-407-823-4758
        leavens@cs.ucf.edu

**Comment by slyubomirsky** [comment]
@Thiez: The error does not occur if you have asserted that the variable is in the correct range. However, in the programs I'm studying, there are casts on ints that are intended to be truncating.

@leavens: Would you recommend that for a case where you know for a fact that the assumption will not be true? I suppose it would make the error message go away, but it would be unsound. (In the specific code I'm examining, the user is storing an unsigned 16-bit value in an int and then is casting to a short only for serialization.)

**Comment by leavens** [comment]
Hi Steven,

If you are only doing static analysis (ESC), then the assumption should be
a way to turn off the warning you are getting. You could add a comment
about it for documentation.

Alternatively, maybe it makes sense to combine both ideas and write
something like:

    //@ assume Short.MIN_VALUE <= ((short) (i & 0xffff)) && ((short) (i &
0xffff)) <= Short.MAX_VALUE;
    ByteBuffer buf = ByteBuffer.allocate.putShort((short) (i & 0xffff));

Assuming that the optimizer does away with the cast in the code that is
actually run.

        Regards,

        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens  phone: +1-407-823-4758
        leavens@cs.ucf.edu

**Comment by davidcok** [comment]
Steven, you can turn off warnings for such cast expressions for the whole
method by adding the modifier //@ code_java_math before the method
declaration. There are ways to tailor the arithmetic mode for
subexpressions of specification expressions but not (yet) for
subexpressions or even individual statements of Java code. It is on my
list, but not yet implemented.

- David

**Comment by slyubomirsky** [comment]
Thank you, @davidcok, that worked.
