### ISSUE TITLE
nonexistent files in -link and -docpath

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#65]
The -link and -docpath options list locations of html files that are 
not generated but may be linked to by the generated files.  For
that to work the designated locations must contain a
packages-list file listing all of the packages rooted at that location 
and they must contain the actual html documentation files.

When jmldoc (and javadoc) run, they will fail if the appropriate
packages-list file cannot be found, but they will run without error
even if the target documentation files are not present.  

An enhancement to jmldoc would be to generate warnings if it
generates a link to a file but that file does not actually exist.
(In the case of -linkoffline, the file is not expected to exist at
the time the documentation is generated).

A second enhancement is to not require the existence of the
package-list file.  It should be sufficient that the target 
package/file.html should be found in the list of directories or urls
provided by -docpath or the -link options.

Original comment by: davidcok

**Comment by linuxlovell** [comment]
thanks www.movied.org
