### ISSUE TITLE
nullable declaration in function definition sometimes ignored

### ISSUE THREAD

**Issue by RustanLeino** [OpenJML/OpenJML#650]
The `key` parameter to `P` in the immutable model class `Content` is ignored in the following example. Consequently, OpenJML reports various `UndefinedCalledMethodPrecondition` errors. Note, if the `axiom` is omitted, then suddenly OpenJML works as expected.

```
public interface A {
    /*@ immutable pure public static model class Content {
      @     public normal_behavior
      @       ensures true;
      @     function
      @     public boolean P(nullable Object key);
      @ }
      @
      @ axiom (\forall Content c; (\forall Object o; c.P(o)));
      @*/
    
    //@ public model instance non_null Content content;

    //@ public invariant content.P(null);
}
```

```
public final class B {
    public B(/*@ non_null */ A a) {
        this.a = a;
    }
    
    //@ non_null
    public A a;
        
    //@ public normal_behavior
    //@   ensures true;
    public void testMethod() {
    }
}
```

The output I get is:

> Proving methods in A
> Proving methods in A.Content
> Starting proof of A.Content.Content() with prover z3_4_3
> A.Content.Content Method assertions are validated
> Completed proof of A.Content.Content() with prover z3_4_3 - no warnings [0.30 secs]
> Completed proving methods in A.Content [0.41 secs]
> Completed proving methods in A [0.56 secs]
> Proving methods in B
> Starting proof of B.B((@org.jmlspecs.annotation.NonNull :: A)) with prover z3_4_3
> B.B Method assertions are INVALID
> B.java:16: warning: The prover cannot establish an assertion (UndefinedCalledMethodPrecondition: A.java:8: ) in method B
> A.java:8: warning: Associated declaration: B.java:16: 
>       @     public boolean P(nullable Object key);
>                            ^
> Completed proof of B.B((@org.jmlspecs.annotation.NonNull :: A)) with prover z3_4_3 - with warnings [1.67 secs]
> Starting proof of B.testMethod() with prover z3_4_3
> B.testMethod Method assertions are INVALID
> A.java:16: warning: The prover cannot establish an assertion (UndefinedCalledMethodPrecondition: A.java:8: ) in method testMethod
>     //@ public invariant content.P(null);
>                                   ^
> A.java:8: warning: Associated declaration: A.java:16: 
>       @     public boolean P(nullable Object key);
>                            ^
> Completed proof of B.testMethod() with prover z3_4_3 - with warnings [0.90 secs]
> Completed proving methods in B [2.88 secs]
> Note: Summary:
>     Valid:      1
>     Invalid:    2
>     Infeasible: 0
>     Timeout:    0
>     Error:      0
>     Skipped:    0
>    TOTAL:       3
>    DURATION:          4.7 secs
> 4 warnings
> 

  Rustan

**Comment by davidcok** [comment]
Test case committed. Problem reproduced.

**Comment by davidcok** [comment]
Problem fixed. This was an internal bug that manifested when a method needing axioms was called within a multiply-nested quantification.
