### ISSUE TITLE
Spurious line

### ISSUE THREAD

**Issue by pys** [OpenJML/OpenJML#652]
Hello,

After downloading OpenJML 0.8.39, I got the error message 
-------
/Applications/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/1526/0/.cp/specs/java/lang/AbstractStringBuilder.jml:7: error: The field MAX_ARRAY_SIZE is a Java field (neither ghost nor model) but does not match any fields in the corresponding Java class.
    private static final int MAX_ARRAY_SIZE;
                             ^
Operation not performed because of parse or type errors
------
This is not a bug (indeed this field is erroneous) but might confuse other users as well, since this erroneous file was added automatically.
I just commented out the offending line.

**Comment by davidcok** [comment]
The presence of this private field in the implementation depends on the version of java being used. Since the private field I not needed, the declaration is now commented out in the development branch.
