### ISSUE TITLE
Field of type C<T> marked as nullable causes unsoundness

### ISSUE THREAD

**Issue by RustanLeino** [OpenJML/OpenJML#654]
In the following example, the field `B.xyz` of type `C<String>` (a type with a type parameter) is marked as `nullable`. This introduces infeasibility in the two callers in `A`.

```
//@ nullable_by_default
public class C<T> {
}
```

```
//@ nullable_by_default
public class B {
    //@ nullable
    public C<String> xyz;

    //@ public normal_behavior
    //@   ensures true;
    public B() {
    }

    //@ public normal_behavior
    //@   ensures \result == xyz;
    public C<String> getXyz() {
        return xyz;
    }
}
```

```
//@ nullable_by_default
public final class A {
    
    //@ public normal_behavior
    //@   ensures true;
    //@ pure
    public A(B b) {  // fails feasibility check #1 (end of preconditions)
        if (false) {
            b.getXyz();
        }
    }

    //@ public normal_behavior
    //@   ensures true;
    public void TestMethod(B b) {  // fails feasibility check #1 (end of preconditions)
        if (false) {
            b.getXyz();
        }
    }
}
```

Here is OpenJML's output:

```
Proving methods in A
Starting proof of A.A(B) with prover z3_4_3
A.A Method assertions are validated
A.java:9: Feasibility check #1 - end of preconditions : infeasible
A.java:9: warning: Invariants+Preconditions appear to be contradictory in method A.A(B)
    public A(B b) {  // fails feasibility check #1 (end of preconditions)
           ^
Completed proof of A.A(B) with prover z3_4_3 - INFEASIBLE [0.49 secs]
Starting proof of A.TestMethod(B) with prover z3_4_3
A.TestMethod Method assertions are validated
A.java:17: Feasibility check #1 - end of preconditions : infeasible
A.java:17: warning: Invariants+Preconditions appear to be contradictory in method A.TestMethod(B)
    public void TestMethod(B b) {  // fails feasibility check #1 (end of preconditions)
                ^
Completed proof of A.TestMethod(B) with prover z3_4_3 - INFEASIBLE [0.16 secs]
Completed proving methods in A [0.94 secs]
Proving methods in B
Starting proof of B.B() with prover z3_4_3
B.B Method assertions are validated
B.java:10: Feasibility check #1 - end of preconditions : OK
B.java:10: Feasibility check #2 - at program exit : OK
Completed proof of B.B() with prover z3_4_3 - no warnings [1.34 secs]
Starting proof of B.getXyz() with prover z3_4_3
B.getXyz Method assertions are validated
B.java:15: Feasibility check #1 - end of preconditions : OK
B.java:15: Feasibility check #2 - at program exit : OK
Completed proof of B.getXyz() with prover z3_4_3 - no warnings [1.08 secs]
Completed proving methods in B [2.76 secs]
Proving methods in C
Starting proof of C.C() with prover z3_4_3
C.C Method assertions are validated
C.java:4: Feasibility check #1 - end of preconditions : OK
C.java:4: Feasibility check #2 - at program exit : OK
Completed proof of C.C() with prover z3_4_3 - no warnings [0.88 secs]
Completed proving methods in C [1.00 secs]
Note: Summary:
    Valid:      3
    Invalid:    0
    Infeasible: 2
    Timeout:    0
    Error:      0
    Skipped:    0
   TOTAL:       5
   DURATION:          6.4 secs
2 warnings
```

Notes:

* In the example above, the three classes are marked `nullable_by_default`. Changing all three of them to `non_null_by_default` (and adding `nullable` as a modifier to `B.getXyz()`), the unsoundness issue is the same. So, the problem appears to be related to the `nullable` attribute on the field `B.xyz`, not the default setting.

* If I remove the `nullable` modifier on the field `B.xyz` (with either default for nullity, see previous bullet), then everything works fine.

* To provoke the unsoundness, it is important that the type of `B.xyz` is a class with a type parameter, here `C<String>`. If I remove the formal type parameter to class `C` and change the type of field `B.xyz` to just `C` (or to `String`, for that matter), then the problem does not appear.

* Curiously, the feasibility reported is on entry to `A.A` and `A.TestMethod`. Indeed, adding an `assert false` just inside these methods yields no further errors. Yet, note that the `if` statements cause `b.getXyz()` never to be reached. The curious thing is that commenting out the calls to `b.getXyz()` causes the infeasibility complaints to go away. In other words, the mere textual presence of a call to `getXyz()` in `A`'s methods is what causes an infeasibility error _on entry_ to those methods.

  Rustan

**Comment by davidcok** [comment]
The problem was that nullable and non_null types were being hashed as different but SMT saw them as the same, hence a contradiction in the preamble. This bug would have been introduced with Java 8.
Fixed, being tested and merged with development.
