### ISSUE TITLE
Do-while loops with specs pretty-print incorrectly

### ISSUE THREAD

**Issue by Thiez** [OpenJML/OpenJML#656]
The `JmlPretty` class has the following code for pretty-printing do-while loops (line 829):

```java
public void visitJmlDoWhileLoop(JmlDoWhileLoop that) {
    if (that.loopSpecs != null) for (JmlStatementLoop s: that.loopSpecs) {
        s.accept(this);
    }
    super.visitDoLoop(that);
}
```

This code does not emit a newline after each spec, so code such as:

```java
//@ loop_invariant true;
do {
 // nothing
} while false;
```

will pretty-print as:

```java
//@ loop_invariant true;do {
// nothing
} while false;
```

It seems that adding a simple `println(); align();` inside the for-loop will fix this problem (which is also how pretty-printing is implemented for the other loop-types).

If necessary I can produce a small example that triggers this bug, but I think the problem is pretty obvious just from the code.

**Comment by Thiez** [comment]
Here is an example that reproduces the problem. Running the code code below will produce the line `    //@ loop_invariant true;do {`.

```java
import org.jmlspecs.openjml.*;

public class Example {
    public static void main(String[] args) throws Exception {
        //@ loop_invariant true;
        do {
            IAPI api = Factory.makeAPI("-jml", "-strictJML");
            System.out.println(api.parseSingleFile("./Example.java").toString());
        } while (false);
    }
}
```

**Comment by davidcok** [comment]
Fixed in development branch
