### ISSUE TITLE
Recursive specs and methods

### ISSUE THREAD

**Issue by davidcok** [OpenJML/OpenJML#659]
Specs with recursive methods - see corresponding test case

**Comment by mhermo** [comment]
I am trying OpenJML in https://rise4fun.com/OpenJMLESC.  It works very well with iterative programs but I am not being able to verify recursive programs.  For instance, this one. 
I would appreciate any help!!

     //@ requires x >= 0;
    //@ ensures \result == 2*x;
    public static int sum(int x){
      int r;
      if (x==0) r = 0;
      else {
        r = sum(x-1);
        //@ assert r == 2*(x-1);
        r = r + 2;
      } 
      return r;    
    }

**Comment by davidcok** [comment]
Sorry for overdue response:
Problems with recursive calls were fixed (or at least improved) quite a while ago.
Running this problem now results in just a possible overflow error, since if x is large enough 2*x will overflow.
That can be fixed with a precondition of requires 0 <= x < Integer.MAX_VALUE/2;

Another suggestion is to declare the method 'pure'. It is not actually necessary here because the method does not use any global variables, but is nonetheless good practice to include either pure or assigns ...
