### ISSUE TITLE
Iterator and Enumeration shouldn't have pure methods

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#66]
The interfaces java.util.Iterator and
java.util.Enumeration are currently specified as having
pure methods hasNext() and hasNextElement()
(respectively).  These are too restrictive, since they
apply to all concievable implementations of these
interfaces, as Joe Kiniry pointed out.  We should
instead have pure model methods that shadow these
methods that could be used in specifications. 
Unfortunately the tools are not currently able to
handle such model methods, I think, but when they are
we should do that.

See also RFE 685969 about Object's equals method.

Original comment by: leavens

**Comment by linuxlovell** [comment]
thanks www.movied.org
