### ISSUE TITLE
Replace Eclipse annotations with FindBugs

### ISSUE THREAD

**Issue by postmasters** [OpenJML/OpenJML#668]
FindBugs does have Nullable and NonNull annotations that are supported by the Eclipse IDE. What do you say about replacing Eclipse annotations in code with them?

**Comment by davidcok** [comment]
We are going toward the Checker framework and the Java/Eaclipse annotations, not the FindBugs package, though I intend that OpenJML can recognize the FindBugs ones.

- David

**Comment by postmasters** [comment]
I saw some comment to remove dependency on Eclipse JDT and OSGi, as well as the existence of `findbugs-17-annotations.jar` in `otherlibs` directory and presumed that the first easy step forward was to move the annotations from Eclipse over to FindBugs. Thanks for the clarification.
