### ISSUE TITLE
OpenJML generates invalid SMTLIB distinct operator

### ISSUE THREAD

**Issue by postmasters** [OpenJML/OpenJML#669]
I am on master branch. The generated SAT proof is something like this.

```
(set-option :print-success true)
(set-option :produce-models true)
(declare-sort REF 0)
(declare-fun NULL () REF)
(declare-fun THIS () REF)
(declare-fun stringConcat (REF REF ) REF)
(declare-fun stringLength (REF ) Int)
(assert (distinct NULL))
```

The last line provides only one argument to `distinct`.

**Comment by davidcok** [comment]
What is the input Java?

**Comment by postmasters** [comment]
Same as in my previous bug.

```
public final class A {
  //@ requires a >= 0 && a <= 10;
  //@ ensures \result == a + 1;
  public int add(int a) {
    return a + 1;
  }

  public static void main(String[] args) {
    System.out.println(new A().add(10));
  }
}
```

**Comment by davidcok** [comment]
What version and what platform?  I see the offending expression in the SMT output, but Z3 on Mac does not complain about it.

- David

**Comment by postmasters** [comment]
Master. Linux. Cvc4.
And yes, Z3 does not complain.
Nam

**Comment by davidcok** [comment]
This was fixed some time ago. Test case is in the test suite. Closing the issue.
