### ISSUE TITLE
Specification of java.util.Scanner is wrong

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [OpenJML/OpenJML#670]
When I use the OpenJML esc checker on anything that uses java.utili.Scanner I get
[scanTest.zip](https://github.com/OpenJML/OpenJML/files/2774427/scanTest.zip)

 several warning messages. For example on the attached program I get the following output. 

scanTest.java:7: warning: The prover cannot establish an assertion (InvariantEntrance: /home/amirfarhad/Desktop/cmu/openjml/newOpenJML/openjml.jar(specs/java/io/InputStream.jml):56: ) in method main:  (Caller: scanTest.main(java.lang.String[]), Callee: java.util.Scanner.Scanner(java.io.InputStream))
        Scanner in = new Scanner(System.in);
                                 ^
/home/amirfarhad/Desktop/cmu/openjml/newOpenJML/openjml.jar(specs/java/io/InputStream.jml):56: warning: Associated declaration: scanTest.java:7: 
    //-RAC@ public invariant readPosition+availableBytes <= inputBytes.length;
                   ^
scanTest.java:7: warning: The prover cannot establish an assertion (InvariantEntrance: /home/amirfarhad/Desktop/cmu/openjml/newOpenJML/openjml.jar(specs/java/io/InputStream.jml):55: ) in method main:  (Caller: scanTest.main(java.lang.String[]), Callee: java.util.Scanner.Scanner(java.io.InputStream))
        Scanner in = new Scanner(System.in);
                                 ^
/home/amirfarhad/Desktop/cmu/openjml/newOpenJML/openjml.jar(specs/java/io/InputStream.jml):55: warning: Associated declaration: scanTest.java:7: 
    //-RAC@ public invariant readPosition >= 0;
                   ^
scanTest.java:7: warning: The prover cannot establish an assertion (InvariantEntrance: /home/amirfarhad/Desktop/cmu/openjml/newOpenJML/openjml.jar(specs/java/io/InputStream.jml):54: ) in method main:  (Caller: scanTest.main(java.lang.String[]), Callee: java.util.Scanner.Scanner(java.io.InputStream))
        Scanner in = new Scanner(System.in);
                                 ^
/home/amirfarhad/Desktop/cmu/openjml/newOpenJML/openjml.jar(specs/java/io/InputStream.jml):54: warning: Associated declaration: scanTest.java:7: 
    //-RAC@ public invariant availableBytes >= 0;
                   ^
scanTest.java:7: warning: The prover cannot establish an assertion (InvariantEntrance: /home/amirfarhad/Desktop/cmu/openjml/newOpenJML/openjml.jar(specs/java/io/InputStream.jml):42: ) in method main:  (Caller: scanTest.main(java.lang.String[]), Callee: java.util.Scanner.Scanner(java.io.InputStream))
        Scanner in = new Scanner(System.in);
                                 ^
/home/amirfarhad/Desktop/cmu/openjml/newOpenJML/openjml.jar(specs/java/io/InputStream.jml):42: warning: Associated declaration: scanTest.java:7: 
    //-RAC@ public invariant inputBytes.owner == this;
                   ^
8 warnings

**Comment by davidcok** [comment]
Amirfarhad - you are correct that no specs have been written fro java.util.Scanner as yet. I’kkl get to this issue, but if you want to develop some draft specs, the issue may be resolved sooner…

- David

**Comment by davidcok** [comment]
Will be fixed in the upcoming release
