### ISSUE TITLE
cannot find symbol error in specs/java/ in the openJML.jar

### ISSUE THREAD

**Issue by Katie2018** [OpenJML/OpenJML#671]
When I use the OpenJML esc checker on the class org.apache.commons.collections4.set.ListOrderedSet
[ListOrderedSet.zip](https://github.com/OpenJML/OpenJML/files/2810140/ListOrderedSet.zip), I got the following error. 
When I use the OpenJML esc checker on the class javax.management.relation.RoleUnresolvedList in JDK, I also got the error. 
I wonder whether I can specify a parameter to let OpenJML ignore the specs in the jar file.
./openjml.jar(specs/java/util/BitSet.jml):15: error: cannot find symbol
      @ public non_null model Content content;
                              ^
  symbol:   class Content
  location: class BitSet
./openjml.jar(specs/java/util/BitSet.jml):19: error: cannot find symbol
      @ public function static pure model int size(Content content);
                                                   ^
  symbol:   class Content
  location: class BitSet
./openjml.jar(specs/java/util/BitSet.jml):23: error: cannot find symbol
      @ public function static pure model int cardinality(Content content);
                                                          ^
  symbol:   class Content
  location: class BitSet
./openjml.jar(specs/java/util/BitSet.jml):25: error: cannot find symbol
      @ public function static pure model boolean isSet(Content c, int index);
                                                        ^
  symbol:   class Content
  location: class BitSet
./org/apache/commons/collections4/set/ListOrderedSet.java:338: error: cannot find symbol
			@ ensures this.theSet.equals(\old(this.theSet.insert(object)));
			                                      ^
  symbol: variable theSet
./org/apache/commons/collections4/set/ListOrderedSet.java:338: error: cannot find symbol
			@ ensures this.theSet.equals(\old(this.theSet.insert(object)));
			              ^
  symbol: variable theSet
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors

**Comment by davidcok** [comment]
Katie - please send me a zip of the apache commons source files you are using, so I am sure to debug against the same versions are you are using.

- David

**Comment by Katie2018** [comment]
Hello David,


Please find the attached source files. Thank you!

Sincerely,
Katie

David Cok <notifications@github.com>于2019年2月8日周五 下午3:37写道：

**Comment by davidcok** [comment]
Katie - the zip of the library of classes that your problem is referencing (by import) seems to have dropped from your email. Perhaps send it to me directly.
Or, if you are linking directly against the binary library, let me know that and be specific about the version (or send it to me).

- David

**Comment by davidcok** [comment]
Resolved in release 41 with corrections to Specs.
