### ISSUE TITLE
esc seems to be stuck and does not stop

### ISSUE THREAD

**Issue by Katie2018** [OpenJML/OpenJML#672]
When I use the OpenJML esc checker on the class org.apache.commons.collections4.bidimap.TreeBidiMap
[TreeBidiMap.zip](https://github.com/OpenJML/OpenJML/files/2810158/TreeBidiMap.zip)
, it seems to be stuck at some place and it just does not stop:

./org/apache/commons/collections4/bidimap/TreeBidiMap.java:106: warning: The prover cannot establish an assertion (NullField) in method TreeBidiMap
    private transient Set<K> keySet;
                             ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:116: warning: The prover cannot establish an assertion (InvariantExit: ./openjml.jar(specs/java/util/Map.jml):80: ) in method TreeBidiMap
    public TreeBidiMap() {
           ^
./openjml.jar(specs/java/util/Map.jml):80: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:116: 
    //-RAC@ public invariant content.owner == this;
                   ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:129: warning: The prover cannot establish an assertion (InvariantLeaveCaller: ./openjml.jar(specs/java/util/Map.jml):80: ) in method TreeBidiMap:  (Parameter: map, Caller: org.apache.commons.collections4.bidimap.TreeBidiMap.TreeBidiMap(java.util.Map<? extends K,? extends V>), Callee: org.apache.commons.collections4.bidimap.TreeBidiMap.putAll(java.util.Map<? extends K,? extends V>))
    public TreeBidiMap(final Map<? extends K, ? extends V> map) {
                                                           ^
./openjml.jar(specs/java/util/Map.jml):80: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:129: 
    //-RAC@ public invariant content.owner == this;
                   ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:129: warning: The prover cannot establish an assertion (InvariantExceptionExit: ./openjml.jar(specs/java/util/Map.jml):80: ) in method TreeBidiMap:  org.apache.commons.collections4.bidimap.TreeBidiMap.TreeBidiMap(java.util.Map<? extends K,? extends V>) (parameter map)
    public TreeBidiMap(final Map<? extends K, ? extends V> map) {
                                                           ^
./openjml.jar(specs/java/util/Map.jml):80: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:129: 
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):70: warning: The prover cannot establish an assertion (Invariant) in method TreeBidiMap
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):71: warning: The prover cannot establish an assertion (Invariant) in method TreeBidiMap
    //-RAC@ public invariant content.theSize >= 0;
                   ^
./openjml.jar(specs/java/util/Collection.jml):70: warning: The prover cannot establish an assertion (Invariant) in method TreeBidiMap
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):71: warning: The prover cannot establish an assertion (Invariant) in method TreeBidiMap
    //-RAC@ public invariant content.theSize >= 0;
                   ^
./openjml.jar(specs/java/util/Map.jml):80: warning: The prover cannot establish an assertion (Invariant) in method TreeBidiMap
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):70: warning: The prover cannot establish an assertion (Invariant) in method TreeBidiMap
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):71: warning: The prover cannot establish an assertion (Invariant) in method TreeBidiMap
    //-RAC@ public invariant content.theSize >= 0;
                   ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:281: warning: The prover cannot establish an assertion (PossiblyNegativeIndex) in method clear
        rootNode[KEY.ordinal()] = null;
                ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:282: warning: The prover cannot establish an assertion (PossiblyNegativeIndex) in method clear
        rootNode[VALUE.ordinal()] = null;
                ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:278: warning: The prover cannot establish an assertion (ExceptionalPostcondition: ./openjml.jar(specs/java/util/Map.jml):302: ) in method clear
        modify();
              ^
./openjml.jar(specs/java/util/Map.jml):302: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:278: 
    /*-RAC@ public normal_behavior
                   ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:281: warning: The prover cannot establish an assertion (PossiblyTooLargeIndex) in method clear
        rootNode[KEY.ordinal()] = null;
                ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:282: warning: The prover cannot establish an assertion (PossiblyTooLargeIndex) in method clear
        rootNode[VALUE.ordinal()] = null;
                ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:277: warning: The prover cannot establish an assertion (Postcondition: ./openjml.jar(specs/java/util/Map.jml):305: ) in method clear
    public void clear() {
                ^
./openjml.jar(specs/java/util/Map.jml):305: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:277: 
      @    ensures (\forall Object k; !content.hasMapObject(k));
           ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:277: warning: The prover cannot establish an assertion (Postcondition: ./openjml.jar(specs/java/util/Map.jml):304: ) in method clear
    public void clear() {
                ^
./openjml.jar(specs/java/util/Map.jml):304: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:277: 
      @    ensures isEmpty();
           ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:171: warning: The prover cannot establish an assertion (Assignable: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:170: ) in method containsKey:  \everything
        checkKey(key);
                ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:170: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:171: 
	public boolean containsKey(final Object key) {
	               ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:172: warning: The prover cannot establish an assertion (Assignable: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:170: ) in method containsKey:  \everything
        return lookupKey(key) != null;
                        ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:170: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:172: 
	public boolean containsKey(final Object key) {
	               ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:172: warning: The prover cannot establish an assertion (Postcondition: ./openjml.jar(specs/java/util/Map.jml):166: ) in method containsKey
        return lookupKey(key) != null;
        ^
./openjml.jar(specs/java/util/Map.jml):166: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:172: 
      @    ensures content.hasMap(key) <==> \result;
           ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:172: warning: The prover cannot establish an assertion (Postcondition: ./openjml.jar(specs/java/util/Map.jml):165: ) in method containsKey
        return lookupKey(key) != null;
        ^
./openjml.jar(specs/java/util/Map.jml):165: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:172: 
      @    ensures isEmpty() ==> !\result;
           ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:171: warning: The prover cannot establish an assertion (ExceptionalPostcondition: ./openjml.jar(specs/java/util/Map.jml):171: ) in method containsKey
        checkKey(key);
                ^
./openjml.jar(specs/java/util/Map.jml):171: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:171: 
      @    signals (NullPointerException) key == null
           ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:171: warning: The prover cannot establish an assertion (ExceptionList: ./openjml.jar(specs/java/util/Map.jml):168: ) in method containsKey
        checkKey(key);
                ^
./openjml.jar(specs/java/util/Map.jml):168: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:171: 
      @    signals_only ClassCastException, NullPointerException;
           ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:188: warning: The prover cannot establish an assertion (Assignable: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:187: ) in method containsValue:  \everything
        checkValue(value);
                  ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:187: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:188: 
    /*@ pure @*/ public boolean containsValue(final Object value) {
                                ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:189: warning: The prover cannot establish an assertion (Assignable: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:187: ) in method containsValue:  \everything
        return lookupValue(value) != null;
                          ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:187: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:189: 
    /*@ pure @*/ public boolean containsValue(final Object value) {
                                ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:189: warning: The prover cannot establish an assertion (Postcondition: ./openjml.jar(specs/java/util/Map.jml):177: ) in method containsValue
        return lookupValue(value) != null;
        ^
./openjml.jar(specs/java/util/Map.jml):177: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:189: 
      @    ensures isEmpty() ==> !\result;
           ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:189: warning: The prover cannot establish an assertion (ExceptionalPostcondition: ./openjml.jar(specs/java/util/Map.jml):185: ) in method containsValue
        return lookupValue(value) != null;
                          ^
./openjml.jar(specs/java/util/Map.jml):185: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:189: 
      @    signals (NullPointerException) value == null
           ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:189: warning: The prover cannot establish an assertion (ExceptionList: ./openjml.jar(specs/java/util/Map.jml):182: ) in method containsValue
        return lookupValue(value) != null;
                          ^
./openjml.jar(specs/java/util/Map.jml):182: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:189: 
      @    signals_only ClassCastException, NullPointerException;
           ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:189: warning: The prover cannot establish an assertion (Postcondition: ./openjml.jar(specs/java/util/Map.jml):178: ) in method containsValue
        return lookupValue(value) != null;
        ^
./openjml.jar(specs/java/util/Map.jml):178: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:189: 
      @    ensures !\key("RAC") ==> \result <==> (
           ^
./openjml.jar(specs/java/util/Collection.jml):70: warning: The prover cannot establish an assertion (Invariant) in method copyColor
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):70: warning: The prover cannot establish an assertion (Invariant) in method copyColor
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Map.jml):80: warning: The prover cannot establish an assertion (Invariant) in method copyColor
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):71: warning: The prover cannot establish an assertion (Invariant) in method copyColor
    //-RAC@ public invariant content.theSize >= 0;
                   ^
./openjml.jar(specs/java/util/Collection.jml):71: warning: The prover cannot establish an assertion (Invariant) in method copyColor
    //-RAC@ public invariant content.theSize >= 0;
                   ^
./openjml.jar(specs/java/util/Collection.jml):70: warning: The prover cannot establish an assertion (Invariant) in method copyColor
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):71: warning: The prover cannot establish an assertion (Invariant) in method copyColor
    //-RAC@ public invariant content.theSize >= 0;
                   ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:97: warning: The prover cannot establish an assertion (Postcondition: ./openjml.jar(specs/java/lang/Enum.jml):22: ) in method toString
            return description;
            ^
./openjml.jar(specs/java/lang/Enum.jml):22: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:97: 
      //@   ensures \result == name;
            ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:1358: warning: The prover cannot establish an assertion (InvariantLeaveCaller: ./openjml.jar(specs/java/util/Map.jml):80: ) in method doEquals:  (Caller: org.apache.commons.collections4.bidimap.TreeBidiMap.doEquals(java.lang.Object,org.apache.commons.collections4.bidimap.TreeBidiMap.DataElement), Callee: java.util.Map.size())
        if (other.size() != size()) {
                      ^
./openjml.jar(specs/java/util/Map.jml):80: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:1358: 
    //-RAC@ public invariant content.owner == this;
                   ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:1367: warning: The prover cannot establish an assertion (InvariantEntrance: ./openjml.jar(specs/java/util/Map.jml):80: ) in method doEquals:  (Caller: org.apache.commons.collections4.bidimap.TreeBidiMap.doEquals(java.lang.Object,org.apache.commons.collections4.bidimap.TreeBidiMap.DataElement), Callee: java.util.Map.get(java.lang.Object))
                    if (value.equals(other.get(key)) == false) {
                                              ^
./openjml.jar(specs/java/util/Map.jml):80: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:1367: 
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Map.jml):191: warning: The prover cannot establish an assertion (UndefinedCalledMethodPrecondition: ./openjml.jar(specs/java/util/Map.jml):60: ) in method doEquals
      @    requires !content.hasMap(key);// hasMap or hasMapObject -- FIXME
                                   ^
./openjml.jar(specs/java/util/Map.jml):60: warning: Associated declaration: ./openjml.jar(specs/java/util/Map.jml):191: 
          public boolean hasMap(nullable Object key);
                         ^
./openjml.jar(specs/java/util/Collection.jml):70: warning: The prover cannot establish an assertion (Invariant) in method doEquals
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Map.jml):80: warning: The prover cannot establish an assertion (Invariant) in method doEquals
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):71: warning: The prover cannot establish an assertion (Invariant) in method doEquals
    //-RAC@ public invariant content.theSize >= 0;
                   ^
./openjml.jar(specs/java/util/Collection.jml):70: warning: The prover cannot establish an assertion (Invariant) in method doEquals
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):71: warning: The prover cannot establish an assertion (Invariant) in method doEquals
    //-RAC@ public invariant content.theSize >= 0;
                   ^
./openjml.jar(specs/java/util/Collection.jml):70: warning: The prover cannot establish an assertion (Invariant) in method doEquals
    //-RAC@ public invariant content.owner == this;
                   ^
./openjml.jar(specs/java/util/Collection.jml):71: warning: The prover cannot establish an assertion (Invariant) in method doEquals
    //-RAC@ public invariant content.theSize >= 0;
                   ^
error: An error while executing a proof script for doHashCode: (error "line 3414 column 129: invalid function application, sort mismatch on argument at position 2")
  >>>(assert (= _JML__tmp18968 (forall ((o REF) ) (or (not (= (select theSize_1299_0___10 (select content_2884_0___8 THIS)) #x00000000)) (not (java_util_Map_Content_hasMapObject_1779 (select content_2884_0___8 THIS) o))))))
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:517: warning: The prover cannot establish an assertion (PossiblyNegativeIndex) in method doPut
        Node<K, V> node = rootNode[KEY.ordinal()];
                                  ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:517: warning: The prover cannot establish an assertion (PossiblyTooLargeIndex) in method doPut
        Node<K, V> node = rootNode[KEY.ordinal()];
                                  ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:517: warning: The prover cannot establish an assertion (PossiblyNullInitialization) in method doPut:  node
        Node<K, V> node = rootNode[KEY.ordinal()];
                   ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:998: warning: The prover cannot establish an assertion (Precondition: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:1908: ) in method doRedBlackDelete
                deletedNode.setLeft(null, dataElement);
                                   ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:1908: warning: Associated declaration: ./org/apache/commons/collections4/bidimap/TreeBidiMap.java:998: 
        private void setLeft(final Node<K, V> node, final DataElement dataElement) {
                     ^
./org/apache/commons/collections4/bidimap/TreeBidiMap.java:1908: warning: Precondition conjunct is false: node != null
        private void setLeft(final Node<K, V> node, final DataElement dataElement) {
                                              ^

**Comment by davidcok** [comment]
With the current release, this seems to run fine, although it times out because there are very many methods to verify. In particular doEquals does keep running util it times out. I suggest using the options -timeout=600 (or however many seconds you want) and -escMaxWarning=1 to keep OpenJML from looking for new warnings down other execution paths after it finds the first warning. (The default is to keep looking until no more warnings can be found.)
