### ISSUE TITLE
Internal error for dealing floating point numbers

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [OpenJML/OpenJML#673]
When I run OpenJml as shown below on the attached file, I get an internal errors.
I am using Ubuntu.

$ java -jar /home/amirfarhad/Desktop/cmu/openjml/newOpenJML/openjml.jar -esc FahrenheitToCelsius.java 
error: An error while executing a proof script for main: (error "line 1525 column 144: unknown constant _JML__tmp2401")
  >>>(define-fun BL_548_afterIf_106__A1 () Bool (= _JML__tmp2402 (org_jmlspecs_models_JMLFloat_approximatelyEqualTo_H7_0 _JML__tmp2388 _JML__tmp2399 _JML__tmp2401)))
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: Exception while translating block: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Double
[FahrenheitToCelsius.zip](https://github.com/OpenJML/OpenJML/files/2823036/FahrenheitToCelsius.zip)

**Comment by davidcok** [comment]
Yes - floating point is not fully implemented as yet, nor are the models files. Thanks for the example.
I’ll get to it.

**Comment by davidcok** [comment]
Floating point still needs a fair bit of implementation, but the crash is fixed
