### ISSUE TITLE
Non persisting racPreconditionEntry and racCheckAssumptions

### ISSUE THREAD

**Issue by ledru** [OpenJML/OpenJML#674]
In eclipse, when I open Window>Preferences>OpenJML, I can check options "Check assumptions (as well as assertions) and "Distinguish entry from internal Precondition errors". I then click "Apply and Close".

![image](https://user-images.githubusercontent.com/13377828/52273888-6973e600-294b-11e9-84c9-c0c74196cfab.png)

At this time the options are working correctly. But when I reopen the preference window, these options
appear as unchecked, and when I close the window (without re-checking the options), the options are no longer working.

![image](https://user-images.githubusercontent.com/13377828/52273835-4a755400-294b-11e9-89ae-17509b561341.png)

I am working under windows 10, with eclipse Photon (4.8.0)  and OpenJML 0.8.40

**Comment by davidcok** [comment]
Fixed the problem with options not being retained. Will be in next release.
