### ISSUE TITLE
JML not checking the return type of main properly

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [OpenJML/OpenJML#676]
The type of main in java should be void. But, JML does not show any error when the type is declared as int. For example the attached file does not show any error.
[Main.zip](https://github.com/OpenJML/OpenJML/files/2846560/Main.zip)

**Comment by dmzimmerman** [comment]
There is no restriction on the return type of a method called `main` in Java. The method in this file, `public static int main()`, is a perfectly legal method to declare - but it does not function as an entry point for running the class, because such an entry point must have the signature `void main(String[])`.

**Comment by Amirfarhad-Nilizadeh** [comment]
Thanks for your answer Daniel. I checked the Java Specification by oracle and it is mentioned that "The method main must be declared public, static, and void." [1] I am not still  sure what is right, but it seems it should be a type-checking error for main. 
In Eclipse, both "static int main(String[] the_args)" and "void main(String[])" will get the following error, while OpenJML accept them.

Error: Main method must return a value of type void in class Main, please 
define the main method as:
   public static void main(String[] args)

[1] https://docs.oracle.com/javase/specs/jls/se7/html/jls-12.html#jls-12.1.4

**Comment by leavens** [comment]
Hi Amirfarhad and all,

It does seem like OpenJML could give a warning if a method is named "main"
and doesn't have return type void. This would just say that the method in
question won't be the program's entry point.

        Regards,

        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens  phone: +1-407-823-4758
        leavens@cs.ucf.edu

**Comment by davidcok** [comment]
In this respect OpenJML just has the behavior that OpenJDK itself has.

- David

**Comment by jsinglet** [comment]
The JLS specifies that the main method should be typed static void main, but places no restrictions on methods called main of other types if they are not the entry point. For example, it is perfectly valid to compile an empty class. OpenJDK and Oracle JDK allow you to create a static method called main with any return type, however, the resulting bytecode will not run as a standalone program. 

In Oracle JDK (and probably OpenJDK), the following does not produce a compile time error: 

```java
public class Test {
    public static int main(String args[]){ return 0;}
}
```

However, if you run the compiled class, you get:

```
Error: Main method must return a value of type void in class Test, please
define the main method as:
   public static void main(String[] args)
```

**Comment by davidcok** [comment]
A similar issue is that methods can be named the same as a constructor

class A

A() {} // a constructor

void A() {} // a legitimate method

}

These are confusing but java compilers do not typically warn about this naming.

Closing the issue without action.
