### ISSUE TITLE
V0.8.41 infinite-loop in double type

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [OpenJML/OpenJML#678]
The static checker was accepting the following code in V0.8.40, but in V0.8.41 it goes to infinite-loop. 

When the input is negative in run time assertion checking of V0.8.40, the code have warnings. 

[DoubleABS.zip](https://github.com/OpenJML/OpenJML/files/3005847/DoubleABS.zip)

**Comment by davidcok** [comment]
I will investigate. Note though that while I aim to avoid crashes and infinite loops, the logic encoding of floats/doubles is far from complete or even accurate. I would avoid attempting proofs of real properties for the moment.

- David

**Comment by davidcok** [comment]
You needed to check for NaN, like this:

public class DoubleABS{  
    //@ requires !num.isNaN() && num >= 0;
    //@ ensures \result == num;
    //@ ensures \result >= 0;

    //@ also

    //@ requires !num.isNaN() && num < 0;
    //@ ensures \result == -num; 
    //@ ensures \result >= 0;
    public /*@ pure @*/ Double DoubleAbsolute(Double num){
        if (num >= 0)
            return num;
        else
            return -num;
    } 
}

Added this as a test case.
