### ISSUE TITLE
Eclipse plugin for Eclipse Photon gives "Failure finding internal specs: java.net.URISyntaxException: Illegal character in path at index 16:"

### ISSUE THREAD

**Issue by devuniv** [OpenJML/OpenJML#680]
Also see [StackOverflow post](https://stackoverflow.com/questions/55649476/failure-finding-internal-specs-error-with-openjml-plugin-in-eclipse): 

Given _Eclipse Photon (JavaEE version)_  on Windows 10 I installed OpenJML as Eclipse Plugin from install site http://jmlspecs.sourceforge.net/openjml-updatesite, my project is using _OpenJDK 1.8.0_201_ (as project docs state that any non-OpenJDK and any non 1.8 version would not work!!!)

Settings:

![image](https://user-images.githubusercontent.com/22913012/56037613-6b399b80-5d38-11e9-813b-e428b9365282.png)

![image](https://user-images.githubusercontent.com/22913012/56037642-7bea1180-5d38-11e9-9624-df3e8b349dd5.png)

Project build yields:

![image](https://user-images.githubusercontent.com/22913012/56037729-b2279100-5d38-11e9-8714-46c6b22d70ac.png)

**Failure finding internal specs: java.net.URISyntaxException: Illegal character in path at index 16: file:/D:/Eclipse Photon Tmp Play With/eclipse/configuration/org.eclipse.osgi/1106/0/.cp/**

**Failure finding internal specs: java.net.URISyntaxException: Illegal character in path at index 16: file:/D:/Eclipse Photon Tmp Play With/eclipse/configuration/org.eclipse.osgi/1106/0/.cp/**

![image](https://user-images.githubusercontent.com/22913012/56037869-12b6ce00-5d39-11e9-8fa5-29c9c9d86b3e.png)

Eclipse Installation details:
![image](https://user-images.githubusercontent.com/22913012/56037813-e9963d80-5d38-11e9-8088-b49aa345fddd.png)

![image](https://user-images.githubusercontent.com/22913012/56037831-f87cf000-5d38-11e9-9249-07c0fe896394.png)

**Comment by wadoon** [comment]
Try with a project path that does not contain spaces. It seems that the path is wrongly encoded.

**Comment by davidcok** [comment]
This is indeed a problem with spaces in the URL, which is not a permitted format for a URI. This is a bug in OpenJDK as well. Added in a workaround (that properly encodes the spaces), which fixes my test case, though I don't have a windows environment to check it there.

**Comment by davidcok** [comment]
Fixed in 0.8.52
