### ISSUE TITLE
System.out.println() Specification 

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [OpenJML/OpenJML#681]
The attached code has specification for "System.out.println()" using the instruction in this [link](http://www.eecs.ucf.edu/~leavens/JML-release/javadocs/java/io/PrintStream.html#println(java.lang.String)).
 Then, I get the following error.

error: An error while executing a proof script for Even: (error "line 1012 column 35: invalid declaration, builtin symbol equals")
  >>>(declare-fun equals (REF REF ) Bool)
1 error

[OddOrEven.java.zip](https://github.com/OpenJML/OpenJML/files/3168292/OddOrEven.java.zip)

**Comment by Calvin-L** [comment]
I tried to use OpenJML for the first time today and encountered this exact error as well.

Source code:

```java
package mypackage;
class Main {
  //@ ensures System.out.outputText.equals("foo");
  public static void main(String[] args) {
    System.out.println("foo");
  }
}
```

Invocation:

    $ openjml -esc mypackage/Main.java
    error: An error while executing a proof script for main: (error "line 659 column 35: invalid declaration, builtin symbol equals")
      >>>(declare-fun equals (REF REF ) Bool)
    1 error

**Comment by davidcok** [comment]
Fixed and closed.

**Comment by davidcok** [comment]
Note that after println("foo"), System.out.outputText is "foo" + PrintStream.eol
