### ISSUE TITLE
Catastrophic JML internal error

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [OpenJML/OpenJML#682]
Catastrophic JML internal error after "esc" in the following small code.

[bug.zip](https://github.com/OpenJML/OpenJML/files/3193273/bug.zip)

**Comment by benozol** [comment]
The following example also causes an catastrophic internal error, even with the development branch including patch 399d8e1. If I replace the `PriorityQueue` with `Queue` the problem dissolves.

I am wondering if `PriorityQueue` is unsupported by OpenJML? Or is this problem unrelated to this issues and should I create a new one?

File `Mismatched.java`:
```java
import java.util.Queue;
import java.util.PriorityQueue;

public class Mismatched {
    void mismatched(PriorityQueue<Object> q) { // Using Queue instead of PriorityQueue works
        q.add(null);
    }
}
```
```shell
$ java -jar ~/setups/openjml-dev/openjml.jar  -esc src/Mismatched.java
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: MISMATCHED BLOCKS
error: ESC could not be attempted because of a failure in typechecking or AST transformation: mismatched
2 errors
```

**Comment by davidcok** [comment]
Closing this. The Catastrophic error was fixed per previous comment. Here corrected the spec of java.util.Queue so that Mismatched.java verifies.
