### ISSUE TITLE
Catastrophic internal error in recursive count

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#683]
I attempted to put in a recursive version of count to substitute for \num_of, but got this catastrophic internal error when running the attached.

/home/leavens/Java-OpenJML-Examples/QuickSort$ esc Count.java
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: java.lang.StackOverflowError
error: ESC could not be attempted because of a failure in typechecking or AST transformation: count
error: ESC could not be attempted because of a failure in typechecking or AST transformation: counteq

The JML isin the Java file contained in the attached zip file.

[CountExample.zip](https://github.com/OpenJML/OpenJML/files/3297070/CountExample.zip)

3 errors

**Comment by davidcok** [comment]
Gary - The crash was fixed a while ago. Just now I fixed the specs (without further changes to OpenJML) and arrived at this, clean working (under 0.8.50) evolution of your example. Closing this issue.

/** class to demonstrate the need for \num_of in JML. */
public class Count{
    /** returns the number of elements in arr[low..k-1] equal to e. */
    /*@
        requires 0 <= low <= k <= high <= arr.length;
        ensures k <= low ==> \result == 0;
        ensures low < k <= high
                ==> \result == counteq(arr, e, low, high, k-1)
                               + (e == arr[k-1] ? 1 : 0);
        ensures 0 <= \result <= k-low;
    @*/
    /*@ pure @*/ 
    int counteq(int arr[], int e, int low, int high, int k) {
        if (k <= low) {
            return 0;
        } else {
            return counteq(arr, e, low, high, k-1)
                   + (e == arr[k-1] ? 1 : 0);
        }
    }


    /*@
        requires 0 <= low <= high <= arr.length;
        ensures \result == counteq(arr, e, low, high, high);
        ensures 0 <= \result <= high-low;
    @*/
    /*@ pure @*/ 
    int count(int arr[], int e, int low, int high) {
        int sum = 0;
        //@ maintaining low <= i <= high;
        //@ maintaining sum == counteq(arr, e, low, high, i);
        for (int i = low; i < high; i++) {
            if (arr[i] == e) {
                sum++;
            }
        }
        return sum;
    }
}

**Comment by leavens** [comment]
Hi David,

Great, thanks for fixing this.


        Regards,

        Gary T. Leavens
        437D Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32916-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        Leavens@ucf.edu<mailto:Leavens@ucf.edu>
