### ISSUE TITLE
Infeasible path after calling `Arrays.sort(Object[], Comparator)`

### ISSUE THREAD

**Issue by benozol** [OpenJML/OpenJML#685]
Calling `Arrays.sort` with a comparator (an anonymous function as below or an instance of `Comparator`) results in an infeasible path. Running OpenJML from the command line reveals that this is due to the fact that `\num_of`, which is used in the specification of `Arrays.sort(a, c)`, is not yet supported by OpenJML. 

```java
public class Test {
    //@ requires \forall int i; 0 <= i && i < a.length; \typeof(a[i]) <: \type(Comparable<Object>);
    void f(Object[] a) {
       Arrays.sort(a);
       // @ assert a != null; // works
       Arrays.sort(a, (Object o1, Object o2) -> 0);
       // @ assert a != null; // <-- Test.java: warning: There is no feasible path to program point at program exit in method Test.f(java.lang.Object[])
    }
}
```

**Comment by davidcok** [comment]
Corrected the Array.sort specs -- removed references to num_of and fixed the case of sort(T[] a, /*@nullable*/ Comparator<? super T> c).

Added to test suite and is fixed on development head and will be fixed in version 0.8.51
