### ISSUE TITLE
Run Time problem

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [OpenJML/OpenJML#688]
The following code work by javac and java. Also, satisfied by esc, but for rac shows the following report.

Internal JML bug - please report.  BuildOpenJML-0.8.42-20190401
java.lang.AssertionError: _JML__tmp126

[DayTime.zip](https://github.com/OpenJML/OpenJML/files/3347284/DayTime.zip)

**Comment by davidcok** [comment]
This is fixed in 0.8.50. Please reopen the issue if it is still a problem for you.
