### ISSUE TITLE
Fix the zip file on website

### ISSUE THREAD

**Issue by andreabac3** [OpenJML/OpenJML#689]
I have tried to download the zip from http://www.openjml.org/downloads/ but at the end of the download process, I receive an error from the Archive Manager of GNOME 'An error occurred while loading the archive', of course, I have tried to download it multiple times. 

Finally, I was able to download and unzip the file from https://github.com/OpenJML/OpenJML/releases

**Comment by davidcok** [comment]
Fixed for 0.8.50 (and likely earlier). Also added an automation script for creating releases and a test script that downloads and tests a release after uploading to the distribution sites.
