### ISSUE TITLE
Unable to use -esc option in Docker container (Failed to start process error)

### ISSUE THREAD

**Issue by ValerioNeriGit** [OpenJML/OpenJML#690]
I created a docker container based upon the official image of oracle's java jdk on docker hub, with the following Dockerfile. I tried both the latest and the previous release.

``` Dockerfile
FROM openjdk:8-jdk-stretch

RUN apt update && apt install wget unzip

RUN mkdir /openjml \
    && wget https://github.com/OpenJML/OpenJML/releases/download/0.8.41/openjml-0.8.41-20190319.zip --output-document=openjml.zip \
    && unzip openjml.zip -d /openjml \
    && rm openjml.zip 
```

When I run it, with no option or the -rac option everything works fine, but when I use the -esc option it gives a *Failed to start process* error despite the fact that it works in my computer, I altro tried wit a ubuntu 16.04 base image and the openjdk 8. 
```
(error "Failed to start process /openjml/Solvers-linux/z3-4.3.1 : Stream closed")
error: Error occurred while attempting proof: (error "Failed to start process /openjml/Solvers-linux/z3-4.3.1 : Stream closed")
(error "z3_4_3 failed to start: Failed to start process /openjml/Solvers-linux/z3-4.3.1 : Stream closed")
error: An error while executing a proof script for divorce: (error "Error writing to Z3 solver: java.io.IOException: Stream closed")
error: An error while executing a proof script for haveBirthday: (error "Error writing to Z3 solver: java.io.IOException: Stream closed")
error: An error while executing a proof script for marry: (error "Error writing to Z3 solver: java.io.IOException: Stream closed")

```

I used a simple Java script to verify that it is possible to create process on with *ProcessBuilder* class inside the same container, the script works. The script is enclosed below..
``` Java
// Java code illustrating start() method 
import java.lang.*; 
import java.io.*; 
import java.util.*; 
class ProcessBuilderDemo 
{ 
    public static void main(String[] arg) throws IOException 
    { 
        // creating list of commands  
        List<String> commands = new ArrayList<String>(); 
        commands.add("ls"); // command 
        commands.add("-l"); // command 
        commands.add("/"); //command in Mac OS 

        // creating the process 
        ProcessBuilder pb = new ProcessBuilder(commands); 

        // startinf the process 
        Process process = pb.start(); 

        // for reading the ouput from stream 
        BufferedReader stdInput = new BufferedReader(new
         InputStreamReader(process.getInputStream())); 
        String s = null; 
        while ((s = stdInput.readLine()) != null) 
        { 
            System.out.println(s); 
        } 
    } 
} 
```

What can I do to make it working?
My image image has been uploaded to dockerhub at this link [dockerhub](https://hub.docker.com/r/valerioneri/openjml)

**Comment by davidcok** [comment]
Are you able to run z3-4.3.1 on its own; z3 is only used in -esc mode ?  (e.g. is it a permissions problem?)

**Comment by ValerioNeriGit** [comment]
Thank you for your quick reply, I found that the problem was the a missing  shared library (*libgomp1*) by running z3-4.3.1 as you suggested.

**Comment by davidcok** [comment]
Indeed,for development I use a Docker file that begins with

FROM ubuntu:16.04

RUN apt-get -y update
RUN apt-get -y install openjdk-8-jdk unzip wget libgomp1
 
RUN wget https://github.com/OpenJML/OpenJML/releases/download/0.8.42/openjml-0.8.42-20190401.zip <https://github.com/OpenJML/OpenJML/releases/download/0.8.42/openjml-0.8.42-20190401.zip>
RUN unzip openjml-0.8.42-20190401.zip


- David

**Comment by ValerioNeriGit** [comment]
I uploaded the image on Docker Hub and the Dockerfile (https://hub.docker.com/r/valerioneri/openjml) on github (https://github.com/ValerioNeriGit/Docker-Open-JML). 
I you want I could share these repos with you in order to provide an up to date and ready to use Docker image. If you want we could integrate this repo into your GitHub organization.
