### ISSUE TITLE
while i m updating eclipse ide with openJML its asking userid and password

### ISSUE THREAD

**Issue by renjithscse** [OpenJML/OpenJML#692]

**Comment by davidcok** [comment]
More detail please on just what you are doing. OpenJML does not ask for of need any passwords. If you are downloading from Git - it might, or Ec lips might be confused that it needs Git credentials.

**Comment by renjithscse** [comment]
Im using eclipse ide. When im trying to install OpenJML in eclipse by clicking new software installation and copying the provided url ,its asking user id and password

**Comment by renjithscse** [comment]
please provide link for installing openJML plug in eclipse. The provided link is asking user id and password. 
![installation error](https://user-images.githubusercontent.com/32746014/74586873-0747c980-5012-11ea-9850-e9edb7597917.JPG)

**Comment by davidcok** [comment]
It appears your system is trying to download Java Pathfinder. This is not included in OpenJML. I can not replicate this error from my system. Not sure yet what is happening.

**Comment by davidcok** [comment]
I'm guessing that the Uncategorized section contains more than just OpenJML.
Closing this now
