### ISSUE TITLE
String length and + not verifying

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#695]
When using + on a string and a char (on the right side), the verifier can't seem to show that the length of the result is one greater than the string on the left side.  That is in s+c, where s has type java.lang.String and c has type char, then we want to assert that s+c has length s.length()+1.  See the concatChar method in the class Reverser2 in the attached.

**Comment by leavens** [comment]
David noted that one shouldn't expect reasoning about strings to work well at the moment. But I also tried this with arrays (of chars) and had similar issues. In the attached you can find.two files ReverseArray.java and ReverseArrayWithAssume.java. The file ReverseArray.java is an attempt to verify the reversing code only using arrays, and it fails in similar ways as Reverser2 does. The ReverseArrayWithAssume file shows which assume statements are needed to make the verification pass in ESC.  Each assume in that file was an assert in ReverseArray and each one, if turned into an assert, will cause verification to fail.
[ReverseArrays.zip](https://github.com/OpenJML/OpenJML/files/4665045/ReverseArrays.zip)

**Comment by davidcok** [comment]
Gary, I'm cleaning up OpenJML Issues. Using 0.8.50

I get ReverseArray.java to verify by adjusting the asserts to be correct, and one adjustment to the Java - changing res += c to res = res + c.  I'll make a note to model string += char.

I'm appending my working version, but note two things. I did have to connect res.length() to \count, and there was an 'assert (len-1-i)+I < len' which is false when i is 0. In the ReserveArrayWithAssume this assertion is assumed, which his really wrong. I did not try to edit the Assume version.

public class ReverseArray {

    /*@ public normal_behavior
          requires 0 <= s.length && s.length < Integer.MAX_VALUE;
          ensures \fresh(\result);
          ensures (\forall int i; 0 <= i < s.length;
                     \result[i] == s[s.length - 1 - i]);
      @*/
    public /*@ pure @*/ char[] reverse(char[] s) {
        final int len = s.length;
        //@ assert len == s.length;
        char[] res = (char[]) new char[len];
        //@ assert len == res.length;
        int i = len-1;
        /** rlen tells how many elements of res are defined. **/
        int rlen = 0;
        //@ maintaining len == res.length;
        //@ maintaining -1 <= i < len;
        //@ maintaining rlen == (len-1) - i && rlen <= len;
        /*@ maintaining (\forall int j; 0 <= j < len-1-i;
                                 res[j] == s[len-1-j]); @*/
        while (0 <= i && i < len) {
            //@ assert 0 <= i < s.length && 0 <= len-i <= len;
            // System.out.println("i is " + i + ", len-1-i is " + (len-1-i));
            //@ assert res.length == len;
            //@ assert (len-1-i)+1 <= len;
            res[len-1-i] = s[i];
            //@ assert res[(len-1-i)] == s[i];
            rlen += 1;
            //@ assert rlen == ((len-1) - i) + 1;
            // System.out.println("res[len-1-i] == s[i] is " + (res[len-1-i] == s[i]));
            i--;
        }
        //@ assert i == -1;
        //@ assert rlen == len;
        /*@ assert (\forall int k; 0 <= k < len; res[k] == s[len-1 - k]); @*/
        return res;
    }

    public static void main(String [] argv) {
        ReverseArray ra = new ReverseArray();
        char [] abc = new char[3];
        abc[0] = 'a'; abc[1] = 'b'; abc[2] = 'c';
        char[] revd = ra.reverse(abc);
        System.out.println("reverse(abc) is \""
                           + ReverseArray.arr2str(revd)
                           + "\"");
    }

    /*@ public normal_behavior
          ensures \result.length() == a.length;
          ensures (\forall int i; 0 <= i && i < a.length; 
                                  \result.charAt(i) == a[i]);
      @*/
    public /*@ pure @*/ static String arr2str(char[] a) {
        String res = "";
        //@ maintaining res.length() <= a.length;
        //@ maintaining res.length() == \count;
        //@ maintaining (\forall int j; 0 <= j < res.length(); res.charAt(j) == a[j]);
        for (char c : a) {
            res = res + c; // res += c;
        }
        //@ assert res.length() == a.length;
        //@ assert (\forall int j; 0 <= j && j < res.length(); res.charAt(j) == a[j]);
        return res;
    }
}

**Comment by leavens** [comment]
Hi David,

Thanks much. I was able to verify the code also using 0.8.50.  Very nice!

        Regards,

        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens  phone: +1-407-823-4758
        Leavens@ucf.edu<mailto:Leavens@ucf.edu>
