### ISSUE TITLE
Disable static checking on a method help to an JML annotation ?

### ISSUE THREAD

**Issue by GabrielHerry** [OpenJML/OpenJML#697]
Hello, I am a new user of OpenJML.
I work with Eclipse.
My question : is that possible to disable static checking on a method help to an JML annotation ?

Thanks,

**Comment by davidcok** [comment]
Not sure of your question. However, annotating a method with //@ skipesk
will disable static checking for that method.  There is also a commanding option to choose/exclude methods for checking.

- David

**Comment by GabrielHerry** [comment]
Perfect, thanks for answering that quick  !
