### ISSUE TITLE
Math.jml --> asin & sqrt

### ISSUE THREAD

**Issue by GabrielHerry** [OpenJML/OpenJML#699]
Hello, I saw two things that might be modified, from my understanding, in Math.jml from : Eclipse\configuration\org.eclipse.osgi\532\0\.cp

First : 
in the function asin : 

/*@ public normal_behavior
@ {|
@   requires Double.isNaN(a) || a > 1 || a < -1;
@   ensures Double.isNaN(\result);
@ also
@   requires a == 0.0;  // positive or negative zero
@   ensures \result == 0.0;
@ also
@   requires isPositiveZero(a);
@   ensures isPositiveZero(\result);
@ also
@   requires isNegativeZero(a);
@   ensures isNegativeZero(\result);
@ also
@   requires !isFinite(a) && a <= 1 && a >= -1;
@   ensures -PI/2 <= \result && \result <= PI/2;
@   ensures (* result within 1 ulp of exact result *);
@ |}
@*/
public static /*@ pure @*/ double asin(double a);

wouldn't it be better to write :
`@   requires !Double.isNaN(a) && a <= 1 && a >= -1; ` 
Instead of : 
` @   requires !isFinite(a) && a <= 1 && a >= -1; ` ?

Also : 
In sqrt : 

  
/*@ public normal_behavior
@ {|
@   requires Double.isNaN(a) || a < 0.0;
@   ensures Double.isNaN(\result);
@ also
@   requires a == Double.POSITIVE_INFINITY;
@   ensures \result == Double.POSITIVE_INFINITY;
@ also
@   requires isPositiveZero(a);
@   ensures isPositiveZero(\result);
@ also
@   requires isNegativeZero(a);
@   ensures isNegativeZero(\result);
@ also
@   requires a > 0.0 && a < Double.POSITIVE_INFINITY;
@   ensures close(a, \result * \result, 2.0E-16);
@ |}  
@*/
public static /*@ pure @*/ double sqrt(double a);

With this spec, when I launch the static checking I never get out an sqrt function.
By never, I mean, I waited an hour and then cancelled the static checking. 

By changing 
`@   ensures close(a, \result * \result, 2.0E-16);`
with 
`@   ensures close(a, \result * \result, 2.0E-6);`
that working and the computed time is inferior to a second.

Let me know what you think about that.
Thanks,

**Comment by davidcok** [comment]
The first one: requires !isFinite(a) && a <= 1 && a >= -1; should be requires isFinite(a) && a <= 1 && a >= -1;

I also did the change in sort.

Thanks for pointing these out.
