### ISSUE TITLE
org.eclipse.osgi -> specs -> Map.jml

### ISSUE THREAD

**Issue by GabrielHerry** [OpenJML/OpenJML#700]
Hello, 

I had some trouble with Map.jml

This file is located in : eclipse/configuration/org.eclipse.osgi/451/0/.cp/specs/java/util

Here the code of put method : 

    /*-RAC@ public normal_behavior
      @    // requires containsNull || (key != null && value != null);
      @    assignable modelMap, keys;
      @    ensures modelMap == \old(modelMap).put(key,value);
      @    ensures hasKey(key);
      @    ensures modelMap.get(key) == value;
      @    ensures \result == \old(modelMap).get(key);
      @     // FIXME: Need to state that the map values are unchanged
      @*/
    /* FIXME @
      @ also exceptional_behavior
      @    signals (NullPointerException) \not_modified(value)
      @             && (key==null)||(value==null) && !containsNull;
      @    signals (UnsupportedOperationException) \not_modified(theMap) 
      @             && (* if the map's put operation is not supported  *);
      @    signals (ClassCastException) \not_modified(theMap)
      @             && (* \typeof(key) or \typeof(value) is incompatible
      @                with the corresponding V or K type *);
      @    signals (IllegalArgumentException) \not_modified(theMap)
      @             && (* if some aspect of key or value is not 
      @                allowed in the map *);
      @*/
    /*@ nullable */V put(/*@ nullable */ K key, /*@ nullable */ V value);

I thing that the line : 
`@    ensures \result == \old(modelMap).get(key);`
could be : 
`@    ensures \result == modelMap.get(key);`

What do you think about that ?

Thank you,

**Comment by davidcok** [comment]
Gabriel, Your change would be incorrect. If you read the spec for Map.put at https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#put-K-V- you find that the return value is the _previous_ value in the map, not the current value.
