### ISSUE TITLE
Faulty ensures?

### ISSUE THREAD

**Issue by gabrieltigerstrom** [OpenJML/OpenJML#704]
I'm very new to OpenJML, I am using it as part of a university course
While writing annotations for a method wrapping `Arrays.binarySearch(int[], int)`, I encountered some (to me) strange behaviour.

My assumption would be that OpenJML would complain about the `ensures` statement below since `\result` is not strictly larger than -1.

```java
//@ requires values != null;
//@ requires (\forall int i, j; 0 <= i & i < j & j < values.length; values[i] <= values[j]);
//@ ensures -1 < \result & \result < values.length;
int binarySearch(int values[], int x) {
	try {
		return Arrays.binarySearch(values, x);
	}
	catch(Exception e) {
		return -1;
	}
}
```
I ran the code above (as part of a larger program) with the following output.
```
➜  java -jar openjml.jar -esc ../JMLTest/Main.java
../JMLTest/Main.java:72: warning: NOT IMPLEMENTED: Not yet supported feature in converting BasicPrograms to SMTLIB: JML Quantified expression using \num_of
../JMLTest/Main.java:72: warning: NOT IMPLEMENTED: Not yet supported feature in converting BasicPrograms to SMTLIB: JML Quantified expression using \num_of

```
I could not find anything in the [JML's specification of java.util.Arrays](http://www.eecs.ucf.edu/~leavens/JML-release/javadocs/java/util/Arrays.html#binarySearch(int[],%20int)) that explains this behaviour.

If I change the statement to `@ ensures 0 < \result & \result < values.length;` I get an error saying `The prover cannot establish an assertion`. And the following warning pointing out the ensures statement.
```
../JMLTest/Main.java:28: warning: Associated declaration: ../JMLTest/Main.java:32: 
	//@ ensures 0 < \result & \result < values.length;
	    ^
```
Is this a bug? Or (more likely) have I misunderstood something regarding declaration of post-conditions?

OpenJML version: openjml OpenJML-0.8.46-20200505
Java version:
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**Comment by davidcok** [comment]
Hi Gabriel,

I’m glad you are trying out OpenJML — feel free to send followup questions.

As for this one:
1) Please upgrade to V0.8.49 as there have been many bug fixes in the interim — in my test that (along with improved Specs) fixes this problem
2) I can’t comment on \num_of as it is not used here, but indeed it is not yet supported.
3) Note also that the specs on library methods, such as binarySearch, are not very complete.

- David

**Comment by gabrieltigerstrom** [comment]
Hi again,

Thank you for the rapid reply! I'll upgrade to the latest version.
I'm liking OpenJML so far. It feels much more powerful than formal verification programs I've previously used for C.
