### ISSUE TITLE
two-sum algorithm problem meets openjml: basic questions

### ISSUE THREAD

**Issue by dariomx** [OpenJML/OpenJML#707]
Dear all,

I am trying to get a grasp of JML through OpenJML, and thought that a
very cool example would be the canonical algorithm question two-sum:

https://leetcode.com/problems/two-sum

Canonical solution is to use a hash-table to remember seen elements,
which leads to O(n) time and memory complexities. Below a Java program
that implements such idea and passes all tests in leetcode link above;
it also includes JML pre and post conditions:

https://gitlab.com/dario.mx/leetcode-jml/-/blob/master/src/easy/two-sum/TwoSum.java

Still, when I try this on OpenJML, it can not really prove any of my
post-conditions. See bottom for a sample execution on the command
line. Could you share your thoughts about the nature of these
warnings? Is it lack of supported Java features, or lack of theorem
prover power or I am missing something?

I am in particular confused by the basic post conditions about the
result array, which I ask to have length 2 and to contain a couple of
indexes from the array. Still OpenJML can not prove any of that, and
even more says that it can not prove the index is non negative; which
I do not get, the index is getting its value from a positive domain.
Similarly the result array is assigned twice to a static array of size
two; hence, why it can not prove my post-condition about its size?
Before understanding these cases, maybe it is not worth it to ask
about the really interesting post-condition; the one saying  that the
resulting two indexes shall correspond to elements x and y in the
array, such that x + y == target.

Am I missing something fundamental here? Please help me see the light :-)

Thanks.

```
# ./openjml -esc examples/two-sum/TwoSum.java
examples/two-sum/TwoSum.java:24: warning: The prover cannot establish
an assertion (PossiblyNegativeIndex) in method twoSum
            int x = nums[i];
                        ^
examples/two-sum/TwoSum.java:33: warning: The prover cannot establish
an assertion (Postcondition: examples/two-sum/TwoSum.java:15: ) in
method twoSum
        return ans;
        ^
examples/two-sum/TwoSum.java:15: warning: Associated declaration:
examples/two-sum/TwoSum.java:33:
      @ ensures \result.length == 2;
        ^
examples/two-sum/TwoSum.java:33: warning: The prover cannot establish
an assertion (Postcondition: examples/two-sum/TwoSum.java:18: ) in
method twoSum
        return ans;
        ^
examples/two-sum/TwoSum.java:18: warning: Associated declaration:
examples/two-sum/TwoSum.java:33:
      @ ensures nums[\result[0]] + nums[\result[1]] == target;
        ^
examples/two-sum/TwoSum.java:33: warning: The prover cannot establish
an assertion (Postcondition: examples/two-sum/TwoSum.java:16: ) in
method twoSum
        return ans;
        ^
examples/two-sum/TwoSum.java:16: warning: Associated declaration:
examples/two-sum/TwoSum.java:33:
      @ ensures \exists int i, j; 0 <= i && i < j && j < nums.length;
        ^

./openjml.jar(specs/org/jmlspecs/lang/intmap.jml):23: warning: The
prover cannot establish an assertion (UndefinedNullDeReference:
./openjml.jar(specs/org/jmlspecs/lang/intmap.jml):28: ) in method
twoSum
      ensures this[k] == v ==> \result == this;
                  ^
./openjml.jar(specs/org/jmlspecs/lang/intmap.jml):28: warning:
Associated declaration:
./openjml.jar(specs/org/jmlspecs/lang/intmap.jml):23:
9 warnings
```

**Comment by davidcok** [comment]
Hi - thanks for your interest and inquiry.

One basic point that you need to address is that every loop needs loop invariants to prove anything.

Secondly, a helpful way to debug proof problems is to work methodically through the method: comment out your postconditions, add assertions to state what you expect to be valid at each relevant program point and see where proof fails. Work step by step so that errors are identified early in the program. Proof failures can either be a lack of proof power (which I can comment on given an example) or lack of the right specs statements.

Third, Collection classes (like a HashMap - though why not just use a HashSet) are not completely specified and can be difficult to reasonably about. Get back to me if that is the source of problems. You can work around library specification problems by putting in temporary assume statements.

Fourth, be sure you are using the latest release.

- David

**Comment by dariomx** [comment]
Dear David,

Thanks for your early response, I was waiting for it on my email but looks like I do not get notices; my bad.

I can see my fears came true, as I was suspecting indeed that loop invariants were a must. I am new to formal methods, and indeed have been trying your second recommendation about the incremental approach to debugging with regards pre/post conditions. But I was hoping, naively I guess, that the logic inside my function could be handled without further  information. 

Having to put invariants in every loop is kinda discouraging for a new comer, as the amount of effort raises considerably; just putting pre and post conditions on the other hand was super attractive. Fearing to sin again of naiveness, could you share basic references towards explaining why one needs to provide invariants on the loops? Is that because of the halting problem? 

Thanks again.

**Comment by dariomx** [comment]
Closing as seems underlying theory (CAR-Hoare Logic) requires such invariants. Will try simpler examples first.
