### ISSUE TITLE
Index relationships of nested loop not flowing into invariants?

### ISSUE THREAD

**Issue by dariomx** [OpenJML/OpenJML#709]
Greetings Sir,

Please consider following snippet:

```


class NestedLoop1 {

  /*@ requires 2 <= nums.length && nums.length <= 1000;
    @ ensures \result.length == 2;
    @*/
  public int[] nestedLoop1(int[] nums) {
    int[] ans = new int[]{0, 1};
    /*@ maintaining 0 <= i && i <= nums.length;
      @*/
    for (int i = 0; i < nums.length; i++) {
      /*@ maintaining 0 <= j && j <= nums.length;
        @ maintaining i < j;
        @ maintaining ans[0] < ans[1];
        @*/
      for(int j=i+1; j < nums.length; j++) {
          ans[0] = i;
          ans[1] = j;
      }
    }
    return ans;
  }

}
```
For now, pretty much I want to compute the last two indexes from the array; though not enforcing as post-condition yet. For now I am trying to put some of it first as an invariant on the nested loop, but is failing. If I remove the last invariant of "ans[0] < ans[1]", everything passes fine; so it is that one causing trouble.

The definition of the loops themselves implies "i < j", and apparently we can prove that as invariant. Then on nested loop we assign precisely those indexes to ans[0] and ans[1]. I am not sure then, why the post-condition "ans[0] < ans[1]" can not be proved. I guess I am missing something else right?

Thanks.

**Comment by davidcok** [comment]
The problem, at least when I run with current OpenJML, is that the invariant ‘ans,[0] < ans[1]’ is not true before the loop is entered, as is required of loop invariants.
You need the 'maintaining ans[0] < ans[1];’ invariant for the outer loop as well. Adding that makes this example work for me.

**Comment by dariomx** [comment]
Thanks David, that made the trick indeed. I can now ask for same invariant as a post-condition and it propagates nicely. Below final code just for reference:

```


class NestedLoop1 {

  /*@ requires 2 <= nums.length && nums.length <= 1000;
    @ ensures \result.length == 2;
    @ ensures \result[0] < \result[1];
    @*/
  public int[] nestedLoop1(int[] nums) {
    int[] ans = new int[]{0, 1};
    /*@ maintaining 0 <= i && i <= nums.length;
      @ maintaining ans[0] < ans[1];
      @*/
    for (int i = 0; i < nums.length; i++) {
      /*@ maintaining 0 <= j && j <= nums.length;
        @ maintaining i < j;
        @ maintaining ans[0] < ans[1];
        @*/
      for(int j=i+1; j < nums.length; j++) {
          ans[0] = i;
          ans[1] = j;
      }
    }
    return ans;
  }

}
```
