### ISSUE TITLE
Problem with substring(int beginindex)

### ISSUE THREAD

**Issue by davidebasile** [OpenJML/OpenJML#712]
Hello, 
with this code:

package CA;
public class Alice {
	public String alice() {
		String alice="Alice";
		return alice.substring(1);
	}
}

the ESC output the errors reported below. 
I managed to fix the issue by using  alice.substring(1,alice.length())  that works fine.

Best
Davide

[0.00] Executing openjml on Alice.java
[1.69] Completed
Using external solver C:\Users\Davide\z3-4.3.0-x86\bin\z3.exe
Proving methods in CA.Alice
Starting proof of CA.Alice.Alice() with prover z3_4_3
Method assertions are validated [1.88 secs]
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:3: Feasibility check #1 - end of preconditions : OK [0.11 secs]
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:3: Feasibility check #2 - at program exit : OK [0.24 secs]
Completed proof of CA.Alice.Alice() with prover z3_4_3 - no warnings [2.42 secs]
Starting proof of CA.Alice.alice() with prover z3_4_3
CA.Alice.alice Method assertions are INVALID
C:\Users\Davide\eclipse\java-2018-09\eclipse\configuration\org.eclipse.osgi\1202\0\.cp\specs\java\lang\String.jml:838: warning: The prover cannot establish an assertion (UndefinedCalledMethodPrecondition: C:\Users\Davide\eclipse\java-2018-09\eclipse\configuration\org.eclipse.osgi\1202\0\.cp\specs\java\lang\CharSequence.jml:56: ) in method alice
      @            && equal(\result.charArray,0,charArray,beginIndex,
                           ^
Note: Call stack
  C:\Users\Davide\eclipse\java-2018-09\eclipse\configuration\org.eclipse.osgi\1202\0\.cp\specs\java\lang\String.jml:838: : java.lang.CharSequence.equal
  C:\Users\Davide\eclipse\java-2018-09\eclipse\configuration\org.eclipse.osgi\1202\0\.cp\specs\java\lang\String.jml:820: : java.lang.String.substring
  C:\Users\Davide\git\FMCAT\src\CA\Alice.java:6: : java.lang.String.substring
C:\Users\Davide\eclipse\java-2018-09\eclipse\configuration\org.eclipse.osgi\1202\0\.cp\specs\java\lang\CharSequence.jml:56: warning: Precondition conjunct is false: a != null
        public static pure helper model boolean equal(char[] a, \bigint astart, char[] b, \bigint bstart, \bigint len);
                                                             ^

TRACE of CA.Alice.alice()
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:5:  	/*@ non_null */  String alice = "Alice"
			VALUE: "Alice"	 === REF!val!18
			VALUE: alice	 === REF!val!18
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	//@ public final invariant charArray != null; 
			VALUE: charArray	 === REF!val!19
			VALUE: null	 === NULL
			VALUE: charArray != null	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:5:  	UndefinedTooLargeIndex assertion: !(_JML__tmp55 != null) || _JML__tmp55.charArray.length > 0
			VALUE: 0	 === 0
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:5:  	UndefinedTooLargeIndex assertion: !(_JML__tmp55 != null) || _JML__tmp55.charArray.length > 1
			VALUE: 1	 === 1
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:5:  	UndefinedTooLargeIndex assertion: !(_JML__tmp55 != null) || _JML__tmp55.charArray.length > 2
			VALUE: 2	 === 2
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:5:  	UndefinedTooLargeIndex assertion: !(_JML__tmp55 != null) || _JML__tmp55.charArray.length > 3
			VALUE: 3	 === 3
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:5:  	UndefinedTooLargeIndex assertion: !(_JML__tmp55 != null) || _JML__tmp55.charArray.length > 4
			VALUE: 4	 === 4
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:5:  	PossiblyNullInitialization assertion: _JML__tmp55 != null
			VALUE: null	 === NULL
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:6:  	return alice.substring(1);
			VALUE: alice	 === REF!val!18
			VALUE: 1	 === 1
			VALUE: alice.substring(1)	 === REF!val!25
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:6:  	PossiblyNullDeReference assertion: _JML__tmp74 != null
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	requires 0 <= beginIndex; 
			VALUE: 0	 === 0
			VALUE: 0 <= beginIndex	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	requires beginIndex <= length(); 
			VALUE: beginIndex	 === 1
			VALUE: length()	 === 5
			VALUE: beginIndex <= length()	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:1:  	UndefinedCalledMethodPrecondition assertion: _$CPRE__26
			VALUE: _$CPRE__26	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	UndefinedNullDeReference assertion: !(_JML__tmp79.charArray != null) || _JML__tmp79.charArray != null
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	requires beginIndex < 0 || beginIndex > length(); 
			VALUE: 0	 === 0
			VALUE: beginIndex	 === 1
			VALUE: length()	 === 5
			VALUE: beginIndex > length()	 === false
			VALUE: beginIndex < 0 || beginIndex > length()	 === false
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:1:  	UndefinedCalledMethodPrecondition assertion: _$CPRE__27
			VALUE: _$CPRE__27	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	UndefinedNullDeReference assertion: !(_JML__tmp90.charArray != null) || _JML__tmp90.charArray != null
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	Precondition assertion: _$CPRE__25
			VALUE: _$CPRE__25	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	//@ public final invariant charArray != null; 
			VALUE: charArray	 === REF!val!19
			VALUE: null	 === NULL
			VALUE: charArray != null	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	//@ public final invariant charArray != null; 
			VALUE: charArray	 === REF!val!27
			VALUE: null	 === NULL
			VALUE: charArray != null	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:1:  	UndefinedCalledMethodPrecondition assertion: _$CPRE__30
			VALUE: _$CPRE__30	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	UndefinedNullDeReference assertion: !(_JML__tmp106.charArray != null) || _JML__tmp106.charArray != null
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	requires 0 <= beginIndex && beginIndex <= endIndex && (endIndex <= length()); 
			VALUE: 0	 === 0
			VALUE: 0 <= beginIndex	 === true
			VALUE: beginIndex	 === 1
			VALUE: endIndex	 === 5
			VALUE: beginIndex <= endIndex	 === true
			VALUE: endIndex	 === 5
			VALUE: length()	 === 5
			VALUE: endIndex <= length()	 === true
			VALUE: (endIndex <= length())	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:1:  	UndefinedCalledMethodPrecondition assertion: _$CPRE__31
			VALUE: _$CPRE__31	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	UndefinedNullDeReference assertion: !(_JML__tmp120.charArray != null) || _JML__tmp120.charArray != null
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	UndefinedCalledMethodPrecondition assertion: _$CPRE__29
			VALUE: _$CPRE__29	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	//@ public final invariant charArray != null; 
			VALUE: charArray	 === REF!val!19
			VALUE: null	 === NULL
			VALUE: charArray != null	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	UndefinedNullDeReference assertion: !_JML__tmp116 || _JML__tmp139 != null
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:1:  	UndefinedCalledMethodPrecondition assertion: _$CPRE__32
			VALUE: _$CPRE__32	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	UndefinedNullDeReference assertion: !(_JML__tmp139.charArray != null) || _JML__tmp139.charArray != null
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	requires a != null; 
			VALUE: a	 === NULL
			VALUE: null	 === NULL
			VALUE: a != null	 === false
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	requires b != null; 
			VALUE: b	 === REF!val!19
			VALUE: null	 === NULL
			VALUE: b != null	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	requires a != null && b != null && astart >= 0 && bstart >= 0 && len >= 0 && astart + len <= a.length && bstart + len <= b.length; 
			VALUE: a	 === NULL
			VALUE: null	 === NULL
			VALUE: a != null	 === false
			VALUE: astart	 === 0
			VALUE: 0	 === 0
			VALUE: astart >= 0	 === true
			VALUE: bstart	 === 1
			VALUE: 0	 === 0
			VALUE: bstart >= 0	 === true
			VALUE: len	 === 4
			VALUE: 0	 === 0
			VALUE: len >= 0	 === true
			VALUE: astart	 === 0
			VALUE: len	 === 4
			VALUE: astart + len	 === 4
			VALUE: a.length	 === 4
			VALUE: astart + len <= a.length	 === true
			VALUE: bstart	 === 1
			VALUE: len	 === 4
			VALUE: bstart + len	 === 5
			VALUE: b.length	 === 5
			VALUE: bstart + len <= b.length	 === true
C:\Users\Davide\git\FMCAT\src\CA\Alice.java:9:  	UndefinedCalledMethodPrecondition assertion: _$CPRE__33
			VALUE: _$CPRE__33	 === false
C:\Users\Davide\eclipse\java-2018-09\eclipse\configuration\org.eclipse.osgi\1202\0\.cp\specs\java\lang\String.jml:838:  Invalid assertion (UndefinedCalledMethodPrecondition)
: C:\Users\Davide\eclipse\java-2018-09\eclipse\configuration\org.eclipse.osgi\1202\0\.cp\specs\java\lang\CharSequence.jml:56:  Associated location

Completed proof of CA.Alice.alice() with prover z3_4_3 - with warnings [2.31 secs]
Completed proving methods in CA.Alice [4.91 secs]
Summary:
    Valid:        1
    Invalid:      1
    Infeasible:   0
    Timeout:      0
    Error:        0
    Skipped:      0
   TOTAL METHODS: 2
   Classes:       0 proved of 1
   Model Classes: 0
   Model methods: 0 proved of 0
   DURATION:          5.1 secs
[6.76] Completed

**Comment by davidcok** [comment]
Thanks for the alert. The library spec for substring(int beginIndex) was not as complete as that for substring(int beginIndex, int endIndex). I've fixed that and it will be in the next release (after the just issued 0.8.50). I made your example a test case as well, so it won't break in the future.
