### ISSUE TITLE
Prover fails to verify simple array copy method

### ISSUE THREAD

**Issue by 0xD3ADBEEF** [OpenJML/OpenJML#716]
The code is as follows:
``` java
/*@
 requires 0 <= len && len <= src.length-srcOfs && len <= dst.length;
 requires 0 <= srcOfs && srcOfs < src.length;
 ensures \forall int k;0 <= k && k < len;dst[k] == src[srcOfs + k];
 @*/
public static void CopyArray(final /*@non_null \readonly @*/ int [] src, final int srcOfs, /*@ non_null @*/int [] dst, final int len) {
	//@ loop_invariant \forall int k;0 <= k && k < i;dst[k] == src[srcOfs+k];
	//@ loop_invariant \forall int k;i <= k && k < dst.length; dst[k]==\old(dst[k]);
	//@ loop_invariant 0 <= i && i <= len;
	//@ decreasing len-i;
	for(int i = 0;i < len;i++) {
		dst[i] = src[srcOfs+i];
	}
}
```
Output from z3:

`...  //@ loop_invariant \forall int k; 0 <= k && k < i; dst[k] == src[srcOfs + k];
			VALUE: \forall int k; 0 <= k && k < i; dst[k] == src[srcOfs + k]	 === false

... LoopInvariant assertion: _JML__tmp211

... Invalid assertion (LoopInvariant)
`
A very similar method however is proven correctly:

``` java
/*@
 requires src != null && dst != null && 0 <= len && len <= src.length && len <= dst.length;
 ensures src != null && dst != null;
 ensures \forall int k;0 <= k && k < len;dst[k] == src[k];
 @*/
public static void CopyArray(final int [] src, int [] dst, final int len) {
	//@ loop_invariant \forall int k;0 <= k && k < i;dst[k] == src[k];
	//@ loop_invariant 0 <= i && i <= len;
	//@ decreasing len-i;
	for(int i = 0;i < len;i++) {
		dst[i] = src[i];
	}
}
```
Seems that the problem is related to the index arithmetic `srcOfs + k`. I have tried many techniques, and searched everywhere to resolve this issue, but it seems that it is related to the prover.

**Comment by davidcok** [comment]
Hi Viktorio,

The problem id that you need the precondition 'requires src != dst;'
Then, at least with the current version for me, the problem verifies just fine.
I agree that differences in indexing patterns can be a problem for the prover, but that does not seem to be the case here -- and in this code the assertions match the code precisely.
It is also difficult to spot verification failures due to aliasing, as is the case here.

**Comment by davidcok** [comment]
In your second example, which works, if src == dst the code just does nothing -- aliasing is not a problem

**Comment by 0xD3ADBEEF** [comment]
Thank you very much for the clarification. I spent almost 4 hours trying to get this to verify, until I gave up, and the feedback from the model checker was useless in that regard.

Suppose that I run into a similar issue in the future, how can I troubleshoot it? Are there any clues in the counter example trace that can give me a hint? Is there a good reference that discusses similar issues? I have primarily used JML in courses, but now I'm genuinely interested in applying this for my work.

**Comment by 0xD3ADBEEF** [comment]
For example, this modified method with the new precondition also fails to verify:
```java
/*@
 requires src != dst;
 requires 0 <= len && len <= src.length-srcOfs && len <= dst.length-dstOfs;
 requires 0 <= srcOfs && srcOfs < src.length;
 requires 0 <= dstOfs && dstOfs < dst.length;
 ensures \forall int k;0 <= k && k < len;dst[dstOfs + k] == src[srcOfs + k];
 @*/
public static void CopyArray(final /*@non_null \readonly @*/ int [] src, final int srcOfs, 
							/*@ non_null @*/int [] dst, final int dstOfs,
							final int len) {
        //@ loop_invariant 0 <= i && i <= len;
	//@ loop_invariant \forall int k;0 <= k && k < dstOfs; dst[k]==\old(dst[k]);
	//@ loop_invariant \forall int k; dstOfs+i <= k && k < dst.length; dst[k]==\old(dst[k]);
	//@ loop_invariant \forall int k;0 <= k && k < i;dst[dstOfs+k] == src[srcOfs+k];
	//@ decreasing len-i;
	for(int i = 0;i < len;i++) {
		dst[dstOfs+i] = src[srcOfs+i];
		//@ assert dst[dstOfs+i]==src[srcOfs+i];
	}
}
```

**Comment by davidcok** [comment]
This one is a case of indices. It typically works better to have one index be a simple [k], as in this, which works for me:

public class Test {
  
/*@
 requires src != dst;
 requires 0 <= len && len <= src.length-srcOfs && len <= dst.length-dstOfs;
 requires 0 <= srcOfs && srcOfs < src.length;
 requires 0 <= dstOfs && dstOfs < dst.length;
 ensures \forall int k;0 <= k && k < len;dst[dstOfs + k] == src[srcOfs + k];
 @*/
public static void CopyArray(final /*@non_null \readonly @*/ int [] src, final int srcOfs,
                                                        /*@ non_null @*/int [] dst, final int dstOfs,
                                                        final int len) {
        //@ loop_invariant 0 <= i && i <= len;
        //@ loop_invariant \forall int k;0 <= k && k < dstOfs; dst[k]==\old(dst[k]);
        //@ loop_invariant \forall int k; dstOfs+i <= k && k < dst.length; dst[k]==\old(dst[k]);
        //@ loop_invariant \forall int k;dstOfs <= k && k < dstOfs+i;dst[k] == src[srcOfs-dstOfs+k];
        //@ decreasing len-i;
        for(int i = 0;i < len;i++) {
                dst[dstOfs+i] = src[srcOfs+i];
                //@ assert dst[dstOfs+i]==src[srcOfs+i];
        }
}

}
~                                                                               
public class Test {
  
/*@
 requires src != dst;
 requires 0 <= len && len <= src.length-srcOfs && len <= dst.length-dstOfs;
 requires 0 <= srcOfs && srcOfs < src.length;
 requires 0 <= dstOfs && dstOfs < dst.length;
 ensures \forall int k;0 <= k && k < len;dst[dstOfs + k] == src[srcOfs + k];
 @*/
public static void CopyArray(final /*@non_null \readonly @*/ int [] src, final int srcOfs,
                                                        /*@ non_null @*/int [] dst, final int dstOfs,
                                                        final int len) {
        //@ loop_invariant 0 <= i && i <= len;
        //@ loop_invariant \forall int k;0 <= k && k < dstOfs; dst[k]==\old(dst[k]);
        //@ loop_invariant \forall int k; dstOfs+i <= k && k < dst.length; dst[k]==\old(dst[k]);
        //@ loop_invariant \forall int k;dstOfs <= k && k < dstOfs+i;dst[k] == src[srcOfs-dstOfs+k];
        //@ decreasing len-i;
        for(int i = 0;i < len;i++) {
                dst[dstOfs+i] = src[srcOfs+i];
                //@ assert dst[dstOfs+i]==src[srcOfs+i];
        }
}

}
~

**Comment by davidcok** [comment]
As for debugging, that is definitely an art. I usually debug by putting in lots of assumes and intermediate asserts to sort out where the problem really lies and then slowly weed them out as I strengthen what ever was missing.

Sometimes the information given with -counterexample is helpful, but often it is just overwhelming (and the format and connection to the source code needs improving). For your original problem I get with -counterexample

java.lang.Object_theString_7989_0___2 = ( _ as-array k!196 )
src_0_0___6 = REF!val!6
_JML__tmp6 = NULL
Test_`alloc___7_0___3 = ( _ as-array k!193 )
_JML__tmp7 = true
_JML__tmp5 = true
_JML__tmp8 = true
dst_326_326___12 = REF!val!5
_JML__tmp11 = true
ASSERT_62 = true
arrays_INT_0 = ( _ as-array k!197 )
srcOfs = 24637
len_0_0___9 = 0
dst_0_0___8 = REF!val!6
_JML__tmp23 = true
Test__heap___0_0___4 = 0
srcOfs_0_0___7 = 0
`terminationPosition_231_231___11 = 0
`exception_231_231___10 = NULL
java.lang.Object_owner_1510_0___5 = ( _ as-array k!195 )
Pre_2_115_25___22 = true
__JML_AssumeCheck_ = 0
src = REF!val!5

which shows dst and src pointing to the same values, confused by the fact that there are two entries for each.

Perhaps a better approach is to add annotations like this:
        for(int i = 0;i < len;i++) {
                //@ assume i == 2 && len == 4;
                dst[i] = src[srcOfs+i];
                //@ assert dst[i] == src[srcOfs+i];
        }

and then use -subexpressions, which gives, in part, this

Test.java:15:  	assert Assert dst[i] == src[srcOfs + i];
			VALUE: dst	 === REF!val!6
			VALUE: i	 === 2
			VALUE: dst[i]	 === 80
			VALUE: src	 === REF!val!6
			VALUE: srcOfs	 === 2
			VALUE: i	 === 2
			VALUE: srcOfs + i	 === 4
			VALUE: src[srcOfs + i]	 === 80
			VALUE: dst[i] == src[srcOfs + i]	 === true

which again shows that dst and src are the same, which might make you realize the problem.
Hope this is helpful.

**Comment by davidcok** [comment]
Viktorio,

Last year I did a large industrial case study (proprietary so I can’t share it) — proving it with OpenJML and JML annotations.
It was a fair amount of work but overall successful.

What sort of work are you interested in applying this to. I’d be happy to collaborate if that is possible.

- David

**Comment by 0xD3ADBEEF** [comment]
> This one is a case of indices. It typically works better to have one index be a simple [k], as in this, which works for me:

Yes, I tried this before as well. Didn't initially work because I was missing the `requires src != dst`. Thank you very much for the feedback.

> As for debugging, that is definitely an art. I usually debug by putting in lots of assumes and intermediate asserts to sort out where the problem really lies and then slowly weed them out as I strengthen what ever was missing.

Aaah, yes, been in this situation before. Helps to know the insides of the tool I guess :) I suppose a different solver can also give better feedback. I remember back in the days the combo of SatAbs + NuSMV for C/C++ gave very detailed counterexample traces, and it helped a lot in the verification process. 

Speaking of which, as an extra side issue, I noticed that when running the tool from Eclipse with other solvers (e.g. yices2), then it doesn't run at all. 

>Last year I did a large industrial case study (proprietary so I can’t share it) — proving it with OpenJML and JML annotations.
It was a fair amount of work but overall successful.

>What sort of work are you interested in applying this to. I’d be happy to collaborate if that is possible.

Very nice to hear, and understandable about the case study. For now, I'd like to apply this out of pure interest and for educational purposes. Later on, the idea is to also apply it to large scale optimization algorithms deployed on servers.

**Comment by 0xD3ADBEEF** [comment]
Sorry if I'm turning this issue in a Q/A, but it seems hard to find a good discussion forum for JML questions. I only have three, which seem related to the original issue, after which I will close this issue :)

I have been trying to verify the following merge method, and succeeded after 2 days of fiddling:
``` java
/*@
requires 0 <= l && l < m && m < r && r <= arr.length && arr.length > 1; //bounds
requires (\forall int k; l <= k && k < m;(\forall int j; k < j && j < m; arr[k] >= arr[j]));
requires (\forall int k; m <= k && k < r;(\forall int j; k < j && j < r; arr[k] >= arr[j]));
ensures \forall int k;l<= k && k < r; ( \forall int j;k < j && j < r; arr[k] >= arr[j] );
@*/
private static void merge(/*@ non_null @*/ int [] arr, final int l, final int m, final int r) {
	final int [] lCpy = Arrays.copyOfRange(arr, l, m),
		         rCpy = Arrays.copyOfRange(arr,m, r);
		
	//@ assert \forall int k; 0 <= k && k < lCpy.length; lCpy[k] == arr[k+l];
	//@ assert \forall int k; 0 <= k && k < rCpy.length; rCpy[k] == arr[k+m];
	
	int l1 = 0, r1 = 0;
	/*@
	 loop_invariant 0 <= l1 && l1 <= lCpy.length;
	 loop_invariant 0 <= r1 && r1 <= rCpy.length;
	 loop_invariant l <= i && i <= r;
	 loop_invariant i == l+l1+r1;
	 loop_invariant l1 == lCpy.length ==> r1 <= rCpy.length;
	 loop_invariant r1 == rCpy.length ==> l1 <= lCpy.length;
	 loop_invariant \forall int k;l<= k && k < i;(\forall int j; l1 <= j && j < lCpy.length;arr[k] >= lCpy[j]);
	 loop_invariant \forall int k;l<= k && k < i;(\forall int j; r1 <= j && j < rCpy.length;arr[k] >= rCpy[j]);
	 loop_invariant \forall int k;l<= k && k < i; ( \forall int j;k < j && j < i; arr[k] >= arr[j] );
	 decreasing r - i;
	 @*/
	for(int i=l;i < r;i++) {
		if(l1 < lCpy.length && (r1 >= rCpy.length || lCpy[l1] >= rCpy[r1])) {
			arr[i] = lCpy[l1];
			l1++;
		} else {
			arr[i] = rCpy[r1];
			r1++;
		}
	}
}
```
First, the prover cannot verify the method, unless I include the invariants `loop_invariant l1 == lCpy.length ==> r1 <= rCpy.length;` and `loop_invariant r1 == rCpy.length ==> l1 <= lCpy.length;`. Any reason why?

Second, the method doesn't verify, unless I `assert \forall int k; 0 <= k && k < lCpy.length; lCpy[k] == arr[k+l];` and  `assert \forall int k; 0 <= k && k < rCpy.length; rCpy[k] == arr[k+m]`. Is it also related to the aliasing issue, or the contract of `copyOfRange` is not well defined yet?

Finally, the prover signals problem infeasible (unreachable state), if I replace `arr[i];i++` to `arr[i++]`. Is this related to the indexing issue discussed above?

**Comment by davidcok** [comment]
On #1) I don't have trouble proving this method without those two loop invariants. Note that the order of loop invariants can be important.

On #2) The library specs are OK. Since the asserts are proved, you know that the library specs are strong enough (if you had to assume them, then the specs would be too weak). asserts like this function as lemmas. That is, the prover can't make the complete deduction by itself, but it can prove these asserts and from these asserts prove the rest. I did not experiment, but I would guess it is because of indices again.

on #3) This is a bug. With the update to 'i' buried in the expression rather than explicit, the algorithm that infers what is changed in the loop (the inference of the loop_modifies) clause omits the 'I', which causes the infeasibility.  You can see this by adding the loop spec: loop_modifies I, l1, r1, arr[*]; and see that it then verifies.  I'll fix this or give a warning.

**Comment by davidcok** [comment]
PS. Note that you can write  0 <= l && l < m && m < r && r <= arr.length as 0 <= l < m < r <= arr.length; and similarly for the bounds within formal expressions.  If a bit more readable and writable.

Also this still proves if you have the precondition 0 <= l <= m <= r <= arr.length;

**Comment by 0xD3ADBEEF** [comment]
Yes, you are right for #1. It's very strange, because I could swear that it didn't work without those.

Thank you very much for the feedback, and appreciate the tips (especially the last one, really simplifies the syntax)!
