### ISSUE TITLE
Loop invariant don't have an effect

### ISSUE THREAD

**Issue by DacianGoina** [OpenJML/OpenJML#717]
Hi!

I try to check selection sort corectness for a project, I use JML with [this](http://aspectjml.cin.ufpe.br/#) tool.

Here is the implementation for selection sort, in Product.java
```
package figures;

public class Product {
        //@ requires A.length > 0;
        //@ ensures (\forall int i; i>=0 && i < A.length - 1; A[i] <= A[i+1]);
    	public static void selection(int A[]) { 
        int n = A.length; 
        //@ loop_invariant \forall int k; k >= 0 && k < i - 1; A[k] <= A[k+1]; 
        for (int i = 0; i < n-1; i++)
        { 
            //@ loop_invariant \forall int t; t >= i + 1 && t < A.length ; A[min_idx] <= A[t];
            int min_idx = i; 
            for (int j = i+1; j < n; j++) { 
                if (A[j] < A[min_idx]) 
                    min_idx = j; 
            }

            int temp = A[min_idx]; 
            A[min_idx] = A[i]; 
            A[i] = temp; 
        } 
    } 
}
```

And here is Main class, Main.java
```
package figures;
public class Main {

    public static void main(String[] args) {
        int B[] = {2,22,-1,3,8,9,1,4};
        Product.selection(B);
    }

}
```
The sorting work fine, but seems that loop_invariant don't have an effect: if I modify for example before the first **for** in something like this   //@ loop_invariant \forall int k; k >= 0 && k < i - 1; A[k] **==** A[k+1]; (== instead of <=)  the program still work fine(the sort still works), but the condition for loop_invariant aren't satisfied so JML should throw an exception but it doesn't do that.

How should I solve this? I I had a similar problem in the past @davidcok

**Comment by 0xD3ADBEEF** [comment]
I'm sorry in advance if I'm stealing the opportunity for @davidcok to answer, but I fiddle for quite long with sorting algorithms :) You seem to be missing additional bound invariants for the indices, and also each loop needs a `decreasing` clause to ensure termination of the loop. Here is my version of selection sort in descending order, which should be easy to adapt to ascending:

```java
/*@
 ensures \forall int k;0 <= k && k < arr.length-1;arr[k] >= arr[k+1];
 @*/
public static void sort(/*@ non_null @*/ int [] arr) {
	//@ ghost final int n = arr.length;
	
	//@ loop_invariant 0 <= i && i <= n; //Bounds check
	/*@ loop_invariant (\forall int j;0 <= j && j < i; //Sorted up-to i
		 		     (\forall int k;j < k && k < n;arr[j] >= arr[k]));
	@*/
	//@ decreasing n-i; //i goes up
	for(int i = 0;i < arr.length;i++) {
		int ub = arr[i];
		int l = i;
		
		//@ loop_invariant i < j && j <= n; //Bounds check
		//@ loop_invariant (\forall int k;i <= k && k < j;ub >= arr[k]); //max elem up-to j
		//@ loop_invariant i <= l && l < n; //max index bounds check
		//@ loop_invariant ub == arr[l]; //max index corresponds to max elem.
		//@ decreasing n-j; //j goes up
		for(int j = i+1;j < arr.length;j++) {
			if(arr[j] > ub) {
				l = j;
				ub = arr[j];
			}
		}
		// assert \forall int k; 0 <= k && k < i;largest <= arr[k];
		// assert \forall int k; i <= k && k < n;largest >= arr[k];
		
		arr[l] = arr[i];
		arr[i] = ub;
	}
}
```

**Comment by DacianGoina** [comment]
Hello @0xD3ADBEEF . I tried your method, I adapt it a bit:
`
public class AddLoop {
    //@ requires A.length > 1;
    //@ ensures (\forall int i;0 <= i && i < A.length - 1; A[i] >= A[i+1]);
    public static void sort(int A[]) {
	  int n = A.length;
	
	  //@ loop_invariant 0 <= i && i <= n - 1;
    //@ loop_invariant (\forall int k; 0 <= k && k <= i -1 ; A[k] >= A[k+1]); 
	  //@ decreasing n - i - 1; 
	for(int i = 0;i < n - 1;i++) {
		int max = A[i];
		int max_idx = i;
		
		//@ loop_invariant i < j && j <= n; 
		//@ loop_invariant (\forall int t; i<= t && t < j; max >= A[t]); 
		//@ loop_invariant i <= max_idx && max_idx < n; 
		//@ loop_invariant max == A[max_idx]; 
		//@ decreasing n - j; 
		for(int j = i+1;j < n ;j++) {
			if(A[j] > max) {
				max_idx = j;
				max = A[j];
			    }
		    }
		
		A[max_idx] = A[i];
		A[i] = max;
	    }
    }
}`

But when I run this in [OpenJML (ESC)](https://www.rise4fun.com/OpenJMLESC/) the solver provide an error:
    **The prover cannot establish an assertion (LoopInvariant) in method sort
    //@ loop_invariant (\forall int k; 0 <= k && k <= i -1 ; A[k] >= A[k+1]);   (at line 8)**

Why? How should I solve it?

**Comment by davidcok** [comment]
If you put 	//@ assert \forall int k; 0 <= k <= i-1; A[k] >= max;

At the end of the inner loop you will see that there is not enough information to prove the outer loop invariant you are asking about.
In particular, the outer loop invariant states that the first i elements are in decreasing order, but you also need an invariant that says that 
Those elements are all larger than the rest of the elements in the array

**Comment by 0xD3ADBEEF** [comment]
Like @davidcok  pointed out, the invariant `(\forall int j;0 <= j && j < i; (\forall int k;j < k && k < n;arr[j] >= A[k]));`, which can be shortened to `\forall int j,k;0 <= j < i && j < k < n;A[j] >= A[k];`, is stronger than `\forall int k; 0 <= k && k <= i -1 ; A[k] >= A[k+1]`. Something I was surprised about as well initially. In general i prefer `\forall int i,k; 0 <= i < j < A.length;A[i] >= A[j]` over `\forall int i; 0 <= i < A.length-1;A[i] >= A[i+1]` because of this reason.

**Comment by DacianGoina** [comment]
If I use **j**  in inner invariant  **\forall int j,k;0 <= j < i && j < k < n;A[j] >= A[k];** solver provide:  "variable j is already used". I tried to replace **j** with another variable **t** and now solver provide again **The prover cannot establish an assertion (LoopInvariantBeforeLoop) in method sort**.

This is what I have now:
```
public class AddLoop {
   //@ requires A.length > 1;
   //@ ensures (\forall int i;0 <= i && i < A.length - 1; A[i] >= A[i+1]);
   public static void sort(int A[]) {
	 int n = A.length;
	
	 //@ loop_invariant 0 <= i && i <= n - 1;
         //@ loop_invariant (\forall int k; 0 <= k && k <= i - 1 ; A[k] >= A[k+1]); 
	 //@ decreasing n - i - 1; 
 	  for(int i = 0;i < n - 1;i++) {
		  int max = A[i];
		  int max_idx = i;
		
		  //@ loop_invariant i < j && j <= n;  
                  //@ loop_invariant (\forall int t,k;0 <= t && t < i && t < k && k < n;A[t] >= A[k]);
		  //@ loop_invariant i <= max_idx && max_idx < n; 
		  //@ loop_invariant max == A[max_idx];
		  //@ decreasing n - j; 
		for(int j = i+1;j < n ;j++) {
			if(A[j] > max) {
				max_idx = j;
				max = A[j];
			    }
		    }
		
		A[max_idx] = A[i];
		A[i] = max;
	    }
    }
}

**Comment by davidcok** [comment]
That should be an invariant of the outer loop
