### ISSUE TITLE
OpenJML tool from rise4fun is out?

### ISSUE THREAD

**Issue by DacianGoina** [OpenJML/OpenJML#720]
Hello!

OpenJML from rise4fun isn't available anymore?
This link https://www.rise4fun.com/OpenJMLESC/ redirect me to rise4fun main page. I can't find OpenJML tool there.

**Comment by leavens** [comment]
Hi Dacian,

The rise4fun site periodically has such trouble.  It would be best to use https://www.openjml.org/ instead.

        Regards,

        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens  phone: +1-407-823-4758
        Leavens@ucf.edu<mailto:Leavens@ucf.edu>

**Comment by davidcok** [comment]
I have removed the link to Rise4Fun. We are working to restore service to the “Try Online” capability on the OpenJML site but do not plan to restore it on Rise4Fun

**Comment by davidcok** [comment]
rise4fun itself appears to be no longer supported.
