### ISSUE TITLE
RAC cannot detect postcondition violation in the following example 

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [OpenJML/OpenJML#721]
All three methods in the Absolute class have correct specifications, but all methods are buggy. 

However, when I run OpenJML's RAC using the attached JMLDriver.java, it does not show postcondition violation. (any inputs except zero should show postcondition violation). To run the JMLDriver, you should use command-line arguments with three inputs, like 

java -classpath ".:$OJ/jmlruntime.jar"  JMLDriver 3 3 3

Thanks in advance for your time.

[AbsoluteProblem.zip](https://github.com/OpenJML/OpenJML/files/6132243/AbsoluteProblem.zip)

**Comment by davidcok** [comment]
It doesn’t show postcondition violations because your driver program is not calling those buggy routines.
Note also that some violations will require -racCheckAssumptions to be used with -rac

**Comment by Amirfarhad-Nilizadeh** [comment]
Thank you so much for your help.

I rerun it, and it works perfectly. Also,  "-racCheckAssumptions" shows more violations, as you said, which was interesting to know.
