### ISSUE TITLE
Build Failed OpenJMLTest with ant

### ISSUE THREAD

**Issue by matifch** [OpenJML/OpenJML#729]
Hi,
I am new to OpenJML and facing a problem to build OpenJMLTest with ant. I cloned all the repositories of OpenJML .
The error is reported below, kindly advise.

ant -f build_OpenJMLTest.xml -Declipse.home=~/snap/tin/eclipse cleanall build OpenJMLTest 
Buildfile: /home/dr/openJML/OpenJML/OpenJMLTest/build_OpenJMLTest.xml

clean:

cleanall:

BUILD FAILED
/home/dr/openJML/OpenJML/OpenJMLTest/build_OpenJMLTest.xml:93: The following error occurred while executing this line:
Error reading project file /home/dr/openJML/JMLAnnotations/build_JMLAnnotations.xml: /home/dr/openJML/JMLAnnotations/build_JMLAnnotations.xml

Total time: 0 seconds

**Comment by davidcok** [comment]
Run the tests with the Eclipse launcher titled “OpenJMLTest - All”. The ant script is not up to date (though you are welcome to update it and send a PR). 
Note that a few tests may fail (some are occasionally nondeterministic)

- David

**Comment by davidcok** [comment]
This eclipse build environment is obsolete. OpenJDK now has a complicated build structure involving generated code and bootstrap builds. So closing this issue as 'will not be addressed'.
