### ISSUE TITLE
Jmlunit should make constructor problems into failures

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#73]
Problems in constructors and other code that creates 
objects for testing do not lead to failures in jmlunit 
generated code.  Currently, when there is a problem in 
creating test case objects during the creation of the 
test suite for jmlunit, the tools prints a stack backtrace, 
but testing continues and no failure or error is signaled.  
It would be better if these problems would cause 
failures.  The difficulty in the coding is that there is not 
yet a result object to add the failure to.  However, that 
can be overcome by saving up the exception objects 
that show the problem, and once the tests start 
running, processing these saved exception objects and 
turning them into failures.  This would affect the 
addTestSuiteForEachMethod that is printed in the 
_JML_Test.java files.  Instead of having blocks of code 
like: 

try {
this.addTestSuiteFor$TestJMLValueToValueMap
(overallTestSuite$);
} catch (java.lang.Throwable ex$) {
ex$.printStackTrace();
}

it would be better to store the exception object ex$ in 
some data structure.  Perhaps the easiest thing to do is 
to store it in the test suite itself as a test that will add 
the failure when run.

Original comment by: leavens

**Comment by linuxlovell** [comment]
thanks www.movied.org
