### ISSUE TITLE
Wrong process.exitValue (echo $?) by using RAC

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [OpenJML/OpenJML#731]
Hi,

When I run OpenJML's RAC using the attached JMLDriver.java with a wrong precondition, it shows the precondition violation as expected. However, it considers the process.exitValue (echo $?) equal to 0, which means the program ran with no violation.

Why "echo $?" is equal to zero? Is any problem with the driver?

Please run "runRac JMLDriver 1; echo $?"

[Test.zip](https://github.com/OpenJML/OpenJML/files/6524968/Test.zip)

**Comment by davidcok** [comment]
Hi - A RAC-enabled program that is configured to output warning messages about assertion violations will output the same exit code as the original program. That is, its behavior is intended to be the same except for the assertion violation reports.

You  can instead set options so that the program quits with an exception upon encountering an assertion violation (see the OpenJML User guide).

In either case, you can wrap the RAC-enabled program in a script wrapper that can detect and report any assertion violations through an exit code or environment variable.

- David

**Comment by leavens** [comment]
Hi David, Amirfarhad,

When I run this program it seems to work as I would expect

/home/leavens/temp/testing/Test$ java -version
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
/home/leavens/temp/testing/Test$ java Driver
Error: Could not find or load main class Driver
/home/leavens/temp/testing/Test$ ls
BankAccount.class  BankAccount.java  JMLDriver.class  JMLDriver.java
/home/leavens/temp/testing/Test$ java JMLDriver
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at JMLDriver.main(JMLDriver.java:4)
/home/leavens/temp/testing/Test$ echo $?
1


        Regards,

        Gary T. Leavens
        437D Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32916-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by Amirfarhad-Nilizadeh** [comment]
Hi David and Gary,

Thank you for your help. I get the process.exitValue 1 when I compile the program with -racPrecondition, which works perfectly. However, I found the same problem with postconditions in the following attached example. Also, I could not find any option in the OpenJML User guide that I can enable to get one by using process.exitValue when Postcondition and assertion violation happen.

If you compile the attached files and then run "runRac JMLDriver 2024; echo $?" then it shows postcondition violation, but the value of the process.exitValue is zero.

Thanks in advance for your time and consideration.

[LeapYearProblem.zip](https://github.com/OpenJML/OpenJML/files/6557030/LeapYearProblem.zip)

**Comment by davidcok** [comment]
I will repeat the same point I made before. The exit code of the program is what the program says the exit code should be; RAC does not change this — the exit code is not incorrect in this case.

If you want an alternate reporting mechanism, you can, as described in the user guide, use the -Dorg.jmlspecs.openjml.racexceptions   option. Then the program will abort with a stack trace upon encountering the first violation and, since it aborts, the exit code will be 1.

The exit code of 1 with -racPreconditionEntry is also because an exception is being thrown.

- David

**Comment by leavens** [comment]
Hi David,

Shouldn't the RAC throw an exception, which is uncaught?  Or is it that only with the -Dorg.jmlspecs.openjml.racexceptions option is the RAC throwing exceptions.


        Regards,

        Gary T. Leavens
        437D Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32916-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
The default behavior is just to print out a message on each detected assertion violation, but otherwise keep the original program’s behavior

With the -Dorg.jmlspecs.openjml.racexceptions option, an (uncaught) exception is thrown at the first assertion violation.

- David

**Comment by leavens** [comment]
Hi David,

OK, I see. This seems like a change from the old way of doing things, but I understand now.


        Regards,

        Gary T. Leavens
        437D Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32916-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
By ‘old’ you must mean pre-OpenJML.

Here is an alternative: enclose the body of main in a top-level try-catch that catches org.jmlspecs.utils.JmlAssertionError and run the tac-compiled program with the -Dorg.jmlspecs.openjml.racexceptions option

Then you can respond to the failed assertion in anyway you want — such as calling System.exit(42);

I could add a new option that causes the exit code to be non-zero in the default case.

- David

**Comment by leavens** [comment]
Hi David,

It seems that Amirfarhad's tests were getting those unhandled exceptions previously, but now they are not.

I think using the option should be sufficient.

        Regards,

        Gary T. Leavens
        437D Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32916-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by Amirfarhad-Nilizadeh** [comment]
Hi David and Gary,

Thank you for your responses. It is working as I need with "-Dorg.jmlspecs.openjml.racexceptions" option.

Thank you so much for your help and time.

**Comment by davidcok** [comment]
Resolved, including the ability to set the RAC-ed programs exit code to be either what the program wants or something else if a RAC violation occurs.
