### ISSUE TITLE
Internal error when calling Float.floatToIntBits()

### ISSUE THREAD

**Issue by garytho** [OpenJML/OpenJML#734]
If I run OpenJML's static checker on the following code involving `Float.floatToIntBits()`, I am notified of a catastrophic JML internal error with "Reason: No logical function for method <init>" and "Reason: MISMATCHED BLOCKS".

   public class FloatToIntBits
   {
      public static void floatToIntBits_test()
      {
         Float.floatToIntBits(1.5);
      }
   }

I also obtain this error when the input is a float (e.g. `1.5f`). I obtained the same error for every value of float and double I tested.

The command I used to call OpenJML was `java -jar openjml.jar -esc -verboseness 2 FloatToIntBits`
OpenJML's output is attached here ([output.txt](https://github.com/OpenJML/OpenJML/files/6611774/output.txt)). I ran this code on Ubuntu 20.04 on the bash shell.

**Comment by davidcok** [comment]
Already fixed in current sources.
