### ISSUE TITLE
just some videos

### ISSUE THREAD

**Issue by DvonHolten** [OpenJML/OpenJML#739]
folks,

this is not a complaint in the usual sense... no urgent need for code-changes.

recently, while searching for other things, i came across some YouTube videos about JML/ OpenJML etc, some of them quite fresh. Searching for Wolfgang Ahrendt brings up some papers too.
you may find more 

https://youtu.be/2JGdhKU7eIs
https://youtu.be/9ItK0jxJ0oQ
https://youtu.be/8Diq48PX3aA

https://www.key-project.org/

**Comment by davidcok** [comment]
Links added to documentation page at openjml.org
