### ISSUE TITLE
Jmlunit should have a verbose mode

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#74]
It would be nice if jmlunit supported a verbose mode, 
where one could have an output of what method's tests 
were being run.  This is could be triggered by a 
parameter that JMLTestRunner passes to the tests.  A 
possibility is to have tests inserted that, when a certain 
condition is true, succeed and print out the name of the 
method to be tested.

Original comment by: leavens

**Comment by linuxlovell** [comment]
thanks www.movied.org
