### ISSUE TITLE
Calling System.out.println in main method that calls a method with an assertion results in many spurious warnings

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#740]
I'm using
$ esc -version
openjml OpenJML-0.8.55-20210712
/home/leavens/temp/testing$ java -version
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

When I use ESC on the attached code, I get the following messages about specifications not passing that seem to be internal to JML's library specifications:

esc PrintProblem.java

PrintProblem.java:6: warning: The prover cannot establish an assertion (InvariantLeaveCaller: C:\cygwin64\usr\local\openjml\openjml.jar(specs/java/io/PrintStream.jml):34: ) in method main:  (Caller: PrintProblem.main(java.lang.String[]), Callee: java.io.PrintStream.println(java.lang.String))
        System.out.println("... test done.");
                          ^
C:\cygwin64\usr\local\openjml\openjml.jar(specs/java/io/PrintStream.jml):34: warning: Associated declaration: PrintProblem.java:6: 
    //-RAC@ public static invariant \invariant_for(eol) && eol.length() > 0;
                          ^

PrintProblem.java:6: warning: The prover cannot establish an assertion (InvariantLeaveCaller: C:\cygwin64\usr\local\openjml\openjml.jar(specs/java/io/PrintStream.jml):38: ) in method main:  (Caller: PrintProblem.main(java.lang.String[]), Callee: java.io.PrintStream.println(java.lang.String))
        System.out.println("... test done.");
                          ^
C:\cygwin64\usr\local\openjml\openjml.jar(specs/java/io/PrintStream.jml):38: warning: Associated declaration: PrintProblem.java:6: 
    //-RAC@ public invariant outputText != null && \invariant_for(outputText);
                   ^
4 warnings

See the files:
[PrintProblem.zip](https://github.com/OpenJML/OpenJML/files/7003305/PrintProblem.zip)

**Comment by davidcok** [comment]
The problem in this example is that test() has a default frame condition of 'assigns \everything' and consequently the invariants for System.out may no longer be established.

The example proves successfully if test() is specified as pure.  Test case added.
