### ISSUE TITLE
How to provide loop-invariants in external spec?

### ISSUE THREAD

**Issue by Elewyth** [OpenJML/OpenJML#742]
I am trying to create an external `.jml` file for a `.java` file, as so:

```java
// OpenJMLExternal.java
public class OpenJMLExternal {
    public static void copyArray(int[] b, int begin, int end, int[] a) {
        for (int k = begin; k < end; k++) {
            b[k] = a[k];
        }
    }
}
```

```java
// OpenJMLExternal.jml
public class OpenJMLExternal {
    /*@ requires a.length == b.length;
      @ requires begin >= 0 && begin < a.length && end >= 0 && end < a.length && begin <= end;
      @ ensures (\forall int k; begin <= k && k < end; a[k] == b[k]);
     */
    public static void copyArray(int[] b, int begin, int end, int[] a);
}
```

ESC fails with the following warnings:
```text
OpenJMLExternal.java:4: warning: The prover cannot establish an assertion (Postcondition: OpenJMLExternal.jml:6: ) in method copyArray
    public static void copyArray(int[] b, int begin, int end, int[] a) {
                       ^
OpenJMLExternal.jml:6: warning: Associated declaration: OpenJMLExternal.java:4:
      @ ensures (\forall int k; begin <= k && k < end; a[k] == b[k]);
        ^
OpenJMLExternal.java:6: warning: The prover cannot establish an assertion (PossiblyNegativeIndex) in method copyArray
            b[k] = a[k];
             ^
3 warnings
```

When writing spec directly in the `.java` file, I can solve these warnings by providing
```java
/*@ maintaining begin <= k && k <= end;
  @ maintaining (\forall int i; begin <= i && i < k; a[i] == b[i]);
  @ decreases end - k;
 */
```
at the top of the for-loop. How can I provide the `maintaining` and `decreases` for the loop from the external `.jml` file?

Thanks :)

**Comment by Elewyth** [comment]
Ah, I see, thank you for the quick response!

I wanted to try this approach, because in the JML Reference manual (https://www.cs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_17.html#SEC199) the following is written:

> Another reason for writing specifications in different files is to prevent the specifications from "cluttering up" the code (i.e., making it hard to see all of the code at once). This is also possible by using separate files for the specification and the code. The same technique of using a file with the same base name but with a `.jml' suffix works in such cases, as the specifications in the `.jml' file are added to the code in the `.java' file.

But if that is not (yet) supported by OpenJML, that's no problem for me. Thanks!

**Comment by davidcok** [comment]
But the quoted part is more or less accurate. Think of JML as consisting of two kinds of specifications

a) interface specs — e.g. method (requires, ensures…) and class (invariant, …) specifications. These can be extracted into a .jml file. These specs specify the behavior of a method — both what the implementation is verified against and what clients of the method use as descriptions of the method’s behavior

b) within-body specifications, such as ghost declarations, assert statements, and loop invariants. These are intermingled with the implementation in the body of a method and cannot be extracted into a .jml file. They are intended to aid the proof engine in verifying the method implementation (i.e., they serve as lemmas). Ideally they are not required, but at present loop invariants definitely are required.

- David
