### ISSUE TITLE
Model object collections need operations that use .equals 

### ISSUE THREAD

**Issue by openjml-project** [OpenJML/OpenJML#75]
To fix the bug in the JML specification of the
java.util collections, we need methods in
org.jmlspecs.models that allow the object collections
to compare elements using .equals.  I propose using a
set of operations like:

hasValue
insertValue
removeValue
valueEquals

etc.  These will be added to the object collection
types, like JMLObjectSet.

I am working on this at present...

Original comment by: leavens

**Comment by linuxlovell** [comment]
thanks www.movied.org
