### ISSUE TITLE
Problems with assignable and arrays

### ISSUE THREAD

**Issue by Elewyth** [OpenJML/OpenJML#757]
Hi, I am having troubles getting `assignable` to work properly, when the contents of an array should be assigned. Probably it's just me doing something wrong again, but I can't figure it out :(.

My minimal reproduction example:
```java
public class AssignableTest {
    //@ public invariant store.length == 1;

    //@ spec_public
    private final int[] store = new int[1]; //@ maps store[*] \into objectState;

    //@ assignable objectState;
    public void set(int value) {
        store[0] = value;
    }
}
```

The esc warning I get is
```
Starting proof of AssignableTest.set(int) with prover z3_4_3
AssignableTest.set Method assertions are INVALID
/opt/ws/src/main/java/AssignableTest.java:9: verify: The prover cannot establish an assertion (Assignable: /opt/ws/src/main/java/AssignableTest.java:7:) in method set: store[0]
        store[0] = value;
                 ^
/opt/ws/src/main/java/AssignableTest.java:7: verify: Associated declaration: /opt/ws/src/main/java/AssignableTest.java:9:
    //@ assignable objectState;
```

It works correctly, if I place `//@ assignable store[0];` or `//@ assignable store[*];` on `set`. But the way I understand, it should be possible to use a Data Group with a dynamic data group mapping for the contents of the array. I also simply tried `//@ in objectState;` with no difference.

In the end, I want to put the `//@ assignable objectState` on an interface, so I don't have access to the implementation's array. I was hoping I could map the array in the implementation into `objectState` and have it work that way. I can currently get it to work by putting `\\@ assignable \everything;` on the interface, but I would like to be more precise.

Tested with openjml 0.8.58 and 0.16.0-alpha-8. Both produce the same warnings.

Thanks in advance :).

**Comment by davidcok** [comment]
Which version of OpenJML?

**Comment by Elewyth** [comment]
I tested with both 0.8.58 and 0.16.0-alpha-8. Both give the same warnings in the example above.

**Comment by davidcok** [comment]
Thanks for this. And yes, maps has not yet been implemented. In fact it, along with other aspects of dynamic frames, is the current major implementation push -- though likely to only appear in the 16ff track.  And part of the rationale is precisely what you state -- to have data groups in interfaces that include elements of an array. So sorry to put you off for a while -- but it is coming.

**Comment by Elewyth** [comment]
Ah, I see. Thanks for the quick response!

**Comment by davidcok** [comment]
This example was made into a unit test. The problem was fixed sometime in the past.
