### ISSUE TITLE
Missing path variables when importing modules into IntelliJ

### ISSUE THREAD

**Issue by saiema** [OpenJML/OpenJML#760]
Hello, I want to see if I can improve how counterexamples are shown but I'm unable to import OpenJML into IntelliJ.

I'm following the instructions in [this page](https://github.com/OpenJML/OpenJML/wiki/OpenJML-Development-Environment-Setup)

Using IntelliJ I followed these steps

1. Import project from existing sources
2. Selected the OpenJML folder where I cloned all repositories (OpenJML, Specs, Solvers, and JMLAnnotations)
3. Selected Eclipse when asked to "import project from external model"
4. Selected all modules that appeared (shown in attached image)
5. Selected "default project code style" (I don't know which to choose)
6. Selected OpenJDK 16
7. Got two path variables without any associated value: PARENT-1-PROJECT_LOC and PARENT-2-PROJECT_LOC

I failed to find any declaration of those variables. I run the `bash ./configure` command, but those variables are not declared, also tried with `make openjml` but again those variables are not declared anywhere. 

![Screenshot from 2022-01-11 16-41-10](https://user-images.githubusercontent.com/4238210/149010281-b4c0f746-d275-4a63-b9fb-4cb8bc754c1e.png)

**Comment by davidcok** [comment]
the page you cite is for setting up the development environment. however no work has yet been done on set up for developing in either Eclipse or IntelliJ. OpenJDK has a custom build environment with non-Java components that may prove challenging for either IDE. If you have any success, please let me know.

**Comment by saiema** [comment]
> the page you cite is for setting up the development environment. however no work has yet been done on set up for developing in either Eclipse or IntelliJ. OpenJDK has a custom build environment with non-Java components that may prove challenging for either IDE. If you have any success, please let me know.

Thanks for the quick reply, I understand. Could you give me a pointer as to what those two variables should point to?

**Comment by davidcok** [comment]
Sorry - those don't show up in the source project at all. The just be IntelliJ variables. Not having set up any IntelliJ projects, I don't know what they should be.

**Comment by davidcok** [comment]
Closing this as there is no support for IntelliJ
