### ISSUE TITLE
OpenJML postcondition (and loop invariant) contains class method call

### ISSUE THREAD

**Issue by Negar-Sabour** [OpenJML/OpenJML#764]
Hi there, 

I would like to call a class method in the postcondition (and loop invariant) of another method. I have searched and the most relevant thing that I have found was [this](https://stackoverflow.com/questions/13602989/jml-postcondition-contains-class-method-call) post in StackOverflow.

I tried to open the link which was provided there (http://www.ibm.com/developerworks/java/library/j-jml/index.html); however, it doesn't work anymore. 
1-	Is there any (other) resource that I can find “how to call a class method in postcondition of the other function”?

2-	Once I tried to test the example at [this](https://stackoverflow.com/questions/13602989/jml-postcondition-contains-class-method-call)  in OpenJML, I received an error for static verification:
 
![image](https://user-images.githubusercontent.com/74606728/154760373-befc9453-fc27-4305-9f64-beb28fddb4f2.png)

Just I was able to use runtime assertion checking for this example:
 
![image](https://user-images.githubusercontent.com/74606728/154760487-341bb709-5e47-4db2-b244-d27f3d545d6d.png)

Any help would be appreciated regarding calling a method in postcondition in static verification (or runtime assertion).
Thank you
 
-- I am using openjml 0.17.0-alpha-9 on ubuntu 20.04.

**Comment by davidcok** [comment]
What you are doing is partially correct. doA is pure so it is allowed to be called in the postcondition. 

However, you have not given doA any postconditions of its own, so the prover does not know what it produces.
Give it //@ ensures \result == 1; and all works well.

**Comment by Negar-Sabour** [comment]
Thanks a lot for your time. 
(1) Please correct me if I am wrong: If I don't provide the postcondition for the calle function (doA), then I couldn't expect that I could call it in postcondition of other methods in static verification.

(2) Sorry the function that is called inside the precondition of the other function, Should be "pure"? or for example it is enough to just be "helper" function. 
(3) I tried to figure it out by removing pure for doA() and then I get the warning:
![image](https://user-images.githubusercontent.com/74606728/154776247-f9dd9998-eb10-4643-8ddd-55bfc6bc556a.png)

(4) for trying the helper function, I tried :
![image](https://user-images.githubusercontent.com/74606728/154775756-ccea7d82-8eda-4ea2-8405-9b738c4cad9a.png)

but didn't receive error as I expected as it is neither private nor pure. So I am thinking I don't use "helper syntax" notation correctly.

--------------------------------------------------------------------------------------
-- (5) Here is one more general question that I would be more than thankful if you could give me some suggestions: 
I am new to OpenJML and JML and willing to learn more about OpenJML. Right now I have only these 3 resource:
1) https://www.openjml.org/tutorial/ (Draft)
2) https://www.openjml.org/examples/ 
3) [JML Reference Manual](https://www.openjml.org/documentation/JML_Reference_Manual.pdf) and the [OpenJML Reference Manual](https://www.openjml.org/documentation/OpenJMLUserGuide.pdf) (Drafts)
4) [JML Reference Manual](https://www.cs.ucf.edu/~leavens/JML/refman/jmlrefman.pdf)

I am a bit confused as I don't know which JML features are supported in OpenJML. and also I wish I could find some simple examples like the ones available at https://www.openjml.org/tutorial/  for other JML features that are supported by OpenJML (for instance for helper function).

Kind regards,
Negar

**Comment by davidcok** [comment]
1) A function must be pure to be used in a specification.
2) You can call a method without its own specification, but you won't be able to prove very much
3) 'helper' has to do with invariants and is not relevant here
4) Those are the relevant resources. As you note all this documentation is in draft as we are doing a major rewrite and upgrade. I'll push updated drafts this weekend if I have some time.

**Comment by Negar-Sabour** [comment]
Thank you so much for all your efforts and care.

Best regards,
Negar

**Comment by davidcok** [comment]
Negar - I should have clarified with a bit more explanation.
The reason that OpenJML does not know that the two invocations of doA are equal is that they are called with different arguments, x and y, which may well have different values. If you called doA twice with the same argument, or even added a precondition to doB that constrains x and y to be equal, such as `//@ requires y <= x <= y;`, then your example will verify without having to add any specifications to doA. With `x == y`, OpenJML knows that `doA(x) == doA(y)` even if it does not know what the value of `doA(x)` is. 

I hope that aids your understanding.

**Comment by Negar-Sabour** [comment]
Thanks for the clarification. I appreciate it.

**Comment by davidcok** [comment]
Resolved as not a problem. Test case added to test suite to be sure it stays working as expected.
