### ISSUE TITLE
error: A catastrophic JML internal error occurred (using javax.crypto.Mac)

### ISSUE THREAD

**Issue by Negar-Sabour** [OpenJML/OpenJML#775]
Hi,

The Verification of f0  `( openjml -esc test6.java -method="f0")` results in a catastrophic error. The complete error message is attached (result.txt). 
However, verifying  f1  `( openjml -esc test6.java -method="f1")`  terminates normally. 

import java.security.NoSuchAlgorithmException;

import javax.crypto.Mac;

public class test6 {
	

	public void f0() {
		try {
			Mac sha256Hmac = Mac.getInstance("HmacSHA256");
		} catch (NoSuchAlgorithmException  e) {
			e.printStackTrace();
		}
	}
	
	
	public void f1() throws NoSuchAlgorithmException {

		Mac sha256Hmac = Mac.getInstance("HmacSHA256");
	
	}
    
}

-- I am using openjml 0.17.0-alpha-9 on ubuntu 20.04.

Regards, 
Negar

[result.txt](https://github.com/OpenJML/OpenJML/files/8758606/result.txt)

**Comment by Negar-Sabour** [comment]
Also once running `openjml -esc test6.java -method="f2"` another catastrophic error happened. The complete error is available at result2.txt.
`	public static void f2(byte[]  inputTextVal, byte[] key) throws NoSuchAlgorithmException, InvalidKeyException {

			Mac sha256Hmac = Mac.getInstance("HmacSHA256");

			SecretKeySpec keySpec = new SecretKeySpec(key, "HmacSHA256");

			sha256Hmac.init(keySpec);



	}
	`
This will be removed once removing the highlighted line in Mac.jml

![image](https://user-images.githubusercontent.com/74606728/169924598-4fea26cb-775a-4dda-951f-f404dfa1f5db.png)


[result2.txt](https://github.com/OpenJML/OpenJML/files/8758678/result2.txt)

Regards,
Negar

**Comment by davidcok** [comment]
I reproduced these errors on version alpha-9, but they are all fixed in the current release, 0.17.0-alpha-14

**Comment by Negar-Sabour** [comment]
Thanks David.
