### ISSUE TITLE
Object.equals in Postcondition: symbol not found

### ISSUE THREAD

**Issue by itlchriss** [OpenJML/OpenJML#779]
Hello,

I am writing a spec for the Java.util.Arrays.deepEquals.
One of the condition in the Java documentation states that two corresponding elements e1 and e2 from the input arrays are considered equal if e1.equals(e2).
However, when I try to write this in the postcondition, it returns symbol not found.
The following is my method with the postcondition:

```java
    //@ ensures (((\forall int i; 0 <= i < a1.length; ((a1[i] == null && a2[i] == null) || (a1[i] ==a2[i]) || a1[i].equals(y[i]))) && (a1.length==a2.length)) ==> (\result==true));
    public boolean deepEquals(Object[] a1, Object[] a2) {
        return Arrays.deepEquals(a1, a2);
    }
```

Error is:
DeepEquals.java:38: error: cannot find symbol
    //@ ensures (((\forall int i; 0 <= i < a1.length; ((a1[i] == null && a2[i] == null) || (a1[i] ==a2[i]) || a1[i].equals(y[i]))) && (a1.length==a2.length)) ==> (\result==true));
                                                                                                                           ^
  symbol:   variable y
  location: class DeepEquals
1 error

**Comment by davidcok** [comment]
What is y? It is not declared in the program text you included. I suspect it should be a2.
Also the comparison of lengths ought to precede the forall.
Also I don't see a definition of Arrays.deepEquals. -- Did you write one?
Also, Object.equals is not necessarily pure. Although it is specified that way at the moment, that specification is deprecated and will change soon.

**Comment by itlchriss** [comment]
Thanks for the reply.
I have corrected the symbol y as a2.
The error becomes:
```
DeepEquals.java:38: error: cannot find symbol
    //@ ensures (((\forall int i; 0 <= i < a1.length; ((a1[i] == null && a2[i] == null) || (a1[i] ==a2[i]) || (a1[i].equals(a2[i])) || (a1.getClass().isArray() && a1.getClass().isArray() && Arrays.Equals(a1,a2)))) && (a1.length==a2.length)) ==> (\result==true));
                                                                                                                                                                                                    ^
  symbol:   method Equals(Object[],Object[])
  location: class Arrays
1 error
```
- The definition of Arrays.deepEquals is in the Java.util.Arrays
In the above error, the pointer points to the Arrays.Equals which is an API from Java.util.Arrays.
I have imported Java.util.Arrays in the source code.
Is it valid to use Java APIs in this way with OpenJML?

**Comment by davidcok** [comment]
- There is no Arrays.Equals, but there is a method Arrays.equals (which also should not be considered pure when applied to Object arrays)
- Regarding Arrays.deepEquals, I should have said there is no JML specification as yet and it should not be used with a specification.
- Java APIs may only be used within JML specs if there are pure (have no side effects)

**Comment by itlchriss** [comment]
Thank you very much. 
Your reply has solved all my questions regarding this issue.
