### ISSUE TITLE
*/ not parsed correctly, if occurring within line comment nested inside JML block specification

### ISSUE THREAD

**Issue by ArmborstL** [OpenJML/OpenJML#787]
In the following example, the JML block specification is ended by a `*/` inside a line comment:
```java
class T {
  /*@ requires true;
      // commented out: ensures false; */
  void m() {}
}
```
This should parse and verify, i.e. the `*/` should indeed end the block comment/specification. 

Instead, I get _"error: A method or type declaration within a JML annotation must be model"_ for the `void m()` method. 
Or (in variations of the code above) I get _"Expected a declaration or a JML construct inside the JML annotation here"_. 
Clearly, the OpenJML parser does not recognise the `*/` as the end of the JML annotation.

This happened on OpenJML version 0.8.59 as well as 0.17.0-alpha-15.

Putting the `*/` on a new line solves the issue.

Note that e.g. `javac` (Version 11) has no problem compiling this code, i.e. it is valid Java.

**Comment by davidcok** [comment]
There is a workaround -- be sure that the */ is on the next line

**Comment by ArmborstL** [comment]
Indeed. So the issue doesn't have high priority, I mostly raised it for documentation purposes.

**Comment by davidcok** [comment]
Fixed this with a recent push to current dev-21
