### ISSUE TITLE
Internal JML bug 

### ISSUE THREAD

**Issue by Negar-Sabour** [OpenJML/OpenJML#790]
Hi,
I received an error message that says "Internal JML bug". A simple example that caused the error is attached. I used the following command, which produced the error message: "openjml -esc ClassA.java -cp "../" > error.txt". The error message will be disappeared if line 3 in "ClassA.java" is uncommented.

I hope this information is helpful for troubleshooting the issue. 

[java.zip](https://github.com/OpenJML/OpenJML/files/10770434/java.zip)

------------------
OpenJML: 0.17.0-alpha-15
Ubuntu 20.04

**Comment by davidcok** [comment]
Thanks for the report. Reproduced with current OpenJML 21. Made it a test and will investigate.

**Comment by davidcok** [comment]
Fixed in V21-0.3
