### ISSUE TITLE
Error Message: "Solver has unexpectedly terminated"

### ISSUE THREAD

**Issue by marcel139** [OpenJML/OpenJML#792]
I faced a problem in static verifying (--esc) the file below which is a solution for question 2 in https://www.openjml.org/tutorial/exercises/AssertExKey.html.
However, I get the following error message: "error: An error while executing a proof script for primeChecker: (error "Solver has unexpectedly terminated")".

Any thoughts on how to sort this out?

```
public class Cap_02_3_Assert_Q2_s {
    //@ ensures \result <==> !(\exists int i; 2 <= i < num; num % i == 0);
    public boolean primeChecker(int num) {
        boolean isPrime = true;
        if (num < 2) {
            isPrime = false;
        } else {
            //@ show num, isPrime;
            //@ maintaining 0 <= i <= (num/2) + 1;
            //@ maintaining isPrime <==> !(\exists int k; 2 <= k < i; num % k != 0);
            //@ loop_writes i, isPrime;
            //@ decreases num - i;        
            for (int i = 2; i <= num / 2; i++) {
                //@ assume i > 0;
                if (num % i == 0) {
                    //@ assert num % i == 0;
                    isPrime = false;
                    //@ assert isPrime == false;
                }
            }
        } 
        return isPrime;
    }   
}   
```

**Comment by leavens** [comment]
Hi Marcel and all,

When I try this example, ESC goes into an infinite loop...  This is with OpenJML 0.17.0-alpha-15 on Ubuntu (22) running under WSL2...


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

From: marcel139 ***@***.***>
Sent: Thursday, February 23, 2023 12:58 PM
To: OpenJML/OpenJML ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenJML/OpenJML] Error Message: "Solver has unexpectedly terminated" (Issue #792)


I faced a problem in static verifying (--esc) the file below which is a solution for question 2 in https://www.openjml.org/tutorial/exercises/AssertExKey.html<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.openjml.org%2Ftutorial%2Fexercises%2FAssertExKey.html&data=05%7C01%7CLeavens%40ucf.edu%7Cb40d52e33e2341bc813808db15c777c9%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C638127718671706725%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nZvub4yCpg9%2Buk9AzJqDG6Oh35YMUfGyfASq%2Bc5nTsg%3D&reserved=0>.
However, I get the following error message: "error: An error while executing a proof script for primeChecker: (error "Solver has unexpectedly terminated")".

Any thoughts on how to sort this out?

public class Cap_02_3_Assert_Q2_s {

    //@ ensures \result <==> !(\exists int i; 2 <= i < num; num % i == 0);

    public boolean primeChecker(int num) {

        boolean isPrime = true;

        if (num < 2) {

            isPrime = false;

        } else {

            //@ show num, isPrime;

            //@ maintaining 0 <= i <= (num/2) + 1;

            //@ maintaining isPrime <==> !(\exists int k; 2 <= k < i; num % k != 0);

            //@ loop_writes i, isPrime;

            //@ decreases num - i;

            for (int i = 2; i <= num / 2; i++) {

                //@ assume i > 0;

                if (num % i == 0) {

                    //@ assert num % i == 0;

                    isPrime = false;

                    //@ assert isPrime == false;

                }

            }

        }

        return isPrime;

    }

}

-

**Comment by marcel139** [comment]
That is probably why the OS is terminating my process. @davidcok could you investigate this internally?

**Comment by davidcok** [comment]
Closing this as the same issue is reported in #802.
