### ISSUE TITLE
Could not run OpenJML in Windows

### ISSUE THREAD

**Issue by lhf552004** [OpenJML/OpenJML#795]
Hi, I cannot run the OpenJML on my laptop. Could someone help me?
My environment is 
Windows 11
Java 8

I also tried Java 16, but It doesn't work.
This is the installation path
![image](https://user-images.githubusercontent.com/10030850/222854023-85b8a3ac-5f4c-4ac9-9de8-a74e6e36400c.png)
This is my path environment
![image](https://user-images.githubusercontent.com/10030850/222854158-685d1492-9409-4b2e-934d-8de2595099f8.png)

Thanks

**Comment by davidcok** [comment]
There is not a pure Windows build. Try running within WSL.

**Comment by lhf552004** [comment]
@davidcok Thanks sir. I will try it

**Comment by lhf552004** [comment]
@davidcok . I tried to install openJMl in ubuntu. 
However, it still has the error:
_Invalid or corrupt jarfile openjml_
![image](https://user-images.githubusercontent.com/10030850/225621225-49062795-4175-4248-9f47-6b876bae0872.png)

**Comment by davidcok** [comment]
There is no pure windows build. Use WSL.

**Comment by davidcok** [comment]
Sorry - this was on ubuntu? But it appears you are using Java 8, rather than Java 16 or 17.

**Comment by davidcok** [comment]
Also, there is an openjml executable script -- you should run that directly.

**Comment by lhf552004** [comment]
Hi, I tried to run the script. But it said no this command. Is there any configuration to do?
![image](https://user-images.githubusercontent.com/10030850/225626229-74ad594b-802e-494c-8c38-8a1cf39f742e.png)

**Comment by davidcok** [comment]
Download the zip file, unzip it somewhere and run the openjml file you find in it. Possibly you have to set its permissions to executable.

**Comment by lhf552004** [comment]
I finally ran it successfully in ubuntu. Thanks
