### ISSUE TITLE
Using PrintStream.println(double) Breaks the Invariant

### ISSUE THREAD

**Issue by marcel139** [OpenJML/OpenJML#796]
In the code below, if I only uncomment the `FAILS` section in the `main` method I get an `InvariantLeaveCaller` when invoking `dpt.set(2.0)`. However, if I only uncomment the `SUCCEEDS` block the verification succeeds.

I noticed that the specification in **PrintStream.jml** of `public void println(double Param0);` has no JML annotation, whilst, for strings, we have `public void println(/*@ nullable */String s);` fully annotated. 

Two questions:

1) Is it correct to assume that the fact that there is no JML annotation in the first one make its specification `assigns \everything` and this is the reason why the invariant is being broken?

2) What would be the nicest way to solve this? I believe that it would be to have the correct specification of `public void println(double Param0);` in **PrintStream.jml**. Correct?

```
public class DoublePrintTest {

    //@ spec_public
    private double value;

    //@ public invariant value >= 0.0;

    //@ requires d >= 0.0;
    //@ ensures value == d;
    //@ pure
    public DoublePrintTest (double d) { this.value = d; }

    //@ requires d >= 0.0;
    //@ assigns value;
    //@ ensures value == d;
    public void set (double d) { this.value = d; }

    public static void main(String [] argv) {
        DoublePrintTest dpt = new DoublePrintTest(0.0);

        // FAILS
        /*
        System.out.println(0.0);
        dpt.set(2.0);
        */

        // SUCCEEDS
        /*
        double d = 0.0;
        String s = "" + d;
        System.out.println(s);
        dpt.set(2.0);
        */

    }
}
```

**Comment by davidcok** [comment]
Correct on both counts. Fully annotating the library is a big task. We're clearly not there yet.

**Comment by marcel139** [comment]
Thanks for you reply, David.
