### ISSUE TITLE
A Large Set of Examples (Available)

### ISSUE THREAD

**Issue by marcel139** [OpenJML/OpenJML#800]
In the following link, I provide a large set of examples:

https://www.dropbox.com/s/yvddtb7inh1v2y2/JML.zip?dl=0

They are originally from the OpenJML tutorial (thanks @davidcok) and @leavens 2007 tutorial:

- The folders tutorial/examples and tutorial/exercises contain examples and solutions to the exercises available at the OpenJML tutorial (some of them adapted from the website to actually work) 
- The folder ajml/examples contains adaptations of the examples provided in the 2007 tutorial teached by @leavens 

Two important considerations:

1. The file tutorial/exercises/Cap_02_3_Assert_Q2_s.java is not working; its verification causes the Error Message: "Solver has unexpectedly terminated" (Issue https://github.com/OpenJML/OpenJML/issues/792)
2. The file ajml/examples/SortedInts3.java works, but lines 6, 13 and 27 are not being verified (commented) because I faced problems using the keyword "owner" (Issue https://github.com/OpenJML/OpenJML/issues/797)

**Comment by davidcok** [comment]
Please log issues for examples in the documentation that do not actually work.

**Comment by marcel139** [comment]
The vast majority of them worked as they are presented in the documentation
(excellent documentatio by the way). I would be happy to log issuea for
them, but unfortunately, I didn't registered which ones needed some work :-(

Em qua., 8 de mar. de 2023 21:26, David Cok ***@***.***>
escreveu:
