### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by bzp99** [OpenJML/OpenJML#803]
We would like to use OpenJML to support runtime verification of [Hyperledger Fabric](https://www.hyperledger.org/use/fabric) smart contracts.

I have been experimenting with building chaincode (= smart contract in Fabric) with OpenJML, but I am having trouble determining Java version compatibility. Do I understand correctly that the latest _stable_ version of OpenJML is [v0.8.59](https://github.com/OpenJML/OpenJML/releases/tag/0.8.59) and it supports only Java 8 and then there are _alpha_ versions like [0.17.0-alpha-15](https://github.com/OpenJML/OpenJML/releases/tag/0.17.0-alpha-15) for Java 17?

I have initially tried with the very latest release found here, but ran into a plethora of problems (I might be able to open issues for them later), so I quickly downgraded to 0.8.59.

**Comment by davidcok** [comment]
You should consider the 0.17.0-alpha sequence as the current supported version, which works on MacOS up through OS11. I hope to fix the build process for OS12 this summer..

Are you intending just to *use* OpenJML or to you need to *modify and build* it?

**Comment by bzp99** [comment]
Thanks for the prompt response! This is certainly good to know; I will go ahead and try again with the latest `0.17.0-alpha-*` version then. I am using Ubuntu inside Docker though, but I don’t think that will be a problem.

We only indent to _use._ The plan is to define JML constraints over a Java implementation of the [TPC-C](https://www.tpc.org/tpcc/) as Fabric chaincode.

I am going to see if I can get things working with the latest version and if anything comes up, I’ll just open a separate issue for it. Thanks!
