### ISSUE TITLE
Java heap space exception

### ISSUE THREAD

**Issue by itlchriss** [OpenJML/OpenJML#804]
Hi,

I am working in using OpenJML with Z3 on verifying a large program. As far as I know, Java has an option Xmx for increasing the runtime heap size. However, I don't find the corresponding option in OpenJML. May I know which option and what is the syntax of using the option?

Thanks,
Chriss IT. Leong

**Comment by davidcok** [comment]
OpenJML is a replacement for javac, not java.
The -Xmx option affects the heap space for a running Java program. Execute `java -X` to see help information on -Xmx and other -X type Java options. You will see the same options if you run `openjml-java -X`.

This is relevant to OpenJML if you (a) compile a Java program using runtime-assertion checking (`openjml --rac ...`) 
and then (b) want to run the program using either `java` or `openjml-java`. The -Xmx option applies to the second step.
