### ISSUE TITLE
yices support in version 0.17-alpha-15 

### ISSUE THREAD

**Issue by itlchriss** [OpenJML/OpenJML#808]
Hi,

    I tried to use yices 2.6 with the OpenJML version 0.17-alpha-15. My environment is a Macbook with M1, I have yices2 installed. However, it kept failing to initiate the proving, detail is attached in the following:

../openjml-0.17-a15/openjml -esc ./build/RandomForest.java -specs-path ./build -ce --prover=yices -progress --exec=/opt/homebrew/Cellar/yices2/2.6.4_1/bin/yices
Proving methods in RandomForest
Starting proof of RandomForest.RandomForest() with prover yices
(error "Failed to start process /opt/homebrew/Cellar/yices2/2.6.4_1/bin/yices : Stream closed")
error: Error occurred while attempting proof: (error "Failed to start process /opt/homebrew/Cellar/yices2/2.6.4_1/bin/yices : Stream closed")
(error "yices failed to start: Failed to start process /opt/homebrew/Cellar/yices2/2.6.4_1/bin/yices : Stream closed")
Completed proof of RandomForest.RandomForest() with prover yices - ERROR [1.54 secs]
Starting proof of RandomForest.randomForest(double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double) with prover yices

**Comment by davidcok** [comment]
Correct - only z3 is currently supported.

**Comment by itlchriss** [comment]
Thank you very much for the prompt reply!
