### ISSUE TITLE
Find Files in Projects with Various Dependencies

### ISSUE THREAD

**Issue by marcel139** [OpenJML/OpenJML#810]
I have a maven project with many (around 50) dependencies to jar files, which are all in the same directory. Unfortunately, I have not found a way to use --class-path refering only to the root directory that contains all the jar files. Apparently, I will have to include each of the jar files to this option. Is that really so, or am I missing some easier way to refer to many jar files at once?

**Comment by davidcok** [comment]
You can use a wild-card in the classpath. cf https://stackoverflow.com/questions/1237093/how-to-use-a-wildcard-in-the-classpath-to-add-multiple-jars
