### ISSUE TITLE
Documentation page "Commit Eclipse Package to our SVN" is obsolete and has broken links

### ISSUE THREAD

**Issue by leavens** [OpenJML/OpenJML#813]
The web page on the Wiki titled "Commit Eclipse Package to our SVN" (https://github.com/OpenJML/OpenJML/wiki/Commit-Eclipse-Package-To-Our-SVN) is obsolete, as we are no longer using SVN, and some of the links are broken. Perhaps the entire page should be deleted?

**Comment by davidcok** [comment]
Deleted.
