### ISSUE TITLE
 Crash in converting BasicPrograms to SMTLIB

### ISSUE THREAD

**Issue by pys** [OpenJML/OpenJML#814]
.. second attempt:
First the error messages (at the end):
-----
/Users/pys/src/openjml-jun22/openjml -esc ~/src/IdeaProjects/jan24/src/BinaryTree.java
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:135: warning: A non-pure method is being called where it is not permitted: java.util.Set.<E>of(E)
    @ ensures Set.of(\result).equals(this.keySet().subSet(a,false,b,false));
                    ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:135: warning: A non-pure method is being called where it is not permitted: java.util.TreeSet.subSet(E,boolean,E,boolean)
    @ ensures Set.of(\result).equals(this.keySet().subSet(a,false,b,false));
                                                         ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:147: warning: A non-pure method is being called where it is not permitted: java.util.Set.<E>of(E)
    @ensures Set.of(\result).equals(Node.ks(n).subSet(a,false,b,false));
                   ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:147: warning: A non-pure method is being called where it is not permitted: java.util.TreeSet.subSet(E,boolean,E,boolean)
    @ensures Set.of(\result).equals(Node.ks(n).subSet(a,false,b,false));
                                                     ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:89: verify: The prover cannot establish an assertion (Assignable: /Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:86:) in method allNullAtNearlySameLevel: \everything
        return depthOfNull(root).size() <= 1;
                          ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:86: verify: Associated declaration: /Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:89:
     pure @*/
     ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:89: verify: The prover cannot establish an assertion (PossiblyNullDeReference) in method allNullAtNearlySameLevel
        return depthOfNull(root).size() <= 1;
                                ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:89: verify: The prover cannot establish an assertion (Postcondition: /Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:84:) in method allNullAtNearlySameLevel
        return depthOfNull(root).size() <= 1;
        ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:84: verify: Associated declaration: /Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:89:
    /*@ ensures \result == (\exists int n;  n >= 0;
        ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:138: verify: The prover cannot establish an assertion (Postcondition: /Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:135:) in method between
        return btw(root, a, b);
        ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:135: verify: Associated declaration: /Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:138:
    @ ensures Set.of(\result).equals(this.keySet().subSet(a,false,b,false));
      ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:150: verify: The prover cannot establish an assertion (Postcondition: /Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:147:) in method btw
        if (n == null) return new int[0];
                       ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:147: verify: Associated declaration: /Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:150:
    @ensures Set.of(\result).equals(Node.ks(n).subSet(a,false,b,false));
     ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:156: verify: The prover cannot establish an assertion (PossiblyNullDeReference) in method btw
        int[] r = Arrays.copyOf(r1, r1.length + 1 + r2.length);
                                      ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:156: verify: The prover cannot establish an assertion (PossiblyNullDeReference) in method btw
        int[] r = Arrays.copyOf(r1, r1.length + 1 + r2.length);
                                                      ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:156: verify: The prover cannot establish an assertion (ArithmeticOperationRange) in method btw: overflow in int sum
        int[] r = Arrays.copyOf(r1, r1.length + 1 + r2.length);
                                              ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:156: verify: The prover cannot establish an assertion (Precondition: /Users/pys/src/openjml-jun22/specs/java/util/Arrays.jml:1918:) in method btw
        int[] r = Arrays.copyOf(r1, r1.length + 1 + r2.length);
                               ^
/Users/pys/src/openjml-jun22/specs/java/util/Arrays.jml:1918: verify: Associated declaration: /Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:156:
    public static int[] copyOf(int /*@ nullable @*/ [] original, int newLength);
                        ^
/Users/pys/src/openjml-jun22/specs/java/util/Arrays.jml:1908: verify: Precondition conjunct is false: newLength >= 0
    //@   requires newLength >= 0;
                             ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:156: verify: The prover cannot establish an assertion (ArithmeticOperationRange) in method btw: overflow in int sum
        int[] r = Arrays.copyOf(r1, r1.length + 1 + r2.length);
                                                  ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:159: verify: The prover cannot establish an assertion (PossiblyNegativeIndex) in method btw
            r[r1.length + 1 + i] = r2[i];
             ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:159: verify: The prover cannot establish an assertion (PossiblyNegativeIndex) in method btw
            r[r1.length + 1 + i] = r2[i];
                                     ^
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: This node should not be present in converting BasicPrograms to SMTLIB: class com.sun.tools.javac.tree.JCTree$JCFieldAccess /*missing*/.this$encl_55_55___25
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:120: verify: The prover cannot establish an assertion (PossiblyNullInitialization) in method depthOfNull: ileft
        /*@ non_null */Interval ileft = depthOfNull(n.left);
                                ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:122: verify: The prover cannot establish an assertion (ArithmeticOperationRange) in method depthOfNull: overflow in int sum
        return new Interval(1 + Math.min(ileft.min, iright.min), 1 + Math.max(ileft.max, iright.max));
                              ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:121: verify: The prover cannot establish an assertion (PossiblyNullInitialization) in method depthOfNull: iright
        /*@ non_null */Interval iright = depthOfNull(n.right);
                                ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:122: verify: The prover cannot establish an assertion (ArithmeticOperationRange) in method depthOfNull: overflow in int sum
        return new Interval(1 + Math.min(ileft.min, iright.min), 1 + Math.max(ileft.max, iright.max));
                                                                   ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:108: verify: The prover cannot establish an assertion (ArithmeticOperationRange) in method size: overflow in int sum
            if (max >= min) return max - min + 1;
                                             ^
/Users/pys/src/IdeaProjects/jan24/src/BinaryTree.java:108: verify: The prover cannot establish an assertion (ArithmeticOperationRange) in method size: overflow in int difference
            if (max >= min) return max - min + 1;
                                       ^
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: This node should not be present in converting BasicPrograms to SMTLIB: class com.sun.tools.javac.tree.JCTree$JCFieldAccess /*missing*/.this$encl_55_55___17
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: This node should not be present in converting BasicPrograms to SMTLIB: class com.sun.tools.javac.tree.JCTree$JCFieldAccess /*missing*/.this$encl_55_55___20
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: This node should not be present in converting BasicPrograms to SMTLIB: class com.sun.tools.javac.tree.JCTree$JCFieldAccess /*missing*/.this$encl_55_55___15
error: A catastrophic JML internal error occurred.  Please report the bug with as much information as you can.
  Reason: This node should not be present in converting BasicPrograms to SMTLIB: class com.sun.tools.javac.tree.JCTree$JCFieldAccess /*missing*/.this$encl_55_55___17
5 errors
4 warnings
24 verification failures
--- my file ---
import java.util.*;
public /*@ nullable_by_default @*/ class BinaryTree {

    Node root;

    private class Node {
        Node left;
        Node right;
        int key;

        //logically in class Node, but cannot because Node can be null.
        /*@ pure @*/ static int size(Node n) {
            if(n==null) return 0;
            return(size(n.left)+1+size(n.right));
        }

        // Set of all keys that appear in the subtree below n.
        /*@ pure non_null @*/ static TreeSet<Integer> ks(Node n) {
            if (n == null) return new TreeSet<Integer>();
            TreeSet<Integer> r = new TreeSet<Integer>();    //<Integer>(new Integer[]{(Integer)});
            r.add(n.key);
            r.addAll(ks(n.left));
            r.addAll(ks(n.right));
            return r;
        }
    }

    // invariant: a BinaryTree should be acyclic
    //@ model public \set<Integer> keyset;
    // represents keyset = this.keySet(); // no type conversion

    // Set of all keys that appear in the BinaryTree.
    public /*@ pure non_null @*/
    TreeSet<Integer> keySet() {
        return Node.ks(root);
    }

    // Empty Binary Tree
    //@ pure
    BinaryTree() {
        root = null; //by default anyway
    }

    //Single-Node Binary Tree
    //@ pure
    BinaryTree(int r) {
        root = new Node();
        root.key = r; //left, right are null
    }

    //Usual constructor for Binary Tree: adds 1 node above existing ones.
    //@ pure
    BinaryTree(/*@ non_null @*/ BinaryTree left, /*@ non_null @*/ BinaryTree right, int r) {
        root = new Node();
        root.key = r;
        root.left = left.root;
        root.right = right.root;
    }

    /*@ requires depth >= 0;
   @ measured_by depth;
   @ normal_behaviour
   @ requires n == null;
   @ ensures \result == (depth <= 1);
   @ normal_behaviour
   @ requires n != null;
   @ requires depth>0;
   @ ensures  \result == (allNullAtOrPred(n.left,depth-1)&&
                   allNullAtOrPred(n.right,depth-1));
   @ normal_behaviour
   @ requires n != null;
   @ requires depth == 0;
  @ ensures  \result == false;
       pure @*/
    boolean allNullAtOrPred(Node n, int depth) {
        if (n == null) return (depth <= 1);
        else if (depth > 0)
            return allNullAtOrPred(n.left, depth - 1) &&
                    allNullAtOrPred(n.right, depth - 1);
        else return false;
    }

    /*@ ensures \result == (\exists int n;  n >= 0;
                             allNullAtOrPred(root,n));
     pure @*/
    boolean allNullAtNearlySameLevel() // l'argument est implicite dans la classe BinaryTree
    {
        return depthOfNull(root).size() <= 1;
    }

    ;

    private
    class Interval {
        int min;
        int max;

        //@ pure
        public Interval(int i, int j) {
            min = i;
            max = j;
        }
        // min > max means an empty interval. We suggest to normalize it to 1,0.
        //@ pure

        public int size() {
            if (max >= min) return max - min + 1;
            return 0;
        }

    } // end of class Interval -- henceforth nullable by default

    // returns the minimal interval of depth of occurrence of null pointers in the tree
    /*@ensures \fresh(\result);
    @ensures 0 <= \result.min <= \result.max;
    @pure
    non_null */   Interval depthOfNull(Node n) {
        if (n == null) return new Interval(0, 0);
        /*@ non_null */Interval ileft = depthOfNull(n.left);
        /*@ non_null */Interval iright = depthOfNull(n.right);
        return new Interval(1 + Math.min(ileft.min, iright.min), 1 + Math.max(ileft.max, iright.max));
    }

    public int size() {
        return Node.size(root);
    }

    public Object[] toArray() {
        return this.keySet().toArray();
    }

    /*@ requires a <= b;
    @ ensures Set.of(\result).equals(this.keySet().subSet(a,false,b,false));
     pure */
    public int[] between(int a, int b) {
        return btw(root, a, b);
    }

    Integer[] btwT(Node n, int a, int b) {
        return Node.ks(n).subSet(a,false,b,false).toArray(new Integer[0]);
    }
    /*@ requires a <= b;
    @ensures Set.of(\result).equals(Node.ks(n).subSet(a,false,b,false));
pure @*/
    int[] btw(Node n, int a, int b) {
        if (n == null) return new int[0];
        if (a <= n.key && b <= n.key) return btw(n.left, a, b);
        if (a >= n.key && b >= n.key) return btw(n.right, a, b);
        // else the root key is in the interval
        int[] r1 = btw(n.left, a, b);
        int[] r2 = btw(n.right, a, b);
        int[] r = Arrays.copyOf(r1, r1.length + 1 + r2.length);
        r[r1.length] = n.key;
        for (int i = 0; i < r2.length; i++)
            r[r1.length + 1 + i] = r2[i];
        return r;
    }
}

**Comment by davidcok** [comment]
A few immediate comments (not yet having had a chance to try to reproduce and analyze this submission).

— The first four warnings are because the library methods you have used do not yet have full specifications. You can ignore these.

— It is likely cut&paste or formatting in the git issue — what I see lacks a ‘*’ in the import statement and in public /@ nullable_by_default @*/ class BinaryTree {

— Some other head-scratching messages are because , in 

***@***.*** \fresh(\result);
@ensures 0 <= \result.min <= \result.max;
@pure
(and elsewhere), there is no space between the initial @ on a line and the next identifier, so there is confusion between JML and a Java annotation. Use a JML style that inserts whitespace there.

— I will look into the ‘catastrophic' errors.

— The others are classic verification errors — you need to improve your specifications (or correct the code) until they are provable. For example, you will need to impose limits on the size of your tree so that you do not get arithmetic overflows, or sometimes the computation can be restructured so that subexpressions do not overflow. Give a try to improving the specs — if you are puzzled about getting something to prove, I’m happy to offer advice.

— Note that you can use the -method option to limit the proof attempts to one method at a time (speeds up the debugging cycle).

David

**Comment by davidcok** [comment]
I would also suggest declaring class Node either (a) outside of BinaryTree as a secondary class in the file or (b) as static -- this might avoid the catastrophic error.

**Comment by pys** [comment]
Yes, it is git formatting : — It is likely cut&paste or formatting in the git issue — what I see lacks a ‘*’ in the import statement and in public /@ nullable_by_default @*/ class BinaryTree {
Github does not accept .java attachments -- I could change the suffix to .txt to  fool Github.

**Comment by pys** [comment]
Indeed, adding static to class Node solves the crash.

**Comment by davidcok** [comment]
Created test case gitbug814 to analyze the crash when 'Node' is not static.

**Comment by davidcok** [comment]
Crash fixed. Fix in version 12-0.6. Added issue #842 to embellish specs to make the verification successful.
